<!DOCTYPE html>
<html lang="de"><head>
<link href="../assets/dhbw_logo.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.19">

  <meta name="author" content="Prof.&nbsp;Dr.-Ing. Daniel Klünder">
  <title>Mikrocomputertechnik 3 – 04 · Aktorik &amp; Sicherheit</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-f355cf95444bdbe7a358cd689c441e6f.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
  <script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
  <link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&amp;display=swap" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">04 · Aktorik &amp; Sicherheit</h1>
  <p class="subtitle">Mikrocomputertechnik 3 · Von Hardware-Countern, PWM-Signalen und dem rettenden Watchdog</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Prof.&nbsp;Dr.-Ing. Daniel Klünder
</div>
</div>
</div>

</section>
<section id="willkommen-zu-block-4" class="slide level2">
<h2>Willkommen zu Block 4!</h2>
<ul>
<li>Willkommen zur vierten Vorlesung in Mikrocomputertechnik 3</li>
<li>Rückblick: In Block 3 hat der CLINT dem SoC einen Herzschlag (System-Tick) gegeben</li>
<li>Bisher: CPU reagiert auf Ereignisse (Interrupts) und verarbeitet Daten</li>
<li>Heute: das System wird aktiv — physikalische Welt steuern (Aktorik)</li>
<li>Sicherheitsnetz: Wer passt auf die CPU auf, wenn Software hängt?</li>
</ul>
<aside class="notes">
<p>Willkommen zu Block 4 knüpft an die bisherige Frage nach Signal und Überwachung an. CPU heißt Central Processing Unit, SoC System on Chip. CLINT ist der Core Local Interruptor, PLIC der Platform-Level Interrupt Controller. Eine LED ist eine Leuchtdiode. Der Prozessor kann Helligkeit rechnen, der Pin braucht daraus ein brauchbares Signal. PWM-Hardware und Watchdog haben verschiedene Aufgaben: eines formt das Ausgangssignal, das andere überwacht ausbleibenden Fortschritt. Ein System-Tick ist eine mögliche Architektur, kein Pflichtherzschlag. Solange Timer und Takt laufen, kann das letzte PWM-Signal weiterlaufen, auch wenn die Hauptschleife hängt. Willkommen zur vierten Vorlesung in Mikrocomputertechnik 3. Rückblick: In Block 3 hat der CLINT dem SoC einen Herzschlag (System-Tick) gegeben. Bisher: CPU reagiert auf Ereignisse (Interrupts) und verarbeitet Daten. Verständnischeck: Was passiert mit Hardware-PWM bei einem Hänger der Hauptschleife? Sie kann unverändert weiterlaufen. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="einordnung-im-semester" class="slide level2">
<h2>Einordnung im Semester</h2>
<div class="cell" data-reveal="true" data-fig-width="4.2" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%
flowchart LR
  A[Block 3: Interrupts] --&gt;|CPU reagiert| B[Block 4: Aktorik]
  B --&gt;|CPU steuert| C[LEDs und Motoren]
  D[Watchdog] -.-&gt;|Hardware schützt| B
  style B fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Einordnung im Semester knüpft an die bisherige Frage nach Signal und Überwachung an. Aktorik ist die Wirkung auf die Umwelt, nicht nur eine ausgegebene Zahl. Verfügbarkeit durch Neustart ist etwas anderes als ein definierter Zustand bei Gefahr. Funktionale Sicherheit wird hier nicht abgeschlossen. Block 3 liefert die monotone Zeit, mit der Fading-Schritte zu Sollzeitpunkten geplant werden. Verständnischeck: Warum ist Block 3 Voraussetzung? Ohne Zeitbasis gibt es kein festes 10-ms-Raster. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="anknüpfung-clint-tick-und-volatile" class="slide level2">
<h2>Anknüpfung: CLINT, Tick und volatile</h2>
<p>Kurz-Recap aus Block 3 (Vertiefung im Übungsblatt):</p>
<ul>
<li>CLINT liefert eine monotone Zeit für Termine, keinen PWM-Pin</li>
<li>Ein Folgetermin knüpft an den bisherigen Solltermin an</li>
<li><code>volatile</code> verhindert bestimmte Wegoptimierungen, nicht Atomarität</li>
<li>Die PWM-Flanken erzeugt später ein eigener Peripherietimer</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb1-1"><a aria-label="1"></a><span class="co">/* Lehrcode, verkürzt. Kein vollständiger Trap-Pfad.</span></span>
<span id="cb1-2"><a aria-label="2"></a><span class="co">   Relatives now+Intervall verschiebt das Raster. */</span></span>
<span id="cb1-3"><a aria-label="3"></a><span class="dt">void</span> timer_isr<span class="op">(</span><span class="dt">void</span><span class="op">)</span> <span class="op">{</span></span>
<span id="cb1-4"><a aria-label="4"></a>    <span class="cf">if</span> <span class="op">(</span>now <span class="op">&gt;=</span> next_deadline<span class="op">)</span> <span class="op">{</span></span>
<span id="cb1-5"><a aria-label="5"></a>        next_deadline <span class="op">+=</span> TICKS_PER_MS<span class="op">;</span></span>
<span id="cb1-6"><a aria-label="6"></a>        write_mtimecmp<span class="op">(</span>next_deadline<span class="op">);</span></span>
<span id="cb1-7"><a aria-label="7"></a>    <span class="op">}</span></span>
<span id="cb1-8"><a aria-label="8"></a><span class="op">}</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Anknüpfung: CLINT, Tick und volatile knüpft an die bisherige Frage nach Signal und Überwachung an. mtime und mtimecmp sind Zähler und Vergleich der Maschinenzeit. Ein Folgetermin read_mtime plus Intervall verschiebt das Raster um die ISR-Latenz. Bei 1 ms Soll und 20 µs konstanter Verspätung wird das Raster etwa 1,020 ms. An den alten Solltermin anzuknüpfen hält die Phase. uptime_ms plus plus zählt Aufrufe, nicht ausgelassene Perioden. volatile unterdrückt Wegoptimierungen und garantiert keine Atomarität und keinen konsistenten 64-Bit-Lesezugriff auf RV32. Das Attribut installiert keinen vollständigen Trap-Pfad. Die PWM-Trägerfrequenz kommt vom GPT, nicht vom CLINT. CLINT liefert eine monotone Zeit für Termine, keinen PWM-Pin. Ein Folgetermin knüpft an den bisherigen Solltermin an. <code>volatile</code> verhindert bestimmte Wegoptimierungen, nicht Atomarität. Verständnischeck: Was macht relatives Rearming bei 20 µs Verspätung? Das Raster wächst auf etwa 1,020 ms. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="von-der-zeitmessung-zur-weltsteuerung" class="slide level2">
<h2>Von der Zeitmessung zur Weltsteuerung</h2>
<ul>
<li>EVA-Prinzip: Eingabe, Verarbeitung, Ausgabe</li>
<li>Bisheriger Fokus: RAM (Verarbeitung) und Interrupts (Eingabe)</li>
<li>Fehlender Teil: Eingriff in die physikalische Welt</li>
<li>Aktorik setzt ein Kommando in Licht, Wärme oder Bewegung um</li>
<li>Ein Tastverhältnis ist offene Steuerung, keine Drehzahlregelung</li>
</ul>
<aside class="notes">
<p>Von der Zeitmessung zur Weltsteuerung knüpft an die bisherige Frage nach Signal und Überwachung an. EVA heißt Eingabe, Verarbeitung, Ausgabe. RAM ist der Arbeitsspeicher, nicht die Verarbeitung selbst. Ein Aktor setzt ein elektrisches Kommando in Licht, Wärme oder Bewegung um. 50 Prozent PWM ist offene Steuerung. Regelung bräuchte Messung und Vergleich. Die Lastenergie kommt meist aus einer eigenen Versorgung. EVA-Prinzip: Eingabe, Verarbeitung, Ausgabe. Bisheriger Fokus: RAM (Verarbeitung) und Interrupts (Eingabe). Fehlender Teil: Eingriff in die physikalische Welt. Verständnischeck: Ist 50 Prozent PWM schon Drehzahlregelung? Nein, Messung und Sollvergleich fehlen. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="eva-schema" class="slide level2">
<h2>EVA — Schema</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/04_aktorik_sicherheit/paths.png"></p>
<figcaption>Steuerpfad, Leistungsweg und Watchdog sind getrennte Ebenen.</figcaption>
</figure>
</div>
<div class="cell" data-reveal="true" data-fig-width="4" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%
flowchart LR
  E[Eingabe: Sensor] --&gt; V[Verarbeitung: SoC]
  V --&gt; A[Ausgabe: Aktorik]
  A --&gt; M[Motor / LED]
  style A fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>EVA — Schema knüpft an die bisherige Frage nach Signal und Überwachung an. GPIO ist ein digitaler Ein- und Ausgang. Der WDT ist der Watchdog Timer. Die Grafik trennt Signalpfeile von Leistungspfaden. Der 12-V-Motorstrom darf nicht durch den GPIO fließen. Ein gezeichneter Reset ist keine automatische Motorabschaltung. Verständnischeck: Warum nicht 12 V durch den GPIO? Der Pin liefert ein Steuerpegel und ist dafür nicht ausgelegt. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="das-problem-der-digitalen-welt" class="slide level2">
<h2>Das Problem der digitalen Welt</h2>
<ul>
<li>Die CPU lebt in einer binären Welt</li>
<li>GPIO-Pin: typisch nur HIGH (z. B. <span class="math inline">\(3{,}3\,\mathrm{V}\)</span>) oder LOW (<span class="math inline">\(0\,\mathrm{V}\)</span>)</li>
<li>Dilemma: der Pin kennt nur zwei Pegel. Helligkeit und Kraft folgen nicht linear aus einem Zwischenwert.</li>
<li>Viele MCU-Pins haben keinen stufenlosen Analogausgang (DAC)</li>
<li>Lösungsidee: Trägheit der realen Welt ausnutzen</li>
</ul>
<aside class="notes">
<p>Das Problem der digitalen Welt knüpft an die bisherige Frage nach Signal und Überwachung an. HIGH und LOW sind logische Zustände. 3,3 V und 0 V sind ideale Beispielpegel, keine RISC-V-Norm. Ein DAC wäre ein Digital-Analog-Wandler. PWM ändert Zeitanteile, nicht die Pulshöhe. Bei 50 Prozent liegen am ungefilterten Pin weiterhin 0 V und 3,3 V im Wechsel. 1,65 V ist der Mittelwert. Die CPU lebt in einer binären Welt. GPIO-Pin: typisch nur HIGH (z. B. <span class="math inline">\(3{,}3\,\mathrm{V}\)</span>) oder LOW (<span class="math inline">\(0\,\mathrm{V}\)</span>). Dilemma: der Pin kennt nur zwei Pegel. Helligkeit und Kraft folgen nicht linear aus einem Zwischenwert. Verständnischeck: Liegen dauerhaft 1,65 V an? Nein, das ist der zeitliche Mittelwert des Rechtecks. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="das-problem-der-software-fehler" class="slide level2">
<h2>Das Problem der Software-Fehler</h2>
<ul>
<li>Zuverlässigkeit: Was, wenn der Code in <code>while (1);</code> hängt?</li>
<li>Folgen: System reagiert nicht; Aktoren können unkontrolliert weiterlaufen</li>
<li>In sicherheitskritischen Domänen (Medizin, Avionik, Industrie) inakzeptabel</li>
<li>Bedarf: Hardware, die die CPU überwacht und im Notfall resetten kann</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="3.6" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%
flowchart TD
  A[Normaler Betrieb] --&gt; B{Software-Bug?}
  B --&gt;|ja| C[Freeze / Endlosschleife]
  C --&gt; D[Hardware muss eingreifen]
  style D fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Das Problem der Software-Fehler knüpft an die bisherige Frage nach Signal und Überwachung an. Eine Endlosschleife kann Instruktionen ausführen, ohne relevanten Fortschritt zu machen. Ein unabhängiger Abschaltpfad kann trotzdem arbeiten. Der Watchdog erkennt fehlenden Feed, nicht jeden falschen Helligkeitswert. Sicher ist anwendungsabhängig: Lampe aus ist nicht dasselbe wie Motor ausrollen oder halten. Zuverlässigkeit: Was, wenn der Code in <code>while (1);</code> hängt?. Folgen: System reagiert nicht; Aktoren können unkontrolliert weiterlaufen. In sicherheitskritischen Domänen (Medizin, Avionik, Industrie) inakzeptabel. Verständnischeck: Erkennt der Watchdog jeden falschen Helligkeitswert? Nein, wenn weiter gültig gefüttert wird. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="agenda-für-den-heutigen-tag" class="slide level2">
<h2>Agenda für den heutigen Tag</h2>
<ol type="1">
<li>Hardware-Counter und Timer-Architektur (warum der CLINT hier nicht reicht)</li>
<li>Pulsweitenmodulation (PWM) — Illusion analoger Signale</li>
<li>PWM-Erzeugung in Hardware (Compare-Register)</li>
<li>System-Sicherheit und Watchdog Timer (WDT)</li>
<li>Brückenschlag zum Labor (z. B. Renode und RGB-LEDs)</li>
</ol>
<aside class="notes">
<p>Agenda für den heutigen Tag knüpft an die bisherige Frage nach Signal und Überwachung an. GPT heißt General Purpose Timer. PWM ist Pulsweitenmodulation. RGB steht für Rot, Grün und Blau. Renode ist ein optionaler, nicht ausgeführter Laborausblick. Der CLINT plant Softwaretermine, der GPT erzeugt im Modell den Pinimpuls. Zuerst muss klar sein, warum der Aktor ohne Hauptschleife weiterlaufen kann. Verständnischeck: Warum nicht sofort Watchdog-Code? Weil das Weiterlaufen der PWM sonst unverständlich bleibt. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="lernziele-block-4" class="slide level2">
<h2>Lernziele Block 4</h2>
<ul>
<li>Aufbau eines General Purpose Timers (GPT) inkl. Prescaler erklären</li>
<li>Mathematik der PWM verstehen (Frequenz, Duty Cycle)</li>
<li>Begründen, warum Software-PWM (Bit-Banging) die CPU belastet und Timing gefährdet</li>
<li>Watchdog Timer (WDT) korrekt konfigurieren und „füttern“</li>
<li>Typische Anfängerfehler beim WDT vermeiden</li>
</ul>
<aside class="notes">
<p>Lernziele Block 4 knüpft an die bisherige Frage nach Signal und Überwachung an. Prüfbar sind Frequenz aus Takt, PSC und ARR, CCR für ein Tastverhältnis, eine verspätete Softwareflanke, Feed an Fortschritt und die Grenzen eines Resets. PSC, CNT, ARR und CCR sind Register eines Timermodells, keine RISC-V-Register. Eine reale Konfiguration braucht Taktquelle, Registersemantik, Pinbelegung und Beschaltung. Aufbau eines General Purpose Timers (GPT) inkl. Prescaler erklären. Mathematik der PWM verstehen (Frequenz, Duty Cycle). Begründen, warum Software-PWM (Bit-Banging) die CPU belastet und Timing gefährdet. Verständnischeck: Welche Zusatzinformation fehlt? Datenblatt, Pin-Mux und Ausgangsbeschaltung. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-leitfrage-des-tages" class="slide level2">
<h2>Die Leitfrage des Tages</h2>
<ul>
<li>SoC-Pin: oft maximal <span class="math inline">\(3{,}3\,\mathrm{V}\)</span> (100 %) oder <span class="math inline">\(0\,\mathrm{V}\)</span> (0 %)</li>
<li>Ziel im Beispiel: 50 Prozent Tastverhaeltnis. Das ist nicht allgemein halbe Motorleistung.</li>
<li>Ohne externe Bauteile wie digitale Potentiometer</li>
<li>Wie dimmt man auf 50 %, wenn der Pin nur „Vollgas“ oder „Aus“ kennt?</li>
</ul>
<aside class="notes">
<p>Die Leitfrage des Tages knüpft an die bisherige Frage nach Signal und Überwachung an. Die Leitfrage ist 50 Prozent aktive Zeit, nicht 50 Prozent Motorleistung oder Helligkeit. Ohne zusätzlichen Analogwandler bleibt das Steuersignal digital. Der Pin erzeugt ein Kommando, der Motor braucht eine Leistungsstufe. SoC-Pin: oft maximal <span class="math inline">\(3{,}3\,\mathrm{V}\)</span> (100 %) oder <span class="math inline">\(0\,\mathrm{V}\)</span> (0 %). Ziel im Beispiel: 50 Prozent Tastverhaeltnis. Das ist nicht allgemein halbe Motorleistung. Ohne externe Bauteile wie digitale Potentiometer. Verständnischeck: Was ist bei idealen 50 Prozent Active-High sicher? HIGH und LOW dauern gleich lang. Die Wirkung ist damit nicht bestimmt. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="leitfrage-schema" class="slide level2">
<h2>Leitfrage — Schema</h2>
<div class="cell" data-reveal="true" data-fig-width="3.8" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%
flowchart LR
  H[3.3 V HIGH] --&gt;|Trick?| M[Motor bei 50 %]
  L[0 V LOW] --&gt;|Trick?| M
  style M fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Leitfrage — Schema knüpft an die bisherige Frage nach Signal und Überwachung an. Zwei Pulse gleicher Höhe und verschiedener Breite haben verschiedene Mittelwerte. Die gestrichelte Linie ist ein rechnerischer Mittelwert, keine ungefilterte Pinspannung. Der Treiber und die Versorgung gehören zum Motorpfad. Verständnischeck: Warum sind gleiche Höhe und verschiedene Breite nicht dasselbe Signal? Der aktive Zeitanteil unterscheidet sich. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="clint-vs.-peripherie-timer" class="slide level2">
<h2>CLINT vs.&nbsp;Peripherie-Timer</h2>
<ul>
<li>Warum nicht einfach <code>mtime</code> aus Block 3 für Aktorik?</li>
<li>CLINT: 64-Bit-System-Timer — läuft durch, darf nicht „wild“ zurückgesetzt werden (OS-Zeitbasis)</li>
<li>Aktorik braucht Timer, die periodisch bei 0 neu starten und mit Ausgangspins verbunden sind</li>
<li>Lösung: General Purpose Timers (GPT) in der Peripherie — oft viele pro SoC</li>
</ul>
<aside class="notes">
<p>CLINT vs.&nbsp;Peripherie-Timer knüpft an die bisherige Frage nach Signal und Überwachung an. Die Systemzeit plant alle 10 ms einen Stellwert. Der PWM-Zähler läuft mit 1 kHz, also zehn Perioden je Fading-Schritt. 10 MHz Systemzeit und 1 MHz Counter sind verschiedene Zähler. Hardware-PWM ist keine CLINT- und keine RISC-V-ISA-Funktion. Warum nicht einfach <code>mtime</code> aus Block 3 für Aktorik?. CLINT: 64-Bit-System-Timer — läuft durch, darf nicht „wild“ zurückgesetzt werden (OS-Zeitbasis). Aktorik braucht Timer, die periodisch bei 0 neu starten und mit Ausgangspins verbunden sind. Verständnischeck: Bleibt ein Helligkeitswert 10 ms, während zehn PWM-Perioden laufen? Ja, bei 1 kHz und 10-ms-Schritten. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="der-general-purpose-timer-gpt" class="slide level2">
<h2>Der General Purpose Timer (GPT)</h2>
<ul>
<li>Flexibles Zählwerk in Hardware, unabhängig vom RISC-V-Kern</li>
<li>Aufgaben: externe Ereignisse zählen, Zeit stoppen, Pulsmuster auf Pins ausgeben</li>
<li>Heute: programmierbarer Signalgenerator — nicht „System-Uhr“</li>
<li>Konfiguration über Memory-Mapped Register (MMIO)</li>
</ul>
<aside class="notes">
<p>Der General Purpose Timer (GPT) knüpft an die bisherige Frage nach Signal und Überwachung an. Der Timer liegt außerhalb des Rechenwerks. MMIO heißt Memory-Mapped Input/Output. TIM, PSC und ARR sind ein STM32-nahes Lehrmodell, keine RISC-V-Namen. Ein Schreiben konfiguriert Hardware, es legt nicht nur eine RAM-Variable ab. Flexibles Zählwerk in Hardware, unabhängig vom RISC-V-Kern. Aufgaben: externe Ereignisse zählen, Zeit stoppen, Pulsmuster auf Pins ausgeben. Heute: programmierbarer Signalgenerator — nicht „System-Uhr“. Verständnischeck: Was bedeutet ein MMIO-Schreiben? Es verändert einen Hardwarezustand nach Registervertrag. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="anatomie-eines-hardware-counters" class="slide level2">
<h2>Anatomie eines Hardware-Counters</h2>
<p>Drei Kernbausteine:</p>
<ul>
<li>Clock Source: oft Systemtakt (z. B. <span class="math inline">\(100\,\mathrm{MHz}\)</span>)</li>
<li>Prescaler (PSC): Vorteiler, drosselt den Takt</li>
<li>Counter-Register (CNT): Zählwert (typisch 16- oder 32-Bit)</li>
</ul>
<p>Jeder Tick hinter dem Prescaler erhöht <code>CNT</code> um 1.</p>
<aside class="notes">
<p>Anatomie eines Hardware-Counters knüpft an die bisherige Frage nach Signal und Überwachung an. 100 MHz sind 100 Millionen Eingangsperioden je Sekunde, hier eine Modellannahme am Timer-Eingang. Ein Tick erhöht CNT nur im Up-Counting. 16 Bit bieten 65536 Zustände von 0 bis 65535. Ein freier Durchlauf bei 100 MHz dauert 655,36 µs. Clock Source: oft Systemtakt (z. B. <span class="math inline">\(100\,\mathrm{MHz}\)</span>). Prescaler (PSC): Vorteiler, drosselt den Takt. Counter-Register (CNT): Zählwert (typisch 16- oder 32-Bit). Verständnischeck: Wie lange dauern 65536 Intervalle bei 100 MHz? 655,36 µs. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="counter-kette-schema" class="slide level2">
<h2>Counter-Kette — Schema</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/04_aktorik_sicherheit/prescaler.png"></p>
<figcaption>100 MHz durch PSC+1. PSC 99 ergibt 1 MHz. 16 Bit hat 65536 Zustaende.</figcaption>
</figure>
</div>
<div class="cell" data-reveal="true" data-fig-width="4" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%
flowchart LR
  A[System Clock\n100 MHz] --&gt;|Takt| B[Prescaler PSC]
  B --&gt;|verlangsamt| C[Counter CNT]
  style B fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Counter-Kette — Schema knüpft an die bisherige Frage nach Signal und Überwachung an. PSC gleich 99 teilt durch 100. 100 MHz geteilt durch 100 ist 1 MHz, also 1 µs je Tick. Die 65536 Zustände sind die Registerbreite. ARR gleich 999 benutzt später nur 1000 Intervalle. Die Pfeile sind Takte, kein Instruktionsfluss. Verständnischeck: Wie lange dauert ein voller 16-Bit-Durchlauf nach der Teilung? 65536 µs, also 65,536 ms, ohne kleinere ARR-Grenze. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="der-prescaler-vorteiler" class="slide level2">
<h2>Der Prescaler (Vorteiler)</h2>
<ul>
<li>Problem: <span class="math inline">\(100\,\mathrm{MHz}\)</span> = <span class="math inline">\(10^{8}\)</span> Ticks/s; 16-Bit-Max <span class="math inline">\(\approx 65\,535\)</span> → Überlauf in unter 1 ms</li>
<li>Lösung: Prescaler lässt nur jeden <span class="math inline">\(n\)</span>-ten Takt durch</li>
<li>Typisch: Registerwert <span class="math inline">\(PSC\)</span>, Teilung durch <span class="math inline">\(PSC + 1\)</span> (weil 0 mitzählt)</li>
<li>Beispiel: <span class="math inline">\(PSC = 99\)</span> → Teiler 100 → langsameres Zählen, längere Messfenster</li>
</ul>
<aside class="notes">
<p>Der Prescaler (Vorteiler) knüpft an die bisherige Frage nach Signal und Überwachung an. Im Modell bedeutet Registerwert 0 den Teiler 1, Wert 99 den Teiler 100. Null stoppt den Timer nicht. Für den Überlauf zählen 65536 Intervalle, nicht nur der Zahlenwert 65535. Die Semantik ist datenblattabhängig und hier festgesetzt. Problem: <span class="math inline">\(100\,\mathrm{MHz}\)</span> = <span class="math inline">\(10^{8}\)</span> Ticks/s; 16-Bit-Max <span class="math inline">\(\approx 65\,535\)</span> → Überlauf in unter 1 ms. Lösung: Prescaler lässt nur jeden <span class="math inline">\(n\)</span>-ten Takt durch. Typisch: Registerwert <span class="math inline">\(PSC\)</span>, Teilung durch <span class="math inline">\(PSC + 1\)</span> (weil 0 mitzählt). Verständnischeck: Welcher PSC ergibt 1 MHz? PSC plus 1 gleich 100, also PSC gleich 99. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="mathematik-zählfrequenz" class="slide level2">
<h2>Mathematik: Zählfrequenz</h2>
<p><span class="math display">\[
f_{\mathrm{cnt}} = \frac{f_{\mathrm{clock}}}{PSC + 1}
\]</span></p>
<p>Beispiel: <span class="math inline">\(f_{\mathrm{clock}} = 100\,\mathrm{MHz}\)</span>, <span class="math inline">\(PSC = 9999\)</span></p>
<p><span class="math display">\[
f_{\mathrm{cnt}} = \frac{10^{8}}{10^{4}} = 10\,\mathrm{kHz}
\]</span></p>
<p>→ Counter erhöht sich <span class="math inline">\(10\,000\)</span>-mal pro Sekunde (alle <span class="math inline">\(0{,}1\,\mathrm{ms}\)</span>).</p>
<aside class="notes">
<p>Mathematik: Zählfrequenz knüpft an die bisherige Frage nach Signal und Überwachung an. f_cnt gleich f_clock geteilt durch PSC plus 1. PSC gleich 9999 ergibt 10 kHz und 100 µs je Tick. Das ist eine Rechenvariante, nicht der spätere PSC 99. PWM-Frequenz braucht zusätzlich N Intervalle. 10 kHz Zähltakt und N gleich 1000 ergäben nur 10 Hz PWM. Verständnischeck: Sind 10 kHz Zähltakt automatisch 10 kHz PWM? Nein. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="das-auto-reload-register-arr" class="slide level2">
<h2>Das Auto-Reload Register (ARR)</h2>
<ul>
<li>Wo endet das Zählen? → Auto-Reload / Period Register (ARR)</li>
<li>Programmierte Periodengrenze in diesem Up-Counting-Modell</li>
<li><code>CNT = ARR</code> gilt einen vollen Tick; der nächste Tick setzt auf 0</li>
<li>Die Periode hat N = ARR+1 Intervalle</li>
<li>Im Kernmodell: PSC+1, Vergleich <code>CNT &lt; CCR</code>, Active-High</li>
</ul>
<aside class="notes">
<p>Das Auto-Reload Register (ARR) knüpft an die bisherige Frage nach Signal und Überwachung an. ARR ist die programmierte Grenze, nicht die Registerbreite. CNT gleich 999 dauert einen vollen Tick, danach folgt 0. N gleich ARR plus 1. Bei 1 MHz und ARR 999 ist T gleich 1000 µs. CNT von 0 bis 9 einschließlich sind zehn Intervalle, ARR gleich 9. Wo endet das Zählen? → Auto-Reload / Period Register (ARR). Programmierte Periodengrenze in diesem Up-Counting-Modell. <code>CNT = ARR</code> gilt einen vollen Tick; der nächste Tick setzt auf 0. Verständnischeck: Wie viele Intervalle hat CNT gleich 0 bis 9? Zehn, also N gleich 10. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="zähl-modus-up-counting" class="slide level2">
<h2>Zähl-Modus: Up-Counting</h2>
<ul>
<li>Standard für viele GPT-Anwendungen</li>
<li>Ablauf: 0 → hoch bis ARR → Reset auf 0</li>
<li>Signalform: Sägezahn</li>
<li>Einsatz: Zeitmessung, periodische Interrupts, einfache PWM</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Phase</th>
<th>CNT</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Start</td>
<td>0</td>
</tr>
<tr class="even">
<td>Mitte</td>
<td>steigt</td>
</tr>
<tr class="odd">
<td>Grenze</td>
<td>ARR</td>
</tr>
<tr class="even">
<td>Danach</td>
<td>0 (neu)</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Zähl-Modus: Up-Counting knüpft an die bisherige Frage nach Signal und Überwachung an. Up-Counting ist eine Treppe, kein glatter Sägezahn. Nach dem vollständigen ARR-Intervall setzt der nächste Tick auf null. Ein Update kann Register übernehmen, muss aber keinen CPU-Interrupt erzeugen. Bei ARR gleich 3 gehören 0, 1, 2 und 3 zu einer Periode. Standard für viele GPT-Anwendungen. Ablauf: 0 → hoch bis ARR → Reset auf 0. Signalform: Sägezahn. Verständnischeck: Welche Werte hat eine Periode bei ARR gleich 3? 0, 1, 2 und 3. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="zähl-modus-down-counting" class="slide level2">
<h2>Zähl-Modus: Down-Counting</h2>
<ul>
<li>Umgekehrt: Start bei ARR, herunter bis 0</li>
<li>Bei 0 oft Event/Interrupt; Neu laden mit ARR</li>
<li>Signalform: fallender Sägezahn</li>
<li>Einsatz: Timeouts; verwandt mit manchen SysTick-Konzepten (z. B. Cortex-M)</li>
</ul>
<aside class="notes">
<p>Zähl-Modus: Down-Counting knüpft an die bisherige Frage nach Signal und Überwachung an. Down-Counting braucht eine eigene Regel, wann null ein Intervall ist und wann neu geladen wird. Die Formel CNT kleiner CCR gilt nicht ungeprüft. SysTick ist ein ARM-Cortex-M-Zeitgeber, kein RISC-V-Modul. Umgekehrt: Start bei ARR, herunter bis 0. Bei 0 oft Event/Interrupt; Neu laden mit ARR. Signalform: fallender Sägezahn. Verständnischeck: Was fehlt bei Startwert 3? Welche Zustände wie lange gelten und wann das Ablaufereignis kommt. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="zähl-modus-center-aligned" class="slide level2">
<h2>Zähl-Modus: Center-Aligned</h2>
<ul>
<li>Fortgeschrittener Modus: 0 → ARR → wieder zurück nach 0 (Richtungsumkehr)</li>
<li>Signalform: Dreieck</li>
<li>Einsatz: moderne Motorsteuerung (z. B. FOC), Wechselrichter</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Phase</th>
<th>Verhalten</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aufwärts</td>
<td>0 → ARR</td>
</tr>
<tr class="even">
<td>Abwärts</td>
<td>ARR → 0</td>
</tr>
<tr class="odd">
<td>Form</td>
<td>Dreieck</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Zähl-Modus: Center-Aligned knüpft an die bisherige Frage nach Signal und Überwachung an. Center-Aligned kehrt die Richtung um. BLDC ist ein bürstenloser Gleichstrommotor, FOC feldorientierte Regelung, beides nur Ausblick. Im kleinen Modell ARR gleich 4 lautet die Folge 0, 1, 2, 3, 4, 3, 2, 1 und dann wieder 0, also acht Ticks. Die Edge-Formel ARR plus 1 gilt hier nicht automatisch. Fortgeschrittener Modus: 0 → ARR → wieder zurück nach 0 (Richtungsumkehr). Signalform: Dreieck. Einsatz: moderne Motorsteuerung (z. B. FOC), Wechselrichter. Verständnischeck: Darf man dieselbe PWM-Frequenz wie im Up-Counting annehmen? Nein, der Auf-und-ab-Zyklus hat eine andere Intervallzahl. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fragen-counter-und-gpt" class="slide level2">
<h2>Fragen? — Counter und GPT</h2>
<ul>
<li>Rolle von Prescaler (PSC) und Auto-Reload (ARR) klar?</li>
<li>Zählfrequenz <span class="math inline">\(f_{\mathrm{cnt}}\)</span> berechnen können?</li>
<li>Up-Counting vs.&nbsp;Center-Aligned unterschieden?</li>
<li>Warum Datenblatt zu <span class="math inline">\(ARR\)</span> vs.&nbsp;<span class="math inline">\(ARR+1\)</span> prüfen?</li>
</ul>
<aside class="notes">
<p>Fragen? — Counter und GPT knüpft an die bisherige Frage nach Signal und Überwachung an. PSC setzt den Countertakt, ARR die Periodengrenze im gewählten Modus. Mit 100 MHz, PSC 99 und ARR 999 bleibt das Kernmodell bei 1 kHz. Steigt nur PSC auf 199, halbieren sich f_cnt und f_PWM auf 500 kHz und 500 Hz. D bei gleichem CCR bleibt gleich. Rolle von Prescaler (PSC) und Auto-Reload (ARR) klar?. Zählfrequenz <span class="math inline">\(f_{\mathrm{cnt}}\)</span> berechnen können?. Up-Counting vs.&nbsp;Center-Aligned unterschieden?. Verständnischeck: Was ändert PSC gleich 199? Frequenz halbiert, Duty bei gleichem CCR nicht. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-analoge-illusion" class="slide level2">
<h2>Die analoge Illusion</h2>
<ul>
<li>Zurück zur Leitfrage: 50 Prozent aktive Zeit an einem binären Pin?</li>
<li>Trick: Pin sehr schnell ein- und ausschalten</li>
<li>Beispiel: 1 kHz, je Hälfte der Periode HIGH/LOW</li>
<li>Motor und Auge sind zu träge, um dem Stottern zu folgen</li>
<li>Effekt: schnelles Schalten. Wahrnehmung und mechanische Wirkung sind davon zu trennen.</li>
</ul>
<aside class="notes">
<p>Die analoge Illusion knüpft an die bisherige Frage nach Signal und Überwachung an. Bei T gleich 1 ms und je 0,5 ms HIGH und LOW bleibt die Periode gleich, wenn nur das Tastverhältnis auf 25 Prozent fällt. Die Pulsdauer wird kürzer. 1 kHz ist kein Garant gegen Flimmern, Kamerabänder oder Geräusche. Trägheit gehört zur Last, nicht zum Pin. Zurück zur Leitfrage: 50 Prozent aktive Zeit an einem binären Pin?. Trick: Pin sehr schnell ein- und ausschalten. Beispiel: 1 kHz, je Hälfte der Periode HIGH/LOW. Verständnischeck: Was bleibt bei festem f_PWM gleich? Periode und Pegelhöhe. Die aktive Dauer ändert sich. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="was-ist-pwm" class="slide level2">
<h2>Was ist PWM?</h2>
<ul>
<li>Pulsweitenmodulation (PWM, Pulse Width Modulation)</li>
<li>Wichtige Schnittstelle: digitale Steuerung und Leistungselektronik</li>
<li>Grundfrequenz bleibt konstant; die Pulsweite (HIGH-Anteil) wird moduliert</li>
<li>Breiter Puls → viel Energie; schmaler Puls → wenig Energie</li>
</ul>
<aside class="notes">
<p>Was ist PWM knüpft an die bisherige Frage nach Signal und Überwachung an. PWM verändert die aktive Dauer bei fester Periode. Breiter Puls bedeutet mehr Energie nur bei gleicher Spannung und Last. Ein Servo nutzt die Pulsbreite später als Information. 1 ms bei T gleich 2 ms ist 50 Prozent, bei T gleich 20 ms nur 5 Prozent. Pulsweitenmodulation (PWM, Pulse Width Modulation). Wichtige Schnittstelle: digitale Steuerung und Leistungselektronik. Grundfrequenz bleibt konstant; die Pulsweite (HIGH-Anteil) wird moduliert. Verständnischeck: Sind 1-ms-Pulse bei 2 ms und 20 ms dasselbe Tastverhältnis? Nein, 50 beziehungsweise 5 Prozent. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="periode-und-frequenz" class="slide level2">
<h2>Periode und Frequenz</h2>
<ul>
<li>Periode <span class="math inline">\(T\)</span>: Dauer eines Zyklus (HIGH + LOW)</li>
<li>Frequenz <span class="math inline">\(f = 1/T\)</span></li>
<li>Zu niedrige <span class="math inline">\(f\)</span> (z. B. 10 Hz): sichtbares Flackern, ruckelige Motoren</li>
<li>Richtwerte (Faustregeln): LEDs oft <span class="math inline">\(\gtrsim 200\,\mathrm{Hz}\)</span>; Motoren oft 10–20 kHz (weniger hörbares Fiepen)</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Abschnitt</th>
<th>Bedeutung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>HIGH</td>
<td>Energie ein</td>
</tr>
<tr class="even">
<td>LOW</td>
<td>Energie aus</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(T\)</span></td>
<td>ein voller Zyklus</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Periode und Frequenz knüpft an die bisherige Frage nach Signal und Überwachung an. f gleich 1 geteilt durch T. 1 ms ist 0,001 s, also 1000 Hz. HIGH und LOW sind Kommandopegel im Active-High-Modell. In LOW kann Freilaufstrom fließen. 20 kHz haben eine Periode von 50 µs. Frequenzwahl hängt von Treiber, Last und Auflösung ab. Periode <span class="math inline">\(T\)</span>: Dauer eines Zyklus (HIGH + LOW). Frequenz <span class="math inline">\(f = 1/T\)</span>. Zu niedrige <span class="math inline">\(f\)</span> (z. B. 10 Hz): sichtbares Flackern, ruckelige Motoren. Verständnischeck: Wie lang ist eine Periode bei 20 kHz? 50 µs. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="der-duty-cycle-tastverhältnis" class="slide level2">
<h2>Der Duty Cycle (Tastverhältnis)</h2>
<ul>
<li>Wichtigste PWM-Größe: Anteil der HIGH-Zeit an der Periode</li>
</ul>
<p><span class="math display">\[
\mathrm{Duty\ Cycle} = \frac{t_{\mathrm{HIGH}}}{T}
\]</span></p>
<ul>
<li>Anteil der aktiven Zeit im gewählten PWM-Modell</li>
<li>Periode/Frequenz konstant; wir ändern den Duty Cycle</li>
</ul>
<aside class="notes">
<p>Der Duty Cycle (Tastverhältnis) knüpft an die bisherige Frage nach Signal und Überwachung an. D_aktiv ist t_aktiv geteilt durch T, zwischen 0 und 1. Im Active-High-Modell ist das der HIGH-Anteil. Bei Active-Low ist der HIGH-Anteil 1 minus D_aktiv. 250 µs aktiv bei 1000 µs sind 25 Prozent, unabhängig vom aktiven Pegel. Wichtigste PWM-Größe: Anteil der HIGH-Zeit an der Periode. Anteil der aktiven Zeit im gewählten PWM-Modell. Periode/Frequenz konstant; wir ändern den Duty Cycle. Verständnischeck: Wie groß ist D bei 250 µs aktiv und T gleich 1000 µs? 0,25. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="duty-cycle-in-prozent" class="slide level2">
<h2>Duty Cycle in Prozent</h2>
<p>Bei konstanter Frequenz:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Duty Cycle</th>
<th>Wirkung (qualitativ)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10 %</td>
<td>kurze Pulse; schwach</td>
</tr>
<tr class="even">
<td>50 %</td>
<td>halbe aktive Zeit</td>
</tr>
<tr class="odd">
<td>90 %</td>
<td>fast dauerhaft HIGH</td>
</tr>
</tbody>
</table>
<p>Die Periode bleibt gleich — nur die fallende Flanke wandert.</p>
<aside class="notes">
<p>Duty Cycle in Prozent knüpft an die bisherige Frage nach Signal und Überwachung an. Bei T gleich 1 ms dauern 10, 50 und 90 Prozent 100, 500 und 900 µs. Die fallende Flanke wandert nur in der gezeigten Edge-Aligned-Active-High-Darstellung. Die Wirkung ist eine Tendenz, keine garantierte Licht- oder Motorleistung. Verständnischeck: Welche Pulsdauer hat 90 Prozent bei 1 kHz? 900 µs. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="mittlere-spannung-berechnen" class="slide level2">
<h2>Mittlere Spannung berechnen</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/04_aktorik_sicherheit/pwm-power.png"></p>
<figcaption>25 Prozent: Mittelwert 0,825 V, RMS 1,65 V. Ohmsche Rechteckleistung ist nicht Vmittel zum Quadrat durch R.</figcaption>
</figure>
</div>
<p>Zeitlicher Mittelwert über die Periode (nicht der Effektivwert/RMS):</p>
<p><span class="math display">\[
\bar{V} = V_{\mathrm{Pin}} \times \mathrm{Duty\ Cycle}
\]</span></p>
<p>Beispiel: <span class="math inline">\(V_{\mathrm{Pin}} = 3{,}3\,\mathrm{V}\)</span>, Duty Cycle <span class="math inline">\(= 25\,\%\)</span> <span class="math inline">\(= 0{,}25\)</span></p>
<p><span class="math display">\[
\bar{V} = 3{,}3\,\mathrm{V} \times 0{,}25 = 0{,}825\,\mathrm{V}
\]</span></p>
<p>Zum Vergleich RMS eines Rechtecksignals: <span class="math inline">\(V_{\mathrm{RMS}} = V_{\mathrm{Pin}} \cdot \sqrt{D}\)</span> — bei 25 % also <span class="math inline">\(\approx 1{,}65\,\mathrm{V}\)</span>. Bei idealer ohmscher Last gilt <span class="math inline">\(P=D\cdot V^2/R\)</span>, nicht <span class="math inline">\(V_{\mathrm{avg}}^2/R\)</span> fuer das ungefilterte Rechteck.</p>
<aside class="notes">
<p>Mittlere Spannung berechnen knüpft an die bisherige Frage nach Signal und Überwachung an. V_mittel gleich D mal 3,3 V. V_RMS, der Effektivwert, ist 3,3 V mal Wurzel aus D. Bei D gleich 0,25 sind das 0,825 V und 1,65 V. Für R gleich 100 Ohm ist die mittlere Rechteckleistung D mal V quadrat geteilt durch R, also 27,225 mW. Das Quadrat des Mittelwerts ergibt nur 6,806 mW und unterschätzt die Heizwirkung. LOW gleich 0, ideale Flanken und ohmsche Last sind Annahmen. Die Mittelwertlinie ist kein gefilterter Ausgang. Verständnischeck: Warum ist der Effektivwert größer? Die hohen Pulse gehen quadratisch ein. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="auflösung-resolution" class="slide level2">
<h2>Auflösung (Resolution)</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/04_aktorik_sicherheit/resolution.png"></p>
<figcaption>Bei 1 MHz: 1 kHz hat 0,1 Prozent Schritt, 20 kHz hat 2 Prozent.</figcaption>
</figure>
</div>
<ul>
<li>Nutzbare Schrittweite im Kernmodell: 1/N mit N = ARR+1</li>
<li>16 Bit sind die Registergrenze, nicht automatisch 16 Bit PWM-Auflösung</li>
<li>Bei 1 MHz: 1 kHz hat 0,1 Prozentpunkte, 20 kHz hat 2 Prozentpunkte</li>
</ul>
<aside class="notes">
<p>Auflösung (Resolution) knüpft an die bisherige Frage nach Signal und Überwachung an. Die Schrittweite ist 1/N. Bei 1 MHz sind N gleich 1000, 250 und 50 für 1, 4 und 20 kHz, ARR gleich 999, 249 und 49, Schritte 0,1, 0,4 und 2 Prozentpunkte. log2 von N ist etwa 9,97, 7,97 und 5,64 Bit des Zeitrasters. N Intervalle und N plus 1 Schwellen sind verschieden. Ein 16-Bit-CCR kann N gleich 65536 nicht halten. Nutzbare Schrittweite im Kernmodell: 1/N mit N = ARR+1. 16 Bit sind die Registergrenze, nicht automatisch 16 Bit PWM-Auflösung. Bei 1 MHz: 1 kHz hat 0,1 Prozentpunkte, 20 kHz hat 2 Prozentpunkte. Verständnischeck: Warum sinkt die Auflösung bei höherer PWM-Frequenz? Pro Periode bleiben weniger Ticks. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="warum-nicht-software-bit-banging" class="slide level2">
<h2>Warum nicht Software? (Bit-Banging)</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/04_aktorik_sicherheit/sw-vs-hw.png"></p>
<figcaption>20 us verspaetete Flanke: Periode 120 us, etwa 58,3 Prozent. Hardware-PWM folgt dem Timer.</figcaption>
</figure>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb2-1"><a aria-label="1"></a><span class="co">/* Software-PWM — blockiert die CPU */</span></span>
<span id="cb2-2"><a aria-label="2"></a><span class="cf">while</span> <span class="op">(</span><span class="dv">1</span><span class="op">)</span> <span class="op">{</span></span>
<span id="cb2-3"><a aria-label="3"></a>    set_pin_high<span class="op">();</span></span>
<span id="cb2-4"><a aria-label="4"></a>    delay_us<span class="op">(</span><span class="dv">50</span><span class="op">);</span>   <span class="co">/* 50 % HIGH */</span></span>
<span id="cb2-5"><a aria-label="5"></a>    set_pin_low<span class="op">();</span></span>
<span id="cb2-6"><a aria-label="6"></a>    delay_us<span class="op">(</span><span class="dv">50</span><span class="op">);</span></span>
<span id="cb2-7"><a aria-label="7"></a><span class="op">}</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li>CPU zu 100 % im Busy Waiting — keine andere Arbeit</li>
<li>Jeder Interrupt zerstört das Timing</li>
</ul>
<aside class="notes">
<p>Warum nicht Software? (Bit-Banging) knüpft an die bisherige Frage nach Signal und Überwachung an. Bit-Banging schaltet den Pin in Software. Die gezeigte Warteschleife bindet den Vordergrund, nicht jede Software-PWM muss die CPU voll belegen. Ein angenommener 20-µs-Interrupt vor der fallenden Flanke macht HIGH 70 µs, LOW 50 µs, T 120 µs und D etwa 58,33 Prozent. Das ist eine Rechnung, keine Ausführung. Trifft die Verzögerung LOW, sinkt D auf etwa 41,67 Prozent. CPU zu 100 % im Busy Waiting — keine andere Arbeit. Jeder Interrupt zerstört das Timing. Verständnischeck: Was passiert, wenn die 20 µs in LOW fallen? D sinkt auf etwa 41,67 Prozent. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="timing-problem-jitter" class="slide level2">
<h2>Timing-Problem: Jitter</h2>
<ul>
<li>Auch mit Timer-ISRs statt <code>delay()</code>: andere Interrupts (z. B. UART) verzögern Toggles</li>
<li>Jitter: unbestimmte Verschiebung der Flanken</li>
<li>Folge: Duty Cycle schwankt → Motor zuckt, LED blitzt</li>
</ul>
<aside class="notes">
<p>Timing-Problem: Jitter knüpft an die bisherige Frage nach Signal und Überwachung an. Latenz ist Verzögerung, Jitter ihre Schwankung. Eine gleiche Verschiebung beider Flanken um 5 µs ändert die Pulsdauer nicht, wohl die Phase. UART ist eine serielle Schnittstelle. Zucken oder Blitzen sind mögliche Folgen, kein allgemeiner Lagerschaden. Auch mit Timer-ISRs statt <code>delay()</code>: andere Interrupts (z. B. UART) verzögern Toggles. Jitter: unbestimmte Verschiebung der Flanken. Folge: Duty Cycle schwankt → Motor zuckt, LED blitzt. Verständnischeck: Ändern 5 µs auf beiden Flanken die Pulsdauer? Nein. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="hardware-pwm-rettet-den-tag" class="slide level2">
<h2>Hardware-PWM rettet den Tag</h2>
<ul>
<li>Philosophie: konfigurieren und vergessen</li>
<li>GPT ist oft direkt mit dem Pin verdrahtet (Alternate Function / Pin-Mux)</li>
<li>CPU setzt Frequenz und Duty Cycle einmal — dann weiterrechnen oder schlafen</li>
<li>Hardware erzeugt das Rechteck autark und jitterarm</li>
</ul>
<aside class="notes">
<p>Hardware-PWM rettet den Tag knüpft an die bisherige Frage nach Signal und Überwachung an. Der Pfad ist Zähler, Vergleich, Ausgangsfunktion, Pin. Pin-Mux wählt die interne Funktion. Hardware-PWM nimmt die CPU aus der einzelnen Flanke, nicht aus Takt und Fehlerbehandlung. Im Sleep läuft der Timer nur weiter, wenn Takt und Ausgangsdomäne aktiv bleiben. Philosophie: konfigurieren und vergessen. GPT ist oft direkt mit dem Pin verdrahtet (Alternate Function / Pin-Mux). CPU setzt Frequenz und Duty Cycle einmal — dann weiterrechnen oder schlafen. Verständnischeck: Warum kann die CPU rechnen, während PWM läuft? Der Timer vergleicht in eigener Hardware. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="praxis-rgb-leds" class="slide level2">
<h2>Praxis: RGB-LEDs</h2>
<ul>
<li>RGB-LED: drei Dioden (Rot, Grün, Blau)</li>
<li>Je Farbe ein PWM-Kanal</li>
<li>Beispiel: R 100 %, G 50 %, B 0 % → wahrgenommenes Orange</li>
<li>Laborziel (geplant): Farbverläufe über Duty Cycles</li>
</ul>
<aside class="notes">
<p>Praxis: RGB-LEDs knüpft an die bisherige Frage nach Signal und Überwachung an. Drei LED-Chips brauchen drei Kanäle und Strombegrenzung. Common Cathode und Common Anode bestimmen den aktiven Pegel. Gleiche Duty-Werte sind nicht gleich viel wahrgenommenes Rot, Grün und Blau. Beliebige RGB-Farben werden nicht behauptet. RGB-LED: drei Dioden (Rot, Grün, Blau). Je Farbe ein PWM-Kanal. Beispiel: R 100 %, G 50 %, B 0 % → wahrgenommenes Orange. Verständnischeck: Warum nicht gleiche Helligkeit bei gleichem Duty? Kanäle und spektrale Empfindlichkeit unterscheiden sich. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="nichtlinearität-des-auges" class="slide level2">
<h2>Nichtlinearität des Auges</h2>
<ul>
<li>Helligkeitsempfindung folgt nicht linear dem Tastverhältnis</li>
<li>Lehrkennlinie: <span class="math inline">\(D = b^{2{,}2}\)</span>, keine universelle Gamma-Norm</li>
<li>Für <span class="math inline">\(N = 1000\)</span> sind die gerundeten CCR-Werte 0, 47, 218, 531, 1000</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/04_aktorik_sicherheit/rgb-gamma.png"></p>
<figcaption>RGB-Beschaltung und Potenzkennlinie sind Lehrannahmen, keine Farbkalibrierung.</figcaption>
</figure>
</div>
<aside class="notes">
<p>Nichtlinearität des Auges knüpft an die bisherige Frage nach Signal und Überwachung an. b ist die gewünschte Helligkeitsstufe, D das elektrische Tastverhältnis. Das Modell ist D gleich b hoch 2,2. Für N gleich 1000 ergeben gerundete CCR-Werte 0, 47, 218, 531 und 1000. Eine LUT speichert solche Werte. 50 Prozent gewünschte Helligkeit und 50 Prozent Duty sind verschiedene Eingaben. Die Prozentfunktion setzt zunächst elektrischen Duty. Helligkeitsempfindung folgt nicht linear dem Tastverhältnis. Lehrkennlinie: <span class="math inline">\(D = b^{2{,}2}\)</span>, keine universelle Gamma-Norm. Für <span class="math inline">\(N = 1000\)</span> sind die gerundeten CCR-Werte 0, 47, 218, 531, 1000. Verständnischeck: Welcher CCR gehört zu b gleich 0,5? 218, etwa 21,8 Prozent elektrischer Duty. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fragen-pwm-grundlagen" class="slide level2">
<h2>Fragen? — PWM-Grundlagen</h2>
<ul>
<li>Periode <span class="math inline">\(T\)</span> und Duty Cycle klar?</li>
<li>Warum ist Bit-Banging riskant für Stabilität und Timing?</li>
<li><span class="math inline">\(V_{\mathrm{eff}}\)</span> nachvollziehbar?</li>
</ul>
<aside class="notes">
<p>Fragen? — PWM-Grundlagen knüpft an die bisherige Frage nach Signal und Überwachung an. Bei T gleich 1 ms und 250 µs aktiv sind Frequenz 1 kHz und Duty 25 Prozent. Mittelwert 0,825 V, Effektivwert 1,65 V. Am ungefilterten Pin liegt keine konstante Zwischenpegelspannung. Aus 0,825 V folgt keine Motorleistung. Periode <span class="math inline">\(T\)</span> und Duty Cycle klar?. Warum ist Bit-Banging riskant für Stabilität und Timing?. <span class="math inline">\(V_{\mathrm{eff}}\)</span> nachvollziehbar?. Verständnischeck: Kann man aus 0,825 V die Motorleistung rechnen? Nein, Last und Stromverlauf fehlen. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="counter-trifft-compare-register" class="slide level2">
<h2>Counter trifft Compare-Register</h2>
<ul>
<li>Bekannt: <code>CNT</code> zählt, <code>ARR</code> begrenzt die Periode</li>
<li>Neu: Capture/Compare Register (<code>CCR</code>) — Schwelle für den Duty Cycle</li>
<li>Merksatz:
<ul>
<li><code>ARR</code> → Frequenz / Periode</li>
<li><code>CCR</code> → Duty Cycle</li>
</ul></li>
</ul>
<aside class="notes">
<p>Counter trifft Compare-Register knüpft an die bisherige Frage nach Signal und Überwachung an. Capture erfasst Zeitpunkte, Compare vergleicht mit einer Schwelle. Hier gilt Compare. f_PWM gleich f_cnt geteilt durch ARR plus 1, D_aktiv gleich CCR geteilt durch ARR plus 1, bei festem Takt und PSC. CCR von 250 auf 500 verdoppelt D von 25 auf 50 Prozent, die Frequenz bleibt. Preload kann die Wirkung verzögern. Bekannt: <code>CNT</code> zählt, <code>ARR</code> begrenzt die Periode. Neu: Capture/Compare Register (<code>CCR</code>) — Schwelle für den Duty Cycle. Merksatz:. Verständnischeck: Was ändert CCR von 250 auf 500? Nur das Tastverhältnis, nicht die Frequenz. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="der-komparator-im-timer" class="slide level2">
<h2>Der Komparator im Timer</h2>
<ul>
<li>Hardware vergleicht fortlaufend <code>CNT</code> und <code>CCR</code></li>
<li>Typische Logik (vereinfacht): solange <code>CNT &lt; CCR</code> → Pin HIGH, sonst LOW</li>
<li>Läuft automatisch — ohne Software-Latenz pro Takt</li>
</ul>
<aside class="notes">
<p>Der Komparator im Timer knüpft an die bisherige Frage nach Signal und Überwachung an. Bei CCR gleich 250 sind CNT 249 aktiv, 250 und 251 inaktiv, weil die Regel CNT kleiner CCR ist. Sofort heißt hier ohne Softwaretakt je Flanke, nicht null physikalische Verzögerung. Dunkler folgt nur bei passender Beschaltung. Hardware vergleicht fortlaufend <code>CNT</code> und <code>CCR</code>. Typische Logik (vereinfacht): solange <code>CNT &lt; CCR</code> → Pin HIGH, sonst LOW. Läuft automatisch — ohne Software-Latenz pro Takt. Verständnischeck: Ist der Ausgang bei CNT gleich CCR noch aktiv? Im Modell nein. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="edge-aligned-pwm" class="slide level2">
<h2>Edge-Aligned PWM</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/04_aktorik_sicherheit/edge-pwm.png"></p>
<figcaption>CNT 0 bis 999, CCR 250: 250 aktive und 750 inaktive Tickintervalle.</figcaption>
</figure>
</div>
<ul>
<li>Up-Counting (Sägezahn) + Vergleich mit CCR → Edge-Aligned PWM</li>
<li>Beispiel: <code>ARR = 999</code>, <code>CCR = 250</code> → exakt 25 % Duty Cycle (Periode <span class="math inline">\(0\ldots999\)</span> = 1000 Takte)</li>
<li>Pin HIGH von 0 bis unter CCR, danach LOW bis ARR, dann Reset</li>
</ul>
<aside class="notes">
<p>Edge-Aligned PWM knüpft an die bisherige Frage nach Signal und Überwachung an. Bei 1 MHz gilt CNT 0 von 0 bis 1 µs, CNT 249 von 249 bis 250 µs, CNT 999 von 999 bis 1000 µs. Aktiv sind 0 bis 250 µs, inaktiv 250 bis 1000 µs. CCR 0 ist immer inaktiv. CCR 1000 ist immer aktiv, wenn der Wert darstellbar ist. 250 geteilt durch 999 wäre falsch, weil null mitzählt. Up-Counting (Sägezahn) + Vergleich mit CCR → Edge-Aligned PWM. Beispiel: <code>ARR = 999</code>, <code>CCR = 250</code> → exakt 25 % Duty Cycle (Periode <span class="math inline">\(0\ldots999\)</span> = 1000 Takte). Pin HIGH von 0 bis unter CCR, danach LOW bis ARR, dann Reset. Verständnischeck: Warum 25 Prozent und nicht 250 geteilt durch 999? Weil N gleich 1000 ist. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="schritt-1-start-pin-high" class="slide level2">
<h2>Schritt 1: Start — Pin HIGH</h2>
<ul>
<li>Start: <code>CNT = 0</code></li>
<li>Vergleich: <span class="math inline">\(0 &lt; 250\)</span> (<code>CNT &lt; CCR</code>) → ja → Pin HIGH (<span class="math inline">\(3{,}3\,\mathrm{V}\)</span>)</li>
<li>Timer zählt weiter; die CPU kann andere Aufgaben erledigen</li>
<li>LED leuchtet in der HIGH-Phase</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>CNT</th>
<th>CCR</th>
<th>Pin</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0 … 249</td>
<td>250</td>
<td>HIGH</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\ge\)</span> 250</td>
<td>250</td>
<td>LOW (nächster Schritt)</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Schritt 1: Start — Pin HIGH knüpft an die bisherige Frage nach Signal und Überwachung an. Der Start CNT gleich 0 ist aktiv, weil 0 kleiner 250. Die Intervalle 0 bis 249 sind aktiv. 3,3 V ist der ideale Pegel. Bei CCR gleich 0 ist 0 kleiner 0 falsch, der Start ist inaktiv. Start immer HIGH gilt daher nicht. Start: <code>CNT = 0</code>. Vergleich: <span class="math inline">\(0 &lt; 250\)</span> (<code>CNT &lt; CCR</code>) → ja → Pin HIGH (<span class="math inline">\(3{,}3\,\mathrm{V}\)</span>). Timer zählt weiter; die CPU kann andere Aufgaben erledigen. Verständnischeck: Was liefert CCR gleich 0 am Start? Keine aktive Phase. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="schritt-2-counter-erreicht-ccr-match" class="slide level2">
<h2>Schritt 2: Counter erreicht CCR (Match)</h2>
<ul>
<li>Counter erreicht exakt <code>CCR = 250</code></li>
<li>Vergleich: <span class="math inline">\(250 &lt; 250\)</span>? → nein → Compare Match</li>
<li>Ab <code>CNT = CCR</code> ist der Steuerpin im Active-High-Modell inaktiv</li>
<li>Induktive Lasten können in LOW weiter Strom führen</li>
<li>Ein ungepufferter CCR-Wechsel mitten in der Periode kann erneut aktivieren</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Phase</th>
<th>Bedingung</th>
<th>Pin</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>aktiv</td>
<td><code>CNT &lt; CCR</code></td>
<td>HIGH</td>
</tr>
<tr class="even">
<td>Match</td>
<td><code>CNT = CCR</code></td>
<td>LOW, Beginn der inaktiven Phase</td>
</tr>
<tr class="odd">
<td>danach</td>
<td><code>CNT &gt; CCR</code> bis ARR</td>
<td>LOW</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/04_aktorik_sicherheit/preload.png"></p>
<figcaption>Ungepuffert kann CCR = 750 bei CNT = 500 erneut aktivieren. Mit Preload gilt der neue Wert erst ab dem Update.</figcaption>
</figure>
</div>
<aside class="notes">
<p>Schritt 2: Counter erreicht CCR (Match) knüpft an die bisherige Frage nach Signal und Überwachung an. Match ist die Gleichheit CNT gleich CCR. CNT größer oder gleich CCR beschreibt die anschließende inaktive Phase. Ab 250 µs bleibt der Pin bis 1000 µs inaktiv. Der Steuerpin ist inaktiv, die Last kann weiter Strom führen. Ohne Preload wird bei CNT gleich 500 und neuem CCR 750 der Vergleich 500 kleiner 750 wieder wahr. Mit Preload bleibt die erste Periode 25 Prozent, die nächste wird 75 Prozent. Registernamen sind herstellerspezifisch. Counter erreicht exakt <code>CCR = 250</code>. Vergleich: <span class="math inline">\(250 &lt; 250\)</span>? → nein → Compare Match. Ab <code>CNT = CCR</code> ist der Steuerpin im Active-High-Modell inaktiv. Verständnischeck: Warum wird ungepuffert bei CNT 500 wieder aktiv? Weil 500 kleiner 750 nun gilt. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="nach-dem-arr-intervall-neustart" class="slide level2">
<h2>Nach dem ARR-Intervall: Neustart</h2>
<ul>
<li><code>CNT = 999</code> dauert von 999 bis 1000 µs</li>
<li>Erst der nächste Tick setzt <code>CNT = 0</code> und startet die neue Periode</li>
<li>Vergleich erneut: <span class="math inline">\(0 &lt; 250\)</span> → Pin wieder HIGH</li>
<li>Im Kernmodell ist das 1 kHz, nicht ungeprüft 10 kHz</li>
</ul>
<aside class="notes">
<p>Nach dem ARR-Intervall: Neustart knüpft an die bisherige Frage nach Signal und Überwachung an. CNT gleich 998 liegt in 998 bis 999 µs, CNT gleich 999 in 999 bis 1000 µs, CNT gleich 0 erst in 1000 bis 1001 µs. Der Ausgang wird bei 1000 µs wieder aktiv. Das Beispiel bleibt 1 kHz. Ein Sleep muss den Timer-Takt behalten. Flackerfrei ist keine Wahrnehmungsgarantie. <code>CNT = 999</code> dauert von 999 bis 1000 µs. Erst der nächste Tick setzt <code>CNT = 0</code> und startet die neue Periode. Vergleich erneut: <span class="math inline">\(0 &lt; 250\)</span> → Pin wieder HIGH. Verständnischeck: Wann beginnt die zweite Periode? Bei t gleich 1000 µs. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-polarität-polarity" class="slide level2">
<h2>Die Polarität (Polarity)</h2>
<ul>
<li>Bisher Active-High: <code>CNT &lt; CCR</code> → Pin HIGH, <span class="math inline">\(D_{\mathrm{HIGH}} = D_{\mathrm{aktiv}}\)</span></li>
<li>Active-Low: dieselbe aktive Zeit, aber LOW. Bei CCR = 250 ist HIGH dann 75 Prozent</li>
<li>Größeres CCR verlängert die aktive Phase, nicht automatisch die HIGH-Zeit</li>
</ul>
<aside class="notes">
<p>Die Polarität (Polarity) knüpft an die bisherige Frage nach Signal und Überwachung an. Bei CCR 250 und N 1000 ist D_aktiv in beiden Polaritäten 25 Prozent. Active-High hat 25 Prozent HIGH, Active-Low 25 Prozent LOW und damit 75 Prozent HIGH. Größeres CCR verlängert die aktive Phase auch bei Active-Low. Bei CNT gleich 100 und Active-Low ist der Pegel LOW. Bisher Active-High: <code>CNT &lt; CCR</code> → Pin HIGH, <span class="math inline">\(D_{\mathrm{HIGH}} = D_{\mathrm{aktiv}}\)</span>. Active-Low: dieselbe aktive Zeit, aber LOW. Bei CCR = 250 ist HIGH dann 75 Prozent. Größeres CCR verlängert die aktive Phase, nicht automatisch die HIGH-Zeit. Verständnischeck: Welcher Pegel ist bei CNT 100 im Active-Low-Fall? LOW, der aktive Anteil bleibt CCR geteilt durch N. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="mehrere-kanäle-an-einem-timer" class="slide level2">
<h2>Mehrere Kanäle an einem Timer</h2>
<ul>
<li>Ein Timer: ein Counter und ein ARR → gemeinsame Frequenz</li>
<li>Oft 4 Compare-Register (CCR1–CCR4) → bis zu 4 Pins</li>
<li>Unterschiedliche Duty Cycles möglich, gleiche Grundfrequenz</li>
<li>Ideal für RGB: ein Rhythmus, drei Helligkeiten</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="4" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%
flowchart LR
  CNT[Counter und ARR] --&gt; C1[CCR1]
  CNT --&gt; C2[CCR2]
  CNT --&gt; C3[CCR3]
  C1 --&gt; R[LED Rot]
  C2 --&gt; G[LED Grün]
  C3 --&gt; B[LED Blau]
  style CNT fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Mehrere Kanäle an einem Timer knüpft an die bisherige Frage nach Signal und Überwachung an. Ein gemeinsamer Zähler kann mehrere CCR und Pins haben. Vier Kanäle sind keine allgemeine Garantie. CCR 100, 500 und 900 sind 10, 50 und 90 Prozent bei N 1000. Dieselbe ARR-Einstellung kann nicht zugleich 1 kHz und 50 Hz erzeugen. Drei Schreibzugriffe, die ein Update überstreichen, können trotz Preload einen gemischten Kanalsatz erzeugen. Ein Timer: ein Counter und ein ARR → gemeinsame Frequenz. Oft 4 Compare-Register (CCR1–CCR4) → bis zu 4 Pins. Unterschiedliche Duty Cycles möglich, gleiche Grundfrequenz. Verständnischeck: Geht 1-kHz-LED und 50-Hz-Servo am selben ARR? Nein. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="center-aligned-pwm" class="slide level2">
<h2>Center-Aligned PWM</h2>
<ul>
<li>Dreieckszähler: Komparator schaltet beim Hoch- und Herunterzählen</li>
<li>PWM-Pulse symmetrisch zur Periodenmitte</li>
<li>Nutzen: Wechselrichter / Motorantrieb — oft weniger störende Harmonische</li>
<li>Für LEDs reicht meist Edge-Aligned</li>
</ul>
<aside class="notes">
<p>Center-Aligned PWM knüpft an die bisherige Frage nach Signal und Überwachung an. Symmetrische Pulse brauchen die Vergleichsregel in beiden Richtungen. Das Dreieck mit acht Intervallen ist das Modell von Folie 21. EMI heißt elektromagnetische Störung, falls genannt. Geringere Verluste sind keine Garantie. Ein Dreieckbild allein liefert keine exakten Prozente. Dreieckszähler: Komparator schaltet beim Hoch- und Herunterzählen. PWM-Pulse symmetrisch zur Periodenmitte. Nutzen: Wechselrichter / Motorantrieb — oft weniger störende Harmonische. Verständnischeck: Warum reicht das Dreieck nicht für Prozente? Endpunkte, Vergleich und Polarität fehlen. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="glättung-von-pwm-signalen" class="slide level2">
<h2>Glättung von PWM-Signalen</h2>
<ul>
<li>Manche Lasten brauchen echte Gleichspannung (z. B. Audio)</li>
<li>RC-Glied (Widerstand + Kondensator) als Tiefpass am PWM-Pin</li>
<li>Hohe Frequenzanteile (Kanten) werden gedämpft → Mittelwert bleibt</li>
<li>Ergebnis: steuerbare Analogspannung — PWM als einfacher DAC</li>
</ul>
<aside class="notes">
<p>Glättung von PWM-Signalen knüpft an die bisherige Frage nach Signal und Überwachung an. RC ist hier Widerstand und Kondensator, ein Tiefpass. Audio ist ein veränderliches Nutzsignal, keine Gleichspannung. R gleich 10 Kiloohm und C gleich 1 Mikrofarad ergeben Tau gleich 10 ms und eine Grenzfrequenz von etwa 15,9 Hz im unbelasteten Modell. Bei 1 kHz und 50 Prozent nähert sich der Mittelwert 1,65 V. Größeres Tau glättet stärker und reagiert langsamer. Das ist kein geprüftes Schaltungsdesign. Manche Lasten brauchen echte Gleichspannung (z. B. Audio). RC-Glied (Widerstand + Kondensator) als Tiefpass am PWM-Pin. Hohe Frequenzanteile (Kanten) werden gedämpft → Mittelwert bleibt. Verständnischeck: Warum folgt der neue Mittelwert nicht sofort? Der Kondensator lädt mit endlicher Zeitkonstante. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="anwendung-servomotoren" class="slide level2">
<h2>Anwendung: Servomotoren</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/04_aktorik_sicherheit/applications.png"></p>
<figcaption>RC-Glied, Servo mit 20 ms und H-Bruecke sind drei verschiedene Anwendungen.</figcaption>
</figure>
</div>
<ul>
<li>Hier ist PWM oft Datenprotokoll, nicht reine Leistungsübertragung</li>
<li>Typisch: 50 Hz (Periode 20 ms)</li>
<li>Pulsbreite steuert den Winkel:
<ul>
<li><span class="math inline">\(1{,}0\,\mathrm{ms}\)</span> → eine Endlage</li>
<li><span class="math inline">\(1{,}5\,\mathrm{ms}\)</span> → Mitte</li>
<li><span class="math inline">\(2{,}0\,\mathrm{ms}\)</span> → andere Endlage</li>
</ul></li>
<li>Motorleistung kommt über separate Versorgung</li>
</ul>
<aside class="notes">
<p>Anwendung: Servomotoren knüpft an die bisherige Frage nach Signal und Überwachung an. RC-Servo heißt Radio-Control-Servo, nicht Widerstand-Kondensator. 20 ms Rahmen und 1, 1,5 und 2 ms Pulse sind häufige Beispiele, keine Winkelgarantie. 1,5 geteilt durch 20 ist 7,5 Prozent des Steuersignals, nicht der Motorleistung. Die Versorgung speist die interne Stufe separat. Hier ist PWM oft Datenprotokoll, nicht reine Leistungsübertragung. Typisch: 50 Hz (Periode 20 ms). Pulsbreite steuert den Winkel:. Verständnischeck: Wie groß ist D bei 1,5 ms in 20 ms? 7,5 Prozent, im Beispiel der mittlere Positionsbefehl. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="anwendung-dc-motoren-und-h-brücke" class="slide level2">
<h2>Anwendung: DC-Motoren und H-Brücke</h2>
<ul>
<li>Motor nie direkt an GPIO (Strombegrenzung, Chip-Schutz)</li>
<li>Motortreiber / H-Brücke dazwischen</li>
<li>SoC: schwaches PWM-Kommando (z. B. <span class="math inline">\(3{,}3\,\mathrm{V}\)</span>)</li>
<li>H-Brücke: schaltet externe Versorgung (z. B. 12 V) im PWM-Takt</li>
</ul>
<aside class="notes">
<p>Anwendung: DC-Motoren und H-Brücke knüpft an die bisherige Frage nach Signal und Überwachung an. DC heißt Gleichstrom. 3,3 V ist das Logiksignal, 12 V eine beispielhafte Motorversorgung. Eine H-Brücke kann die Polarität ändern. PWM, Richtung und Enable sind nur dann Pins, wenn das Modell sie definiert. Gleichzeitiges Durchschalten einer Brücke ist unzulässig. In LOW kann Induktivität weiter Strom treiben. Motor nie direkt an GPIO (Strombegrenzung, Chip-Schutz). Motortreiber / H-Brücke dazwischen. SoC: schwaches PWM-Kommando (z. B. <span class="math inline">\(3{,}3\,\mathrm{V}\)</span>). Verständnischeck: Warum fließt in LOW noch Strom? Die Wicklung speichert Energie, der Treiber stellt einen Pfad bereit. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="zusammenfassung-hardware-pwm" class="slide level2">
<h2>Zusammenfassung: Hardware-PWM</h2>
<ul>
<li>GPT erzeugt Signale autark (kein Bit-Banging)</li>
<li>Frequenz: Prescaler (PSC) und Auto-Reload (ARR)</li>
<li>Duty Cycle: Compare-Register (CCR)</li>
<li>Active-High (typisch): <code>CNT &lt; CCR</code> → Pin HIGH</li>
<li>LEDs direkt (strombegrenzt); Motoren über Treiber/H-Brücke — jitterarm</li>
</ul>
<aside class="notes">
<p>Zusammenfassung: Hardware-PWM knüpft an die bisherige Frage nach Signal und Überwachung an. Das Kernmodell: 100 MHz, PSC 99, ARR 999, CCR 250 ergeben 1 kHz und 25 Prozent aktive Zeit. Der Pin muss gemultiplext sein. LEDs brauchen Strombegrenzung, Motoren einen Treiber. Nach einem Hänger kann das letzte PWM-Signal bleiben. GPT erzeugt Signale autark (kein Bit-Banging). Frequenz: Prescaler (PSC) und Auto-Reload (ARR). Duty Cycle: Compare-Register (CCR). Verständnischeck: Was bleibt bei einem Hänger aktiv? Das letzte PWM-Signal, solange Takt und Timer laufen. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fragen-hardware-pwm" class="slide level2">
<h2>Fragen? — Hardware-PWM</h2>
<ul>
<li>Zusammenspiel von Counter, ARR und CCR?</li>
<li>Warum gleiche Frequenz, aber unterschiedliche Duty Cycles auf einem Timer?</li>
<li>PWM zum Dimmen vs.&nbsp;PWM als Servo-Protokoll?</li>
</ul>
<aside class="notes">
<p>Fragen? — Hardware-PWM knüpft an die bisherige Frage nach Signal und Überwachung an. Der Counter liefert das Raster, ARR beendet es nach N Intervallen, CCR setzt die Schwelle. Mehrere Kanäle teilen die Grundfrequenz. Ein direktes CCR-Schreiben mitten in der Periode kann Pulse zerschneiden oder verdoppeln. Preload verschiebt die Wirkung an das Update. Zusammenspiel von Counter, ARR und CCR?. Warum gleiche Frequenz, aber unterschiedliche Duty Cycles auf einem Timer?. PWM zum Dimmen vs.&nbsp;PWM als Servo-Protokoll?. Verständnischeck: Warum ist direktes Schreiben heikel? Der neue Vergleich kann in derselben Periode zusätzlich schalten. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="szenario-system-ohne-reset-zugang" class="slide level2">
<h2>Szenario: System ohne Reset-Zugang</h2>
<ul>
<li>Beispiel: Gerät ohne physischen Zugang (Satellit, Implantat, Feldgerät)</li>
<li>Software hängt in einer Endlosschleife (Freeze)</li>
<li>Kommunikation und Steuerung fallen aus</li>
<li>Niemand kann den Reset-Knopf drücken</li>
<li>Folge: Mission / Funktion dauerhaft verloren — ohne Selbstheilung</li>
</ul>
<aside class="notes">
<p>Szenario: System ohne Reset-Zugang knüpft an die bisherige Frage nach Signal und Überwachung an. Das Beispiel ist ein entferntes LED-Feldgerät, kein Implantat. Ein Hänger blockiert die Anwendung, autonome Peripherie kann weiterlaufen. Ein Reset beseitigt einen temporären Zustand, nicht zwingend eine bleibende Ursache. Ein kurzgeschlossener Sensor kann nach dem Boot erneut hängen lassen. Beispiel: Gerät ohne physischen Zugang (Satellit, Implantat, Feldgerät). Software hängt in einer Endlosschleife (Freeze). Kommunikation und Steuerung fallen aus. Verständnischeck: Warum hilft Reset bei einem dauerhaften Sensorfehler nicht immer? Die Ursache bleibt. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="warum-stürzt-software-ab" class="slide level2">
<h2>Warum stürzt Software ab?</h2>
<ul>
<li>Endlosschleifen (z. B. Timeout vergessen: <code>while (sensor_busy);</code>)</li>
<li>Deadlocks (Multicore, später Block 9)</li>
<li>Stack Overflow (z. B. zu tiefes Nesting)</li>
<li>Soft-Errors: Bit-Flips (z. B. Strahlung) → Program Counter / Zustand zerstört</li>
</ul>
<aside class="notes">
<p>Warum stürzt Software ab knüpft an die bisherige Frage nach Signal und Überwachung an. Eine Endlosschleife, unbegrenztes Warten, wechselseitige Locks, erschöpfter Stack und ein Bitfehler sind verschiedene Fälle. Deadlock ist nicht jede while-1-Schleife. Tiefe Aufrufe verbrauchen Stack, verschachtelte ifs nicht automatisch. Der Watchdog sieht ausbleibenden Feed, nicht den falschen Sensorwert. Endlosschleifen (z. B. Timeout vergessen: <code>while (sensor_busy);</code>). Deadlocks (Multicore, später Block 9). Stack Overflow (z. B. zu tiefes Nesting). Verständnischeck: Erkennt der Watchdog einen falschen Wert bei weiterem Feed? Nicht allein durch den Timeout. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="leitfrage-2-wer-resettet-die-tote-cpu" class="slide level2">
<h2>Leitfrage 2: Wer resettet die tote CPU?</h2>
<ul>
<li>OS/C-Code abgestürzt — CPU reagiert nicht mehr</li>
<li>Wie resettet man, wenn das „Gehirn“ den Reset nicht mehr auslösen kann?</li>
<li>Antwort: Software nicht vertrauen — unabhängige, einfache Hardware</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="3.6" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%
flowchart TD
  CPU[CPU abgestürzt] --&gt;|keine Reaktion| S[System eingefroren]
  W{Wer drückt Reset?} -.-&gt; S
  style W fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Leitfrage 2: Wer resettet die tote CPU knüpft an die bisherige Frage nach Signal und Überwachung an. Tot ist ein Bild: die CPU kann weiterlaufen, während die relevante Arbeit fehlt. Der Watchdog kann im SoC sitzen. Der Pfad ist Ablauf des Zählers zur Resetlogik ohne die hängende Schleife. Eine eigene Taktquelle ist ein zusätzlicher Entwurf, keine Folge der räumlichen Trennung. OS/C-Code abgestürzt — CPU reagiert nicht mehr. Wie resettet man, wenn das „Gehirn“ den Reset nicht mehr auslösen kann?. Antwort: Software nicht vertrauen — unabhängige, einfache Hardware. Verständnischeck: Warum genügt ein Reset-Aufruf am Schleifenende nicht? Der Hänger erreicht ihn nicht. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="der-watchdog-timer-wdt" class="slide level2">
<h2>Der Watchdog Timer (WDT)</h2>
<ul>
<li>WDT: einfaches Hardware-Modul, getrennt von der ALU</li>
<li>Ultimatum im Basismodell: Reset 2 s nach dem letzten gültigen Feed</li>
<li>Gesunde Software erneuert die Frist nach geprüftem Fortschritt</li>
<li>Bei Ausfall: Timeout → Hardware zieht die Reset-Leitung</li>
</ul>
<aside class="notes">
<p>Der Watchdog Timer (WDT) knüpft an die bisherige Frage nach Signal und Überwachung an. ALU ist das Rechenwerk. Getrennt von der ALU heißt noch keine eigene Takt- oder Stromversorgung. Das Basismodell nutzt 2 s, nicht 5 s. Ein Feed erneuert die Frist und prüft keine Ergebnisse. Der Hund ist nur die Analogie nach dieser Beschreibung. WDT: einfaches Hardware-Modul, getrennt von der ALU. Ultimatum im Basismodell: Reset 2 s nach dem letzten gültigen Feed. Gesunde Software erneuert die Frist nach geprüftem Fortschritt. Verständnischeck: Was schließt ein gültiger Feed? Nur, dass der Feed-Vorgang stattfand. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="architektur-des-wdt" class="slide level2">
<h2>Architektur des WDT</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/04_aktorik_sicherheit/watchdog.png"></p>
<figcaption>Feeds bei 0, 0,5 und 1 s, idealer Reset bei 3 s. 0xAA55 ist fiktiv.</figcaption>
</figure>
</div>
<ul>
<li>Oft Down-Counter</li>
<li>Beim Start: Timeout nominal 2 s laden</li>
<li>Feeds bei 0, 0,5 und 1,0 s starten die Frist neu; idealer Reset bei 3,0 s</li>
<li>Abschaltbarkeit ist plattformabhängig, keine allgemeine Garantie</li>
</ul>
<aside class="notes">
<p>Architektur des WDT knüpft an die bisherige Frage nach Signal und Überwachung an. Feeds bei 0, 0,5 und 1 s starten je 2 s neu. Nach dem Feed bei 1 s endet die Frist bei 3 s. Ein Hänger bei 1,2 s wartet im Idealmodell 1,8 s. 0xAA55 ist ein Lehrschlüssel. Ein Down-Counter ist eine mögliche Umsetzung, keine notwendige Innenschaltung. Nicht jeder WDT lässt sich nach dem Scharfmachen abschalten. Oft Down-Counter. Beim Start: Timeout nominal 2 s laden. Feeds bei 0, 0,5 und 1,0 s starten die Frist neu; idealer Reset bei 3,0 s. Verständnischeck: Warum nicht schon bei 2 s seit Start? Der Feed bei 1 s hat die Frist neu gestartet. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="der-biss-des-hundes" class="slide level2">
<h2>Der Biss des Hundes</h2>
<ul>
<li>Counter erreicht 0</li>
<li>Kein „freundlicher“ Interrupt (CPU könnte taub sein)</li>
<li>Direkter Eingriff in Reset-/Power-Management</li>
<li>Chip wie nach Hardware-Reset: CPU, Zustand, Peripherie neu</li>
<li>Boot ab Reset-Vektor / Flash-Startadresse</li>
</ul>
<aside class="notes">
<p>Der Biss des Hundes knüpft an die bisherige Frage nach Signal und Überwachung an. Manche Watchdogs warnen vor oder wählen die Ablaufaktion. Dieses Modell erzwingt einen Reset ohne die hängende ISR. Ein Watchdog-Reset ist nicht zwingend ein Power-On-Reset. RAM, Peripherie und Flags können verschiedene Domänen haben. Der Bootpfad ist plattformspezifisch. Dieselbe Ursache kann erneut hängen lassen. Counter erreicht 0. Kein „freundlicher“ Interrupt (CPU könnte taub sein). Direkter Eingriff in Reset-/Power-Management. Verständnischeck: Kann die Firmware denselben Fehler erneut treffen? Ja. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="den-hund-streicheln-feed" class="slide level2">
<h2>Den Hund streicheln (Feed)</h2>
<ul>
<li>Gesunde Software muss den WDT periodisch zurücksetzen</li>
<li>„Petting / kicking the dog“: magischen Wert ins Feed-Register schreiben</li>
<li>Counter springt auf den Startwert zurück</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb3-1"><a aria-label="1"></a><span class="dt">void</span> wdt_feed<span class="op">(</span><span class="dt">void</span><span class="op">)</span> <span class="op">{</span></span>
<span id="cb3-2"><a aria-label="2"></a>    <span class="op">*(</span><span class="dt">volatile</span> <span class="dt">uint32_t</span> <span class="op">*)</span>WDT_FEED_REG <span class="op">=</span> <span class="bn">0xAA55</span><span class="op">;</span></span>
<span id="cb3-3"><a aria-label="3"></a><span class="op">}</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Den Hund streicheln (Feed) knüpft an die bisherige Frage nach Signal und Überwachung an. Der Zeigerzugriff schreibt 32 Bit an eine fiktive Adresse. volatile macht den Zugriff im C-Modell sichtbar, ersetzt aber Breite, Sequenz und Ordnung nicht. Manche Bausteine brauchen mehrere Schlüssel. Der Aufruf erneuert nur die Frist. Gesunde Software muss den WDT periodisch zurücksetzen. „Petting / kicking the dog“: magischen Wert ins Feed-Register schreiben. Counter springt auf den Startwert zurück. Verständnischeck: Warum nicht 0xAA55 auf ein anderes Board? Adresse und Sequenz stehen im Datenblatt. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="wo-streichelt-man-den-hund" class="slide level2">
<h2>Wo streichelt man den Hund?</h2>
<ul>
<li>Falsch: Füttern nur in der SysTick-ISR
<ul>
<li><code>main</code> kann tot sein, Interrupts laufen weiter → kein Reset</li>
</ul></li>
<li>Falsch: bedingungsloses Füttern in einer weiterlaufenden Tick-ISR</li>
<li>Ein Aufruf am Ende von <code>main</code> reicht nicht, wenn die Arbeit selbst nicht geprüft wurde</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb4-1"><a aria-label="1"></a><span class="co">/* Lehrcode. Timeout 2 s. Feed nur nach frischem Fortschritt. */</span></span>
<span id="cb4-2"><a aria-label="2"></a><span class="cf">while</span> <span class="op">(</span><span class="dv">1</span><span class="op">)</span> <span class="op">{</span></span>
<span id="cb4-3"><a aria-label="3"></a>    <span class="dt">bool</span> fresh <span class="op">=</span> work_finished_and_plausible<span class="op">();</span></span>
<span id="cb4-4"><a aria-label="4"></a>    <span class="cf">if</span> <span class="op">(</span>service_due <span class="op">&amp;&amp;</span> fresh<span class="op">)</span></span>
<span id="cb4-5"><a aria-label="5"></a>        wdt_feed<span class="op">();</span></span>
<span id="cb4-6"><a aria-label="6"></a><span class="op">}</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Wo streichelt man den Hund knüpft an die bisherige Frage nach Signal und Überwachung an. Ein Tick-Feed verdeckt einen Hänger der Hauptschleife. Rückkehr von lese_sensoren und berechne_werte beweist keine frischen, plausiblen Daten. Feed nur, wenn die vereinbarte Arbeit neu und rechtzeitig fertig ist. Alte Flags gelten nicht für den nächsten Abschnitt. 0,5 s Service ist nicht die 10-ms-Fading-Periode. Falsch: Füttern nur in der SysTick-ISR. <code>main</code> kann tot sein, Interrupts laufen weiter → kein Reset. Falsch: bedingungsloses Füttern in einer weiterlaufenden Tick-ISR. Verständnischeck: Warum reicht die Rückkehr der beiden Funktionen nicht? Sie können veraltete oder falsche Ergebnisse liefern. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="unabhängige-taktquelle-lsi" class="slide level2">
<h2>Unabhängige Taktquelle (LSI)</h2>
<ul>
<li>Was, wenn der Hauptquarz ausfällt?</li>
<li>Gemeinsamer Takt: CPU und WDT würden gemeinsam einfrieren</li>
<li>Für den Ausfall des Haupttakts braucht die Überwachung eine eigene Zeitquelle</li>
<li>LSI und etwa 32 kHz sind ein Herstellerbeispiel, keine Norm jedes Watchdogs</li>
</ul>
<aside class="notes">
<p>Unabhängige Taktquelle (LSI) knüpft an die bisherige Frage nach Signal und Überwachung an. LSI, Low-Speed Internal, ist ein Herstellername, keine Norm. Für einen Ausfall des Haupttakts braucht der WDT eine passende eigene Zeitquelle. 20 Prozent höhere Taktfrequenz verkürzt 2 s auf 2 geteilt durch 1,2, etwa 1,667 s. 20 Prozent weniger dehnt auf 2,5 s. Das sind keine symmetrischen plus minus 20 Prozent der Zeit. Ein gemeinsamer Spannungsausfall bleibt unbeobachtet. Verständnischeck: Warum wird der Timeout kürzer? Derselbe Zählwert wird schneller erreicht. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="window-watchdog-wwdg" class="slide level2">
<h2>Window Watchdog (WWDG)</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/04_aktorik_sicherheit/window.png"></p>
<figcaption>Weiterfuettern aus dem Tick verdeckt einen Haenger. Fenster und Normal-Feed sind verschieden.</figcaption>
</figure>
</div>
<ul>
<li>Normaler WDT: erkennt zu langsames Füttern (Timeout)</li>
<li>Problem: fehlerhafter Code füttert zu oft / zu früh</li>
<li>Window Watchdog: Füttern nur in einem Zeitfenster erlaubt</li>
<li>Zu früh oder zu spät → Reset</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Zeitpunkt</th>
<th>Bewertung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>vor Fenster</td>
<td>Reset (zu früh)</td>
</tr>
<tr class="even">
<td>im Fenster</td>
<td>OK</td>
</tr>
<tr class="odd">
<td>nach Timeout</td>
<td>Reset (zu spät)</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Window Watchdog (WWDG) knüpft an die bisherige Frage nach Signal und Überwachung an. WWDG ist ein herstellerspezifischer Name für einen Window-Watchdog. Im Modell gilt 0,5 s kleiner Delta t kleiner 2 s seit dem letzten gültigen Feed. Ein Feed alle 10 ms ist hier zu früh. Das Fenster prüft ein Zeitmuster, keine Ergebnisrichtigkeit. Eigene Taktquelle und Fenster sind unabhängige Merkmale. Normaler WDT: erkennt zu langsames Füttern (Timeout). Problem: fehlerhafter Code füttert zu oft / zu früh. Window Watchdog: Füttern nur in einem Zeitfenster erlaubt. Verständnischeck: Warum passt der 10-ms-Fade-Feed nicht ins Fenster? Er kommt vor den erlaubten 0,5 s. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="zusammenfassung-watchdog" class="slide level2">
<h2>Zusammenfassung Watchdog</h2>
<ul>
<li>WDT: Netz bei Freeze, Deadlocks, entgleistem Ablauf</li>
<li>Autarker Down-Counter → harter System-Reset bei 0</li>
<li>Software setzt periodisch zurück (Feed)</li>
<li>Feed in der Main-Loop, nicht in der Timer-ISR</li>
<li>Window Watchdog: auch zu schnelles Abarbeiten erkennen</li>
</ul>
<aside class="notes">
<p>Zusammenfassung Watchdog knüpft an die bisherige Frage nach Signal und Überwachung an. Das Basismodell ist Zeitüberwachung mit Reset, optional eigener Takt und optionalem Fenster. Feed hängt an frischem Fortschritt. Ein zeitlich korrektes Fenster beweist keine inhaltliche Richtigkeit. Der Aktor kann nach dem CPU-Reset noch aktiv sein, bis ein eigener Abschaltpfad wirkt. WDT: Netz bei Freeze, Deadlocks, entgleistem Ablauf. Autarker Down-Counter → harter System-Reset bei 0. Software setzt periodisch zurück (Feed). Verständnischeck: Können Reset und weiter laufender Aktor zugleich gelten? Ja, bis zur separaten Abschaltwirkung. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fragen-watchdog" class="slide level2">
<h2>Fragen? — Watchdog</h2>
<ul>
<li>Warum eigener Takt (nicht CPU-Takt)?</li>
<li>Warum ist Feed in der Timer-ISR ein Designfehler?</li>
<li>Welches Problem löst der Window Watchdog zusätzlich?</li>
</ul>
<aside class="notes">
<p>Fragen? — Watchdog knüpft an die bisherige Frage nach Signal und Überwachung an. Eine eigene Zeitquelle hilft beim angenommenen Haupttaktausfall. Feed aus dem Tick kann die Hauptschleife verdecken. Das Fenster erkennt zu frühes Füttern, nicht falsche Ergebnisse. Renode braucht passende Timer-, GPIO- und Watchdog-Modelle. Ein Lauf liegt nicht vor. Warum eigener Takt (nicht CPU-Takt)?. Warum ist Feed in der Timer-ISR ein Designfehler?. Welches Problem löst der Window Watchdog zusätzlich?. Verständnischeck: Ist Feed aus einer ISR immer falsch? Nein, falsch ist bedingungsloses Füttern ohne Fortschrittsvertrag. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ausblick-labor-smarte-lampe" class="slide level2">
<h2>Ausblick Labor: smarte Lampe</h2>
<p>Geplantes Szenario:</p>
<ul>
<li>Timer als PWM-Generator; virtuelle RGB-LEDs in Renode</li>
<li>Fading in der Main-Schleife</li>
<li>Watchdog aktivieren</li>
<li>Virtueller Taster → künstliche <code>while (1);</code> (Freeze provozieren)</li>
</ul>
<aside class="notes">
<p>Ausblick Labor: smarte Lampe knüpft an die bisherige Frage nach Signal und Überwachung an. Das Labor ist ein späterer Ausblick. Virtuelle LEDs belegen weder Flanken noch Jitter. Ohne Firmware lassen sich Registerarithmetik, 10-ms-Plan, Feed-Zeitlinie und Resetgrenzen nachrechnen. Während des Hängers kann PWM weiterlaufen, der nominale Reset folgt der 2-s-Frist. Timer als PWM-Generator; virtuelle RGB-LEDs in Renode. Fading in der Main-Schleife. Watchdog aktivieren. Verständnischeck: Was ist ohne Ausführung prüfbar? Die Modellrechnung von PWM, Fading und Watchdog-Zeit. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="mmio-register-für-den-timer" class="slide level2">
<h2>MMIO-Register für den Timer</h2>
<p>Beispielhafte Adressen (fiktiv — immer Datenblatt prüfen):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb5-1"><a aria-label="1"></a><span class="pp">#define TIMER_BASE </span><span class="bn">0x40000000</span></span>
<span id="cb5-2"><a aria-label="2"></a><span class="pp">#define TIMER_PSC  </span><span class="op">(*(</span><span class="dt">volatile</span><span class="pp"> </span><span class="dt">uint32_t</span><span class="pp"> </span><span class="op">*)(</span><span class="pp">TIMER_BASE </span><span class="op">+</span><span class="pp"> </span><span class="bn">0x00</span><span class="op">))</span></span>
<span id="cb5-3"><a aria-label="3"></a><span class="pp">#define TIMER_ARR  </span><span class="op">(*(</span><span class="dt">volatile</span><span class="pp"> </span><span class="dt">uint32_t</span><span class="pp"> </span><span class="op">*)(</span><span class="pp">TIMER_BASE </span><span class="op">+</span><span class="pp"> </span><span class="bn">0x04</span><span class="op">))</span></span>
<span id="cb5-4"><a aria-label="4"></a><span class="pp">#define TIMER_CCR1 </span><span class="op">(*(</span><span class="dt">volatile</span><span class="pp"> </span><span class="dt">uint32_t</span><span class="pp"> </span><span class="op">*)(</span><span class="pp">TIMER_BASE </span><span class="op">+</span><span class="pp"> </span><span class="bn">0x0C</span><span class="op">))</span></span>
<span id="cb5-5"><a aria-label="5"></a></span>
<span id="cb5-6"><a aria-label="6"></a><span class="co">/* Registerausschnitt, fiktiv. Kein vollstaendiger Treiber. */</span></span>
<span id="cb5-7"><a aria-label="7"></a><span class="dt">void</span> init_pwm_registers<span class="op">(</span><span class="dt">void</span><span class="op">)</span> <span class="op">{</span></span>
<span id="cb5-8"><a aria-label="8"></a>    TIMER_PSC <span class="op">=</span> <span class="dv">99</span><span class="op">;</span>     <span class="co">/* Teiler 100 */</span></span>
<span id="cb5-9"><a aria-label="9"></a>    TIMER_ARR <span class="op">=</span> <span class="dv">999</span><span class="op">;</span>    <span class="co">/* N = 1000 */</span></span>
<span id="cb5-10"><a aria-label="10"></a>    TIMER_CCR1 <span class="op">=</span> <span class="dv">0</span><span class="op">;</span></span>
<span id="cb5-11"><a aria-label="11"></a><span class="op">}</span></span>
<span id="cb5-12"><a aria-label="12"></a><span class="co">/* Danach noch noetig: Takt, Pin-Mux, Modus, Polaritaet,</span></span>
<span id="cb5-13"><a aria-label="13"></a><span class="co">   Preload, Kanal- und Timerfreigabe laut Datenblatt. */</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li>PSC: Takt drosseln</li>
<li>ARR: Periode / Frequenz</li>
<li>CCR1: Duty Cycle Kanal 1</li>
</ul>
<aside class="notes">
<p>MMIO-Register für den Timer knüpft an die bisherige Frage nach Signal und Überwachung an. TIMER_BASE 0x40000000 ist fiktiv. Die Makros benennen Zugriffe. PSC 99 und ARR 999 folgen aus 100 MHz und 1 kHz. CCR 0 legt eine inaktive Schwelle fest. uint32_t beschreibt den Lehrzugriff, nicht jede echte Busbreite. Danach fehlen Takt, Pin-Mux, Modus, Polarität, Preload, Update und Freigabe. Drei Register allein erzeugen keinen Pin. PSC: Takt drosseln. ARR: Periode / Frequenz. CCR1: Duty Cycle Kanal 1. Verständnischeck: Warum CCR 0 vor dem Start? Als inaktive Anfangsschwelle. Der sichere Ausgang braucht zusätzlich die Beschaltung. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="hilfsfunktion-prozent-ccr" class="slide level2">
<h2>Hilfsfunktion: Prozent → CCR</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb6-1"><a aria-label="1"></a><span class="dt">void</span> set_led_duty_percent<span class="op">(</span><span class="dt">uint8_t</span> percent<span class="op">)</span> <span class="op">{</span></span>
<span id="cb6-2"><a aria-label="2"></a>    <span class="cf">if</span> <span class="op">(</span>percent <span class="op">&gt;</span> <span class="dv">100</span><span class="op">)</span> percent <span class="op">=</span> <span class="dv">100</span><span class="op">;</span></span>
<span id="cb6-3"><a aria-label="3"></a>    <span class="dt">const</span> <span class="dt">uint32_t</span> N <span class="op">=</span> <span class="dv">1000</span><span class="bu">u</span><span class="op">;</span> <span class="co">/* ARR + 1 im Kernmodell */</span></span>
<span id="cb6-4"><a aria-label="4"></a>    <span class="dt">uint32_t</span> ccr <span class="op">=</span> <span class="op">((</span><span class="dt">uint32_t</span><span class="op">)</span>percent <span class="op">*</span> N<span class="op">)</span> <span class="op">/</span> <span class="dv">100</span><span class="bu">u</span><span class="op">;</span></span>
<span id="cb6-5"><a aria-label="5"></a>    TIMER_CCR1 <span class="op">=</span> ccr<span class="op">;</span></span>
<span id="cb6-6"><a aria-label="6"></a><span class="op">}</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li>0, 25, 50 und 100 Prozent ergeben CCR 0, 250, 500 und 1000.</li>
<li>Kleine Abstraktion erleichtert die Main-Logik</li>
</ul>
<aside class="notes">
<p>Hilfsfunktion: Prozent → CCR knüpft an die bisherige Frage nach Signal und Überwachung an. percent wird auf 0 bis 100 begrenzt. Der Cast vor der Multiplikation vermeidet einen zu kleinen Typ. Geteilt durch 100 ist Ganzzahldivision. 0, 25, 50 und 100 ergeben 0, 250, 500 und 1000. Die Funktion setzt elektrischen Duty, nicht b gleich 0,5. Dafür wäre CCR 218. 100 Prozent braucht CCR gleich N. Bei N 1000 passt das in ein 16-Bit-Feld. Preload verzögert die Wirkung bis zum Update. 0, 25, 50 und 100 Prozent ergeben CCR 0, 250, 500 und 1000. Kleine Abstraktion erleichtert die Main-Logik. Verständnischeck: Setzt 50 Prozent die Helligkeitsstufe 0,5? Nein, das wäre im Gammamodell CCR 218. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fading-alle-10-ms" class="slide level2">
<h2>Fading alle 10 ms</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb7-1"><a aria-label="1"></a><span class="co">/* Lehrcode — nicht kompiliert.</span></span>
<span id="cb7-2"><a aria-label="2"></a><span class="co">   10 MHz Systemzeit, nicht der 1-MHz-PWM-Zähler. */</span></span>
<span id="cb7-3"><a aria-label="3"></a><span class="pp">#define FADE_TICKS </span>UINT64_C<span class="op">(</span><span class="dv">100000</span><span class="op">)</span></span>
<span id="cb7-4"><a aria-label="4"></a><span class="dt">static</span> <span class="dt">uint64_t</span> next_fade<span class="op">;</span></span>
<span id="cb7-5"><a aria-label="5"></a><span class="dt">static</span> <span class="dt">int</span> brightness<span class="op">;</span></span>
<span id="cb7-6"><a aria-label="6"></a><span class="dt">static</span> <span class="dt">int</span> direction<span class="op">;</span></span>
<span id="cb7-7"><a aria-label="7"></a></span>
<span id="cb7-8"><a aria-label="8"></a><span class="dt">void</span> fade_init<span class="op">(</span><span class="dt">uint64_t</span> now<span class="op">)</span> <span class="op">{</span></span>
<span id="cb7-9"><a aria-label="9"></a>    brightness <span class="op">=</span> <span class="dv">0</span><span class="op">;</span></span>
<span id="cb7-10"><a aria-label="10"></a>    direction <span class="op">=</span> <span class="dv">1</span><span class="op">;</span></span>
<span id="cb7-11"><a aria-label="11"></a>    next_fade <span class="op">=</span> now <span class="op">+</span> FADE_TICKS<span class="op">;</span></span>
<span id="cb7-12"><a aria-label="12"></a><span class="op">}</span></span>
<span id="cb7-13"><a aria-label="13"></a></span>
<span id="cb7-14"><a aria-label="14"></a><span class="dt">bool</span> fade_poll<span class="op">(</span><span class="dt">uint64_t</span> now<span class="op">)</span> <span class="op">{</span></span>
<span id="cb7-15"><a aria-label="15"></a>    <span class="cf">if</span> <span class="op">(</span>now <span class="op">&lt;</span> next_fade<span class="op">)</span></span>
<span id="cb7-16"><a aria-label="16"></a>        <span class="cf">return</span> <span class="kw">false</span><span class="op">;</span></span>
<span id="cb7-17"><a aria-label="17"></a>    <span class="dt">uint64_t</span> k <span class="op">=</span> UINT64_C<span class="op">(</span><span class="dv">1</span><span class="op">)</span></span>
<span id="cb7-18"><a aria-label="18"></a>        <span class="op">+</span> <span class="op">(</span>now <span class="op">-</span> next_fade<span class="op">)</span> <span class="op">/</span> FADE_TICKS<span class="op">;</span></span>
<span id="cb7-19"><a aria-label="19"></a>    next_fade <span class="op">+=</span> k <span class="op">*</span> FADE_TICKS<span class="op">;</span></span>
<span id="cb7-20"><a aria-label="20"></a>    brightness <span class="op">+=</span> direction<span class="op">;</span></span>
<span id="cb7-21"><a aria-label="21"></a>    <span class="cf">if</span> <span class="op">(</span>brightness <span class="op">==</span> <span class="dv">100</span> <span class="op">||</span> brightness <span class="op">==</span> <span class="dv">0</span><span class="op">)</span></span>
<span id="cb7-22"><a aria-label="22"></a>        direction <span class="op">=</span> <span class="op">-</span>direction<span class="op">;</span></span>
<span id="cb7-23"><a aria-label="23"></a>    set_led_duty_percent<span class="op">((</span><span class="dt">uint8_t</span><span class="op">)</span>brightness<span class="op">);</span></span>
<span id="cb7-24"><a aria-label="24"></a>    <span class="cf">return</span> <span class="kw">true</span><span class="op">;</span></span>
<span id="cb7-25"><a aria-label="25"></a><span class="op">}</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<p>Der Watchdog-Feed steht nicht in dieser Funktion.</p>
<aside class="notes">
<p>Fading alle 10 ms knüpft an die bisherige Frage nach Signal und Überwachung an. FADE_TICKS 100000 bei 10 MHz sind 10 ms. fade_init setzt den ersten Termin auf now plus ein Intervall. Bei now kleiner next_fade passiert nichts. k gleich 1 plus der ganzzahlige Abstand überspringt verpasste Plätze, ein Aufruf macht genau einen Schritt. Start bei 0: erster Schritt bei 100000 auf 1 Prozent, nächster Termin 200000. Bei next 100000 und now 350000 ist k gleich 3, next wird 400000, ein Schritt. Derselbe now noch einmal ändert nichts. 100 Schritte erreichen 100 Prozent, danach geht es abwärts, nach 200 Schritten wieder 0. Ideal sind 1 s hin und 2 s für hin und zurück. Der Feed bleibt außerhalb. Ein altes Erfolgskennzeichen darf nicht weiter füttern. Lehrcode, nicht kompiliert. Die Zeitbasis überläuft im betrachteten Betrieb nicht. Verständnischeck: Was macht now gleich 350000? k gleich 3, nächster Termin 400000, genau ein Helligkeitsschritt. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="den-crash-provozieren" class="slide level2">
<h2>Den Crash provozieren</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/04_aktorik_sicherheit/safe-state.png"></p>
<figcaption>Von 1,2 bis 3,0 s laeuft PWM ohne Main. Reset und sicherer Aktorzustand fallen auseinander.</figcaption>
</figure>
</div>
<ul>
<li>Watchdog-Timeout z. B. 2 s</li>
<li>Button löst einen künstlichen Hänger aus, keinen Deadlock</li>
<li>Letzter Feed bei 1,0 s, Hänger ab 1,2 s, nominaler Reset bei 3,0 s</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb8-1"><a aria-label="1"></a><span class="cf">if</span> <span class="op">(</span>button_pressed<span class="op">())</span> <span class="op">{</span></span>
<span id="cb8-2"><a aria-label="2"></a>    printf<span class="op">(</span><span class="st">"Freeze — warte auf WDT...</span><span class="sc">\n</span><span class="st">"</span><span class="op">);</span></span>
<span id="cb8-3"><a aria-label="3"></a>    <span class="cf">while</span> <span class="op">(</span><span class="dv">1</span><span class="op">)</span> <span class="op">{</span></span>
<span id="cb8-4"><a aria-label="4"></a>        <span class="co">/* kein wdt_feed() */</span></span>
<span id="cb8-5"><a aria-label="5"></a>    <span class="op">}</span></span>
<span id="cb8-6"><a aria-label="6"></a><span class="op">}</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Den Crash provozieren knüpft an die bisherige Frage nach Signal und Überwachung an. Der while-1-Zustand ist ein Hänger, kein Deadlock, weil keine zwei Seiten aufeinander warten. printf kann selbst blockieren. Feeds bei 0, 0,5 und 1 s, Hänger bei 1,2 s, Reset bei 3 s. Vom Hänger bis zum Reset sind 1,8 s, weil die 2 s seit 1 s laufen. PWM kann bis zum Reset den letzten CCR halten. Der Pinzustand nach Reset ist plattformabhängig. Watchdog-Timeout z. B. 2 s. Button löst einen künstlichen Hänger aus, keinen Deadlock. Letzter Feed bei 1,0 s, Hänger ab 1,2 s, nominaler Reset bei 3,0 s. Verständnischeck: Warum 1,8 s? 3 minus 1,2, weil der Timeout seit dem Feed bei 1 s läuft. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="reset-ursache-lesen" class="slide level2">
<h2>Reset-Ursache lesen</h2>
<ul>
<li>Nach Reboot: warum neu gestartet?</li>
<li>Reset-Reason-Register (Power-/Reset-Block)</li>
<li>Beim Boot zuerst auswerten</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb9-1"><a aria-label="1"></a><span class="dt">void</span> check_reset_reason<span class="op">(</span><span class="dt">void</span><span class="op">)</span> <span class="op">{</span></span>
<span id="cb9-2"><a aria-label="2"></a>    <span class="dt">uint32_t</span> reason <span class="op">=</span> <span class="op">*(</span><span class="dt">volatile</span> <span class="dt">uint32_t</span> <span class="op">*)</span>RESET_REASON_REG<span class="op">;</span></span>
<span id="cb9-3"><a aria-label="3"></a>    <span class="cf">if</span> <span class="op">(</span>reason <span class="op">&amp;</span> WDT_RESET_FLAG<span class="op">)</span> <span class="op">{</span></span>
<span id="cb9-4"><a aria-label="4"></a>        printf<span class="op">(</span><span class="st">"WDT-Reset nach Freeze</span><span class="sc">\n</span><span class="st">"</span><span class="op">);</span></span>
<span id="cb9-5"><a aria-label="5"></a>        <span class="co">/* optional: loggen / sicherer Modus */</span></span>
<span id="cb9-6"><a aria-label="6"></a>    <span class="op">}</span></span>
<span id="cb9-7"><a aria-label="7"></a><span class="op">}</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Reset-Ursache lesen knüpft an die bisherige Frage nach Signal und Überwachung an. RESET_REASON_REG und das Flag sind fiktiv. Das Flag nennt eine Resetquelle, nicht die volle Ursachenkette. Mehrere Flags können gesetzt sein. W1C, write one to clear, löscht durch Schreiben einer Eins, falls das Datenblatt das so definiert. Diagnose darf den sicheren Start nicht blockieren. Nach Reboot: warum neu gestartet?. Reset-Reason-Register (Power-/Reset-Block). Beim Boot zuerst auswerten. Verständnischeck: Beweist das Flag einen konkreten Softwarefehler? Nein, nur die gemeldete Resetquelle. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="best-practices-wdt-intervall" class="slide level2">
<h2>Best Practices: WDT-Intervall</h2>
<ul>
<li>Der maximale gesunde Feed-Abstand muss kleiner sein als der kürzeste tatsächliche Timeout</li>
<li>Im fiktiven ±20-Prozent-Taktmodell liegt ein 2-s-Nennwert zwischen etwa 1,667 s und 2,5 s</li>
<li>Abschalt- und Lastzeit kommen gegebenenfalls hinzu</li>
</ul>
<aside class="notes">
<p>Best Practices: WDT-Intervall knüpft an die bisherige Frage nach Signal und Überwachung an. Der gesunde Feed-Abstand muss unter dem kürzesten Timeout liegen. Die verlangte Reaktion muss den längsten Timeout plus Abschalt- und Lastzeit fassen. 2,5 s plus 0,02 s plus 0,08 s sind 2,60 s Modellzeit und verfehlen eine 1-s-Anforderung. Bootzeit zählt nur, wenn der sichere Zustand erst dann entsteht. Ein 0,5-s-Feed kann gesund sein und die 1-s-Reaktion trotzdem verfehlen. Der maximale gesunde Feed-Abstand muss kleiner sein als der kürzeste tatsächliche Timeout. Im fiktiven ±20-Prozent-Taktmodell liegt ein 2-s-Nennwert zwischen etwa 1,667 s und 2,5 s. Abschalt- und Lastzeit kommen gegebenenfalls hinzu. Verständnischeck: Passt 2,5 s Maximum zu einer 1-s-Reaktion? Nein. Die nächste Folie nimmt die noch offene Modellfrage auf. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="zusammenfassung-block-4" class="slide level2">
<h2>Zusammenfassung Block 4</h2>
<ul>
<li>PWM-Duty ist nicht allgemein Leistung oder Wahrnehmung</li>
<li>Feed nach frischem Fortschritt, nicht allein weil eine ISR weiterläuft</li>
<li>Reset garantiert keinen sicheren Aktorzustand</li>
<li>Das Labor ist geplant und hier nicht ausgeführt</li>
</ul>
<p>Vielen Dank — wir sehen uns im Labor.</p>
<aside class="notes">
<p>Zusammenfassung Block 4 knüpft an die bisherige Frage nach Signal und Überwachung an. Der Block erklärt Ausgabe, Zeitüberwachung und Wiederanlauf, keinen Safety-Nachweis. f_PWM folgt aus Takt, PSC und ARR, D aus CCR geteilt durch N. Feed nach frischem Fortschritt ist nicht schon richtig, nur weil er in main steht. Rechnung, Lehrcode und Labor bleiben drei Evidenzen. Renode ist nicht ausgeführt. PWM-Duty ist nicht allgemein Leistung oder Wahrnehmung. Feed nach frischem Fortschritt, nicht allein weil eine ISR weiterläuft. Reset garantiert keinen sicheren Aktorzustand. Verständnischeck: Welche drei Grenzen bleiben? Duty ist nicht Leistung, Feed ist kein Richtigkeitsbeweis, Reset ist kein sicherer Aktor. Als Ausblick bleiben echte Hardwaredaten und ein optionales späteres Labor. Adressen, Takte und Toleranzen sind Lehrannahmen. Code auf der Folie ist Lehrcode und wurde nicht kompiliert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="../assets/dhbw_logo.svg" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 8.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script>
    /**
     * Fit Quarto/Reveal Mermaid SVGs to remaining slide space.
     * Dimensions from getBoundingClientRect are viewport pixels; CSS sizes inside
     * Reveal slides are unscaled — divide by Reveal.getScale().
     */
    (function () {
      const BOTTOM_PAD = 36;
      const SIDE_PAD_RATIO = 0.92;
      const MAX_SCALE = 3.4;

      function presentSlide() {
        var present = document.querySelector("section.present");
        if (!present) return null;
        var nested = present.querySelector(":scope > section.present");
        return nested || present;
      }

      function revealScale() {
        if (window.Reveal && typeof Reveal.getScale === "function") {
          var s = Reveal.getScale();
          return s > 0.05 ? s : 1;
        }
        return 1;
      }

      function ensureWrap(svg) {
        var parent = svg.parentElement;
        if (!parent) return null;
        if (parent.classList.contains("mermaid-fit")) return parent;
        var wrap = document.createElement("div");
        wrap.className = "mermaid-fit";
        parent.insertBefore(wrap, svg);
        wrap.appendChild(svg);
        return wrap;
      }

      function contentBottomAbove(slide, wrap) {
        var top = slide.getBoundingClientRect().top;
        var bottom = top + 8;
        var children = slide.children;
        for (var i = 0; i < children.length; i++) {
          var el = children[i];
          if (el === wrap || el.classList.contains("mermaid-fit")) break;
          if (el.querySelector && el.querySelector("svg.mermaid-js")) break;
          if (el.tagName === "ASIDE") continue;
          var r = el.getBoundingClientRect();
          if (r.height > 1) bottom = Math.max(bottom, r.bottom);
        }
        return bottom;
      }

      function naturalSize(svg) {
        if (svg.dataset.natW && svg.dataset.natH) {
          return { w: +svg.dataset.natW, h: +svg.dataset.natH };
        }
        var vb = svg.viewBox && svg.viewBox.baseVal;
        if (vb && vb.width > 0 && vb.height > 0) {
          svg.dataset.natW = String(vb.width);
          svg.dataset.natH = String(vb.height);
          return { w: vb.width, h: vb.height };
        }
        var wAttr = parseFloat(svg.getAttribute("width"));
        var hAttr = parseFloat(svg.getAttribute("height"));
        if (wAttr > 0 && hAttr > 0) {
          svg.dataset.natW = String(wAttr);
          svg.dataset.natH = String(hAttr);
          return { w: wAttr, h: hAttr };
        }
        var r = svg.getBoundingClientRect();
        var rs = revealScale();
        var w = r.width / rs || 320;
        var h = r.height / rs || 120;
        svg.dataset.natW = String(w);
        svg.dataset.natH = String(h);
        return { w: w, h: h };
      }

      function fitMermaids() {
        var slide = presentSlide();
        if (!slide) return;

        var rs = revealScale();
        var slideRect = slide.getBoundingClientRect();
        var svgs = slide.querySelectorAll("svg.mermaid-js");

        for (var i = 0; i < svgs.length; i++) {
          var svg = svgs[i];
          var wrap = ensureWrap(svg);
          if (!wrap) continue;

          svg.style.removeProperty("transform");
          svg.style.removeProperty("max-width");
          svg.style.removeProperty("zoom");
          wrap.style.zoom = "";

          var nat = naturalSize(svg);
          var above = contentBottomAbove(slide, wrap);
          var availW = (slideRect.width * SIDE_PAD_RATIO) / rs;
          var availH = Math.max(72, (slideRect.bottom - above - BOTTOM_PAD) / rs);

          var scale = Math.min(availW / nat.w, availH / nat.h, MAX_SCALE);
          if (!(scale > 0)) scale = 1;

          var targetW = Math.max(1, Math.round(nat.w * scale));
          var targetH = Math.max(1, Math.round(nat.h * scale));

          svg.setAttribute("width", targetW);
          svg.setAttribute("height", targetH);
          svg.style.width = targetW + "px";
          svg.style.height = targetH + "px";
          svg.style.display = "block";
          svg.style.margin = "0.35rem auto 0";
        }
      }

      function scheduleFit() {
        requestAnimationFrame(function () {
          fitMermaids();
          setTimeout(fitMermaids, 150);
          setTimeout(fitMermaids, 500);
          setTimeout(fitMermaids, 1100);
        });
      }

      window.addEventListener("load", scheduleFit);

      function bindReveal() {
        if (!window.Reveal || !Reveal.on) return false;
        Reveal.on("ready", scheduleFit);
        Reveal.on("slidechanged", scheduleFit);
        if (Reveal.isReady && Reveal.isReady()) scheduleFit();
        return true;
      }

      if (!bindReveal()) {
        window.addEventListener("load", function () {
          var tries = 0;
          var id = setInterval(function () {
            if (bindReveal() || ++tries > 50) clearInterval(id);
          }, 100);
        });
      }

      window.dhbwMermaidFit = fitMermaids;
    })();
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Kopiert");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Kopiert");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/dantschi\.github\.io\/mct3\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>