<!DOCTYPE html>
<html lang="de"><head>
<link href="../assets/dhbw_logo.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.19">

  <meta name="author" content="Prof.&nbsp;Dr.-Ing. Daniel Klünder">
  <title>Mikrocomputertechnik 3 – 08 · KI-Beschleuniger &amp; Edge AI</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-f355cf95444bdbe7a358cd689c441e6f.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
  <script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
  <link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&amp;display=swap" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">08 · KI-Beschleuniger &amp; Edge AI</h1>
  <p class="subtitle">Mikrocomputertechnik 3 · Von der Memory-Wall neuronaler Netze zu Systolic Arrays und TensorFlow Lite</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Prof.&nbsp;Dr.-Ing. Daniel Klünder
</div>
</div>
</div>

</section>
<section id="willkommen-zu-block-8" class="slide level2">
<h2>Willkommen zu Block 8!</h2>
<ul>
<li>Willkommen zur achten Vorlesung in Mikrocomputertechnik 3</li>
<li>Block 7: OoO und Branch Prediction maximieren die General-Purpose-CPU</li>
<li>Heute: Workload Künstliche Intelligenz — und warum Spezialhardware (NPUs) hilft</li>
<li>Ziel: Memory Wall bei neuronalen Netzen verstehen und den Weg zu DSAs skizzieren</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="3.8" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%
flowchart LR
  A[Block 7: CPU] --&gt;|Alleskönner| B[Kontrollfluss]
  C[Heute: NPU] --&gt;|Spezialist| D[Datenfluss / KI]
  style C fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Willkommen zu Block 8 knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Heute stehen regelmäßige Rechnung und Datenbewegung im Mittelpunkt. Eine NPU ist nicht für jede lokale Inferenz nötig. CPU, DSP und Vektoren können kleine Modelle tragen. Willkommen zur achten Vorlesung in Mikrocomputertechnik 3. Block 7: OoO und Branch Prediction maximieren die General-Purpose-CPU. Verständnischeck: Braucht jede lokale Inferenz eine NPU? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="anknüpfung-compiler-labor" class="slide level2">
<h2>Anknüpfung: Compiler-Labor</h2>
<p>Kurz-Recap aus Block 7 (Vertiefung im Übungsblatt):</p>
<ul>
<li>Godbolt zeigt die Übersetzung, kein OoO-Timing</li>
<li><code>-O3</code> garantiert weder Unrolling noch kürzere Laufzeit</li>
<li>Scheduling und Unrolling sind mögliche, keine sicheren Folgen</li>
<li>Eine MAC-Kette bleibt RAW. Mehrere Akkumulatoren können unabhängig sein</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb1-1"><a aria-label="1"></a><span class="co">/* Konzept: Unrolling von for (i = 0; i &lt; 4; i++) a[i] = 0; */</span></span>
<span id="cb1-2"><a aria-label="2"></a>a<span class="op">[</span><span class="dv">0</span><span class="op">]</span> <span class="op">=</span> <span class="dv">0</span><span class="op">;</span></span>
<span id="cb1-3"><a aria-label="3"></a>a<span class="op">[</span><span class="dv">1</span><span class="op">]</span> <span class="op">=</span> <span class="dv">0</span><span class="op">;</span></span>
<span id="cb1-4"><a aria-label="4"></a>a<span class="op">[</span><span class="dv">2</span><span class="op">]</span> <span class="op">=</span> <span class="dv">0</span><span class="op">;</span></span>
<span id="cb1-5"><a aria-label="5"></a>a<span class="op">[</span><span class="dv">3</span><span class="op">]</span> <span class="op">=</span> <span class="dv">0</span><span class="op">;</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Anknüpfung: Compiler-Labor knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Vier Arrayzeilen sind manuelles Unrolling, kein Compileroutput. Eine Summe sum plus gleich w mal x behält eine RAW-Kette. Godbolt zeigt Übersetzung, kein OoO-Timing. -O3 garantiert weder Unrolling noch kürzere Laufzeit. Godbolt zeigt die Übersetzung, kein OoO-Timing. <code>-O3</code> garantiert weder Unrolling noch kürzere Laufzeit. Verständnischeck: Beweist die Vier-Zeilen-Folge einen -O3-Output? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="grenze-der-general-purpose-cpu" class="slide level2">
<h2>Grenze der General-Purpose-CPU</h2>
<ul>
<li>Mehr Issue-Breite verteuert Scheduler, Ports und Bypass. Quadratisch gilt nicht pauschal für ROB, Renaming und Decode zusammen</li>
<li>OoO kann Loads überlappen. Es hebt eine einzelne Akkumulatorkette nicht auf</li>
<li>DLP ergänzt ILP. SIMD ist eine Umsetzung, keine Definition von DLP</li>
</ul>
<aside class="notes">
<p>Grenze der General-Purpose-CPU knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. OoO kann Loads und unabhängige Produkte überlappen. Eine einzelne Akkumulatorkette bleibt abhängig. DLP ist gleiche Rechnung an vielen Werten. SIMD ist eine Umsetzung davon, nicht die Definition. Mehr Issue-Breite verteuert Scheduler, Ports und Bypass. Quadratisch gilt nicht pauschal für ROB, Renaming und Decode zusammen. OoO kann Loads überlappen. Es hebt eine einzelne Akkumulatorkette nicht auf. Verständnischeck: Kann OoO bei einem Dot Product helfen? Ja, aber die Summenkette bleibt. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="neuer-workload-edge-ai" class="slide level2">
<h2>Neuer Workload: Edge AI</h2>
<ul>
<li>Edge AI umfasst Endgerät und Gateway. Nicht jede lokale Inferenz braucht eine NPU</li>
<li>Beispiele: Schrittzählung, Wake-Word, Vibrationsdiagnose an Maschinen</li>
<li>Dauerbetrieb auf knappen Ressourcen (Energie, SRAM, Flash)</li>
</ul>
<aside class="notes">
<p>Neuer Workload: Edge AI knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Edge umfasst Endgerät und Gateway. Training bestimmt Parameter, Inferenz verwendet sie. Eine Aktivitätsklasse ist keine Schrittzahl. Eine Schwellenwertlösung kann reichen. Edge AI umfasst Endgerät und Gateway. Nicht jede lokale Inferenz braucht eine NPU. Beispiele: Schrittzählung, Wake-Word, Vibrationsdiagnose an Maschinen. Verständnischeck: Ist ein lokales Gateway Edge? Ja. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="cloud-ai-vs.-edge-ai" class="slide level2">
<h2>Cloud AI vs.&nbsp;Edge AI</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/08_ki_beschleuniger_edge_ai/edge.png"></p>
<figcaption>Lokal und Cloud sind Optionen. Funk ist nicht immer die teurere Seite.</figcaption>
</figure>
</div>
<p>Warum nicht alles in die Cloud?</p>
<ol type="1">
<li>Latenz — sicherheitskritische Reaktionen dulden keine Funkwartezeit</li>
<li>Privacy — Audio/Video sollen oft lokal bleiben</li>
<li>Energie und Verfügbarkeit sind Anforderungen. Funk ist nicht immer teurer als lokale Rechnung</li>
</ol>
<div class="cell" data-reveal="true" data-fig-width="3.6" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%
flowchart LR
  A[Sensordaten] --&gt;|lokal| B[Edge-NPU]
  A -.-&gt;|Funk| C[Cloud]
  style B fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Cloud AI vs.&nbsp;Edge AI knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Lokal kann CPU, DSP, NPU oder Gateway rechnen. Lokalität ist keine Datenschutzgarantie. Kommunikation ist nicht stets teurer als Rechnen. Verständnischeck: Kann lokale Rechnung mehr Energie brauchen als Übertragung? Ja. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="agenda" class="slide level2">
<h2>Agenda</h2>
<ol type="1">
<li>KI-Herausforderung und Memory Wall</li>
<li>DSPs und SIMD</li>
<li>RISC-V Vector Extension (RVV)</li>
<li>NPU und Systolic Arrays</li>
<li>Edge-AI-Software / TensorFlow Lite</li>
</ol>
<aside class="notes">
<p>Agenda knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Die Agenda fragt nach Bytes, Parallelität, Vektorlänge, lokaler Wiederverwendung und Firmware. Das sind kombinierbare Wege, keine Pflichttreppe. TFLM ist hier nicht als Labor vorhanden. Verständnischeck: Warum Speicher vor dem Array? Weil lokale Wege Verkehr vermeiden sollen. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="lernziele-block-8" class="slide level2">
<h2>Lernziele Block 8</h2>
<ul>
<li>Memory Wall bei Matrix-/MAC-Lasten erklären</li>
<li>MAC-Operation und ihre Bedeutung benennen</li>
<li>ILP vs.&nbsp;DLP unterscheiden</li>
<li>Systolic Arrays einordnen</li>
<li>TensorFlow Lite Micro Workflow skizzieren</li>
</ul>
<aside class="notes">
<p>Lernziele Block 8 knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Prüfbar sind die Dense-Ausgabe, Parameter gegen MACs, die Speichergrenze, SIMD gegen DLP, das zurückgegebene VL und die TFLM-Lebensdauer. TOPS brauchen Datentyp und Zählkonvention. Memory Wall bei Matrix-/MAC-Lasten erklären. MAC-Operation und ihre Bedeutung benennen. Verständnischeck: Was zuerst zu TOPS? Datentyp, Ops je MAC und Peak gegen Anwendung. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-leitfrage-des-tages" class="slide level2">
<h2>Die Leitfrage des Tages</h2>
<ul>
<li>Kleines Netz: z. B. <span class="math inline">\(10^{6}\)</span> Gewichte — Inferenz verrechnet sie mit Aktivierungen</li>
<li>SRAM, Cache-Hit, Flash und DRAM haben verschiedene Kosten. Nicht jeder Zugriff ist ein DRAM-Miss</li>
<li>Wie rechnet man Millionen MACs/s auf knapper Energie, ohne am Speicher zu ersticken?</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="3.2" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%
flowchart TD
  A[RAM: Gewichte] --&gt;|Flaschenhals| B[ALU]
  B --&gt; C[Ergebnis]
  style A fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Die Leitfrage des Tages knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Eine Million Float32-Gewichte sind 4 MB, als Int8 1 MB. Bias und Aktivierungen fehlen. Nicht jede MCU hat DRAM. Eine Million Gewichte sind nur bei einmaliger Nutzung eine Million MACs. Kleines Netz: z. B. <span class="math inline">\(10^{6}\)</span> Gewichte — Inferenz verrechnet sie mit Aktivierungen. SRAM, Cache-Hit, Flash und DRAM haben verschiedene Kosten. Nicht jeder Zugriff ist ein DRAM-Miss. Verständnischeck: Sind eine Million Gewichte eine Million MACs? Nur in diesem Sonderfall. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="aufgabe-sechs-macs" class="slide level2">
<h2>Aufgabe — Sechs MACs</h2>
<p><span class="math inline">\(W=\begin{bmatrix}1&amp;2&amp;3\\0&amp;-1&amp;4\end{bmatrix}\)</span>, <span class="math inline">\(x=\begin{bmatrix}2\\1\\3\end{bmatrix}\)</span>, <span class="math inline">\(b=\begin{bmatrix}1\\-2\end{bmatrix}\)</span>.</p>
<p>Warum sind sechs Gewichte hier sechs produktbezogene MACs, bei einer Faltung aber nicht? Was ist <span class="math inline">\(y\)</span>?</p>
<aside class="notes">
<p>Aufgabe — Sechs MACs knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. W ist [[1,2,3],[0,-1,4]], x ist [2,1,3], b ist [1,-2]. Die erste Zeile ist 1 mal 2 plus 2 mal 1 plus 3 mal 3 plus 1 gleich 14. Die zweite ist 0 plus minus 1 plus 12 minus 2 gleich 9. Sechs Gewichte und zwei Bias sind acht Parameter und sechs produktbezogene MACs. Verständnischeck: Wie viele Parameter? Acht. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="neuronale-netze-auf-hardware-ebene" class="slide level2">
<h2>Neuronale Netze auf Hardware-Ebene</h2>
<ul>
<li>Abseits des Hypes: große Zahlenarrays</li>
<li>Inputs / Activations: Sensordaten (z. B. <span class="math inline">\(28\times 28\)</span> Pixel)</li>
<li>Weights: trainierte Konstanten (oft Flash)</li>
<li>Neuron: gewichtete Summe der Eingänge (+ Aktivierung, hier ausgeblendet)</li>
</ul>
<aside class="notes">
<p>Neuronale Netze auf Hardware-Ebene knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Aktivierungen sind auch Zwischenergebnisse. 28 mal 28 ist 784 nur bei einem Kanal. Gewichte können im Flash liegen, Summen oft in SRAM oder Registern. Eine Matrix ist nicht das ganze Netz. Abseits des Hypes: große Zahlenarrays. Inputs / Activations: Sensordaten (z. B. <span class="math inline">\(28\times 28\)</span> Pixel). Verständnischeck: Sind alle Aktivierungen Sensorwerte? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="mathematik-matrix-dot-product" class="slide level2">
<h2>Mathematik: Matrix / Dot Product</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/08_ki_beschleuniger_edge_ai/dense.png"></p>
<figcaption>y0 = 14 und y1 = 9. Sechs MACs, acht Parameter, 14 arithmetische Operationen.</figcaption>
</figure>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb2-1"><a aria-label="1"></a><span class="dt">float</span> sum <span class="op">=</span> <span class="fl">0.0</span><span class="bu">f</span><span class="op">;</span></span>
<span id="cb2-2"><a aria-label="2"></a><span class="cf">for</span> <span class="op">(</span><span class="dt">int</span> i <span class="op">=</span> <span class="dv">0</span><span class="op">;</span> i <span class="op">&lt;</span> N<span class="op">;</span> i<span class="op">++)</span> <span class="op">{</span></span>
<span id="cb2-3"><a aria-label="3"></a>    sum <span class="op">+=</span> input<span class="op">[</span>i<span class="op">]</span> <span class="op">*</span> weights<span class="op">[</span>i<span class="op">];</span></span>
<span id="cb2-4"><a aria-label="4"></a><span class="op">}</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li>Kein Kontrollfluss-Chaos: vorhersagbarer Datenstrom</li>
<li>Naive Lehrzählung ohne Registerreuse: zwei Loads, eine Multiplikation, eine Addition. Das ist keine Übersetzung in Assembler</li>
</ul>
<aside class="notes">
<p>Mathematik: Matrix / Dot Product knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Sechs MACs sind in der benannten Konvention zwölf arithmetische Ops plus zwei Biasadditionen, also vierzehn. Das sind keine Takte. Int8-Gewichte, Int32-Bias und Int8-Eingaben sind 6 plus 8 plus 3 gleich 17 Byte, optional plus zwei Ausgaben 19. Elf Byte wäre ein anderes, unvollständiges Budget. Kein Kontrollfluss-Chaos: vorhersagbarer Datenstrom. Pro Iteration: zwei Loads + Mul + Add. Verständnischeck: Warum nicht acht MACs? Die Biaswerte werden separat addiert. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="mac-operation" class="slide level2">
<h2>MAC-Operation</h2>
<ul>
<li>Multiply-Accumulate: <span class="math inline">\(a \leftarrow a + (w \times x)\)</span></li>
<li><span class="math inline">\(w\)</span>: Gewicht, <span class="math inline">\(x\)</span>: Activation, <span class="math inline">\(a\)</span>: Akkumulator</li>
<li>KI-Chips: oft in TOPS (viele MAC-Äquivalente / s) spezifiziert — nicht nur in MHz</li>
</ul>
<aside class="notes">
<p>MAC-Operation knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. a gleich 5, w gleich 2, x gleich 3 ergibt 11. Eine MAC kann eine Instruktion und trotzdem zwei Ops sein. Float-FMA rundet einmal, getrennte Mul und Add zweimal. Eine MAC ist nicht automatisch ein Takt. Multiply-Accumulate: <span class="math inline">\(a \leftarrow a + (w \times x)\)</span>. <span class="math inline">\(w\)</span>: Gewicht, <span class="math inline">\(x\)</span>: Activation, <span class="math inline">\(a\)</span>: Akkumulator. Verständnischeck: Ist eine MAC immer ein Takt? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="anatomie-einer-mac-auf-risc-v" class="slide level2">
<h2>Anatomie einer MAC auf RISC-V</h2>
<p>Vereinfachte Befehlsfolge:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode numberSource asm number-lines code-with-copy"><code class="sourceCode fasm"><span id="cb3-1"><a aria-label="1"></a># Konzept — RV32IM <span class="op">(</span>mul<span class="op">)</span><span class="co">; Adressen schematisch</span></span>
<span id="cb3-2"><a aria-label="2"></a>lw  t0<span class="op">,</span> <span class="dv">0</span><span class="op">(</span>s1<span class="op">)</span>    <span class="op">#</span> x</span>
<span id="cb3-3"><a aria-label="3"></a>lw  t1<span class="op">,</span> <span class="dv">0</span><span class="op">(</span>s2<span class="op">)</span>    <span class="op">#</span> w</span>
<span id="cb3-4"><a aria-label="4"></a><span class="bu">mul</span> t2<span class="op">,</span> t0<span class="op">,</span> t1</span>
<span id="cb3-5"><a aria-label="5"></a><span class="bu">add</span> t3<span class="op">,</span> t3<span class="op">,</span> t2   <span class="op">#</span> a <span class="op">+=</span> w<span class="op">*</span>x</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><code>mul</code>/<code>add</code> sind hier Ganzzahl, die C-Schleife darüber ist Float. Das ist eine Analogie, keine Float-ISA</li>
<li>Zwei Loads und zwei Ops gelten nur ohne Wiederverwendung und ohne FMA</li>
</ul>
<aside class="notes">
<p>Anatomie einer MAC auf RISC-V knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. lw lädt ein 32-Bit-Muster. mul und add sind hier Integer der M-Erweiterung, keine Float-Rechnung. Zwei Loads sind nicht zwei DRAM-Misses. Der Akkumulator muss vorher gesetzt sein. Lehrcode, nicht assembliert. <code>mul</code>/<code>add</code> sind hier Ganzzahl, die C-Schleife darüber ist Float. Das ist eine Analogie, keine Float-ISA. Zwei Loads und zwei Ops gelten nur ohne Wiederverwendung und ohne FMA. Verständnischeck: Warum reicht RV32I nicht für mul? Es braucht die M-Erweiterung. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="arithmetic-intensity-zahlenbeispiel" class="slide level2">
<h2>Arithmetic Intensity: Zahlenbeispiel</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/08_ki_beschleuniger_edge_ai/roofline.png"></p>
<figcaption>Knick bei 1 Op/Byte. Naiv 0,25, mit Wiederverwendung 0,5. Lehrwerte, keine Messung.</figcaption>
</figure>
</div>
<ul>
<li><span class="math inline">\(\mathrm{AI} = \mathrm{Ops}/\mathrm{Bytes}\)</span></li>
<li>Grenze dieses Beispiels: DRAM zum On-Chip-Speicher. Output und Bias zählen hier noch nicht</li>
<li><span class="math inline">\(2\)</span> Ops und <span class="math inline">\(8\)</span> Byte ergeben <span class="math inline">\(0{,}25\)</span> Ops/Byte. Das ist nicht allgemein „unter 1 = memory-bound“</li>
<li>Erreichbar ist <span class="math inline">\(\min(P_{peak}, Bandbreite \times AI)\)</span>. Der Knick liegt bei <span class="math inline">\(P_{peak}/Bandbreite\)</span></li>
</ul>
<aside class="notes">
<p>Arithmetic Intensity: Zahlenbeispiel knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. I_arith ist Ops je Byte über die Grenze DRAM nach On-Chip. Peak 8 Ops je Takt, Bandbreite 8 Byte je Takt, Knick bei 1 Op je Byte. Bei 0,25 sind höchstens 2 Ops je Takt erreichbar, bei 0,5 höchstens 4. Das ist eine Obergrenze, keine Messung. <span class="math inline">\(\mathrm{AI} = \mathrm{Ops}/\mathrm{Bytes}\)</span>. Grenze dieses Beispiels: DRAM zum On-Chip-Speicher. Output und Bias zählen hier noch nicht. Verständnischeck: Warum liegt der Knick bei 1? 8 Ops geteilt durch 8 Byte. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="datenproblem-gewichte" class="slide level2">
<h2>Datenproblem: Gewichte</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/08_ki_beschleuniger_edge_ai/tile.png"></p>
<figcaption>Dieselbe 2×2-Rechnung: 64 Byte naiv, 32 Byte aus einem Tile.</figcaption>
</figure>
</div>
<ul>
<li>Modelle wie ResNet-50: Millionen Parameter — Megabyte-Bereich</li>
<li>L1 oft nur Dutzende KiB → Matrizen passen nicht</li>
<li>Ein Streaming-Datensatz erzeugt nicht bei jedem Skalarzugriff einen Capacity Miss. Cachezeilen und Prefetch bündeln Zugriffe</li>
</ul>
<aside class="notes">
<p>Datenproblem: Gewichte knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. A ist [[1,2],[3,4]], B ist [[5,6],[7,8]], C ist [[19,22],[43,50]]. Acht MACs sind 16 Ops. Ohne Halten 16 mal 4 Byte gleich 64 Byte, mit Tile 32 Byte. Outputs fehlen in dieser Zahl. Auch eine CPU kann Tiles bilden. Modelle wie ResNet-50: Millionen Parameter — Megabyte-Bereich. L1 oft nur Dutzende KiB → Matrizen passen nicht. Verständnischeck: Warum halbieren sich die Eingangsbytes? Jeder Wert wird einmal geladen und lokal wiederverwendet. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="memory-wall-bei-ki" class="slide level2">
<h2>Memory Wall bei KI</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Phase</th>
<th>Typische Dauer (schematisch)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Load <span class="math inline">\(x\)</span>, <span class="math inline">\(w\)</span> (DRAM)</td>
<td>viele Takte</td>
</tr>
<tr class="even">
<td>MUL + ADD</td>
<td>wenige Takte</td>
</tr>
<tr class="odd">
<td>nächster Load</td>
<td>wieder viele Takte</td>
</tr>
</tbody>
</table>
<ul>
<li>ALU oft idle; Energie geht in Wartezeit und Datentransport</li>
</ul>
<aside class="notes">
<p>Memory Wall bei KI knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Die Tabelle ist ein pessimistischer serieller Pfad, nicht jede echte Latenz. Requests können sich überlappen. Vier Transfers mit Latenz 3: seriell bis Takt 12, gepipelinet bis Takt 6, wenn ein Start je Takt erlaubt ist. ALU oft idle; Energie geht in Wartezeit und Datentransport. Verständnischeck: Warum nicht jede Miss-Latenz addieren? Zugriffe können sich überlappen. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="rechenbeispiel-106-macs" class="slide level2">
<h2>Rechenbeispiel: <span class="math inline">\(10^{6}\)</span> MACs</h2>
<ul>
<li><span class="math inline">\(10^{6}\)</span> Gewichte sind nur dann <span class="math inline">\(10^{6}\)</span> MACs, wenn jedes Gewicht genau einmal multipliziert wird</li>
<li>Eine Faltung nutzt Gewichte mehrfach. Sequenz, Bild und Batch ändern den Aufwand</li>
<li>Einzelne Miss-Latenzen darf man nicht zu einer Summe addieren, wenn Zugriffe überlappen</li>
</ul>
<aside class="notes">
<p>Rechenbeispiel: <span class="math inline">\(10^{6}\)</span> MACs knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Eine Million MACs, einmal je Gewicht, sind zwei Millionen Ops. Naiv zwei Float32-Operanden sind acht Millionen Byte. Bei 8 Ops und 8 Byte je Takt sind das 250000 Rechen- und eine Million Transfertakte. Kein Boardwert. <span class="math inline">\(10^{6}\)</span> Gewichte sind nur dann <span class="math inline">\(10^{6}\)</span> MACs, wenn jedes Gewicht genau einmal multipliziert wird. Eine Faltung nutzt Gewichte mehrfach. Sequenz, Bild und Batch ändern den Aufwand. Verständnischeck: Welche Untergrenze dominiert? Der Transfer. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="warum-ooo-hier-wenig-hilft" class="slide level2">
<h2>Warum OoO hier wenig hilft</h2>
<ul>
<li>OoO/Predictor: stark bei unregelmäßigem Kontrollfluss</li>
<li>MAC-Schleife: linear, hoch vorhersagbar</li>
<li>Der Predictor ist bei einer festen Schleife nicht wertlos, aber selten der Engpass</li>
<li>Unabhängige Akkumulatoren kann OoO ausführen. Die Speichergrenze bleibt, wenn die Arithmetic Intensity niedrig ist</li>
</ul>
<aside class="notes">
<p>Warum OoO hier wenig hilft knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. OoO hilft bei Überlappung, hebt aber die Bandbreitengrenze nicht. Eine Summe bleibt RAW-abhängig. Niedrige Intensity beweist nicht, dass der Scheduler nutzlos ist. OoO/Predictor: stark bei unregelmäßigem Kontrollfluss. MAC-Schleife: linear, hoch vorhersagbar. Verständnischeck: Beweist niedrige Intensity Nutzlosigkeit? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fazit-cpu-vs.-ki-last" class="slide level2">
<h2>Fazit: CPU vs.&nbsp;KI-Last</h2>
<ul>
<li>ALU-Auslastung bei naiver Matrixrechnung oft gering</li>
<li>Viel Zeit/Energie in Transport und Instruktionsverwaltung</li>
<li>Spezialhardware kann passen, wenn Operatoren, Form und Auslastung sie nutzen</li>
</ul>
<aside class="notes">
<p>Fazit: CPU vs.&nbsp;KI-Last knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Geringe Auslastung folgt hier aus Versorgung oder Abhängigkeit, nicht aus jeder KI auf der CPU. Tiling kann helfen, bevor neue Hardware kommt. ALU-Auslastung bei naiver Matrixrechnung oft gering. Viel Zeit/Energie in Transport und Instruktionsverwaltung. Verständnischeck: Welche Softwaretechnik zuerst? Tiling innerhalb der Speichergrenze. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="lösung-data-level-parallelism-dlp" class="slide level2">
<h2>Lösung: Data-Level Parallelism (DLP)</h2>
<ul>
<li>Weg von „viele verschiedene Instruktionen“ (ILP)</li>
<li>DLP: dieselbe Rechnung an vielen Werten. SIMD ist eine mögliche Umsetzung, nicht die Definition</li>
<li>Hundert unabhängige Produkte brauchen weder hundert Rechenwerke noch einen Takt</li>
</ul>
<aside class="notes">
<p>Lösung: Data-Level Parallelism (DLP) knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Hundert unabhängige Produkte sind DLP. Sie brauchen weder hundert Units noch einen Takt. Ein Befehl für viele Daten ist SIMD, nicht die Definition von DLP. Weg von „viele verschiedene Instruktionen“ (ILP). DLP: dieselbe Rechnung an vielen Werten. SIMD ist eine mögliche Umsetzung, nicht die Definition. Verständnischeck: Garantiert ein Befehl hundert Produkte im selben Takt? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="domain-specific-architecture-dsa" class="slide level2">
<h2>Domain-Specific Architecture (DSA)</h2>
<ul>
<li>Eine DSA kann Formate und Operatoren einschränken. Programmierbarkeit muss nicht vollständig entfallen</li>
<li>DSA: Silizium für eine Domäne (z. B. Matrizen) — oft deutlich effizienter</li>
<li>Evolutionsschritte: SIMD → DSP-Tricks → Vektoren → NPUs</li>
</ul>
<aside class="notes">
<p>Domain-Specific Architecture (DSA) knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Eine DSA passt Silizium an ein Muster an und kann Operatoren einschränken. SIMD, DSP, RVV und NPU können im SoC zusammenarbeiten. Kein Ersatzpfad ist vorgeschrieben. Extreme DLP-Optimierung → Verlust der Allzweck-Fähigkeit. DSA: Silizium für eine Domäne (z. B. Matrizen) — oft deutlich effizienter. Verständnischeck: Muss der DSP durch eine NPU ersetzt werden? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fragen-mac-und-memory-wall" class="slide level2">
<h2>Fragen? — MAC und Memory Wall</h2>
<ul>
<li>Was leistet die MAC-Operation im Netz?</li>
<li>Warum kehrt die Memory Wall bei KI zurück?</li>
<li>ILP vs.&nbsp;DLP?</li>
</ul>
<aside class="notes">
<p>Fragen? — MAC und Memory Wall knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. MAC verbindet Produkt und Summe. ILP und DLP können zugleich vorliegen. Die Memory Wall ist hier Transport, die RAW-Kette ist Abhängigkeit. Was leistet die MAC-Operation im Netz?. Warum kehrt die Memory Wall bei KI zurück?. Verständnischeck: Kann ein Programm beides haben? Ja. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="was-bedeutet-simd" class="slide level2">
<h2>Was bedeutet SIMD?</h2>
<ul>
<li>SIMD: Single Instruction, Multiple Data</li>
<li>Paradebeispiel für DLP</li>
<li>Ein Fetch/Decode → intern mehrere parallele Operationen</li>
</ul>
<aside class="notes">
<p>Was bedeutet SIMD knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Ein Decode steuert gleiche Operationen auf getrennten Lanes. Vier Lanes sind nicht vier Befehle. Weniger Fetch garantiert keine Gesamtenergieeinsparung. SIMD: Single Instruction, Multiple Data. Paradebeispiel für DLP. Verständnischeck: Sind vier Lanes vier Befehle? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="simd-prinzip" class="slide level2">
<h2>SIMD-Prinzip</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/08_ki_beschleuniger_edge_ai/simd.png"></p>
<figcaption>Vier 8-Bit-Lanes addieren getrennt. Ein Int8-Produkt braucht einen breiteren Akkumulator.</figcaption>
</figure>
</div>
<ul>
<li>Skalar (SISD): <code>add</code> → eine Addition</li>
<li>SIMD: ein Befehl → mehrere parallele Adds auf Daten-Lanes</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="3.8" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%
flowchart LR
  A[SIMD Add] --&gt; B{Verteiler}
  B --&gt; A1[ALU1]
  B --&gt; A2[ALU2]
  B --&gt; A3[ALU3]
  B --&gt; A4[ALU4]
  style A fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>SIMD-Prinzip knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Unsigned modulo 256: 01 plus 02 ist 03, 10 plus 20 ist 30, 7F plus 01 ist 80, FF plus 01 ist 00. Das ist Addition, kein Dot Product. 20 mal 20 gleich 400 passt nicht in ein Byte. Signed und Sättigung sind andere Verträge. Skalar (SISD): <code>add</code> → eine Addition. SIMD: ein Befehl → mehrere parallele Adds auf Daten-Lanes. Verständnischeck: Warum kein Übertrag in die Nachbarlane? Jede Lane rechnet modulo 256 für sich. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="packed-simd" class="slide level2">
<h2>Packed SIMD</h2>
<ul>
<li>Problem: schmale ISA-Register, breite Parallelität?</li>
<li>Lösung: Register in Lanes zerlegen (z. B. 32 Bit → <span class="math inline">\(4\times 8\)</span> Bit)</li>
<li>SIMD-Op: Lane für Lane parallel, ohne Carry zwischen Lanes</li>
</ul>
<aside class="notes">
<p>Packed SIMD knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Ein normales 32-Bit-add darf Bytes überlaufen. Packed SIMD braucht eine Instruktion mit Lanevertrag. Vier gepackte Bytes und ein gewöhnliches add genügen nicht. Problem: schmale ISA-Register, breite Parallelität?. Lösung: Register in Lanes zerlegen (z. B. 32 Bit → <span class="math inline">\(4\times 8\)</span> Bit). Verständnischeck: Genügt normales add? Nein, Überträge vermischen die Felder. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="digital-signal-processors-dsps" class="slide level2">
<h2>Digital Signal Processors (DSPs)</h2>
<ul>
<li>Vor dem KI-Boom: DSPs für Audio, Modem, Filter</li>
<li>Algorithmen (FIR etc.): wie KI stark Array-/Skalarprodukt-lastig</li>
<li>Vorläufer vieler NPU-Ideen</li>
</ul>
<aside class="notes">
<p>Digital Signal Processors (DSPs) knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Ein FIR ist y von n gleich Summe h von k mal x von n minus k. Mit h gleich 1 und 2 und Fenster 3 und 4 ist das 11. Dense ähnelt der Summe, der zeitliche Kontext kann anders sein. Vor dem KI-Boom: DSPs für Audio, Modem, Filter. Algorithmen (FIR etc.): wie KI stark Array-/Skalarprodukt-lastig. Verständnischeck: Was teilen FIR und Dense? Viele Produkte in einer Summe. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="dsp-dedizierte-mac-einheit" class="slide level2">
<h2>DSP: dedizierte MAC-Einheit</h2>
<ul>
<li>Mul und Add oft fest verdrahtet als eine MAC</li>
<li><span class="math inline">\(a + (x \times w)\)</span> in wenigen Takten / oft einem Zyklus (je nach Design)</li>
<li>Weniger Instruktionsfolge als auf skalarer RISC-ALU</li>
</ul>
<aside class="notes">
<p>DSP: dedizierte MAC-Einheit knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Initiierungsintervall 1 erlaubt einen neuen unabhängigen Start je Takt. Die Ergebnislatenz kann trotzdem mehrere Takte sein. Eine abhängige Summe braucht Weiterleitung oder Warten. Mul und Add oft fest verdrahtet als eine MAC. <span class="math inline">\(a + (x \times w)\)</span> in wenigen Takten / oft einem Zyklus (je nach Design). Verständnischeck: Beweist ein Start je Takt Latenz 1? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="super-harvard-in-dsps" class="slide level2">
<h2>Super-Harvard in DSPs</h2>
<ul>
<li>Mehrere parallele Speicherpfade gegen die Memory Wall</li>
<li>Typisch: Code-Bus + getrennte Datenbusse für <span class="math inline">\(x\)</span> und <span class="math inline">\(w\)</span></li>
<li>Loads und MAC können im selben Takt überlappen</li>
</ul>
<aside class="notes">
<p>Super-Harvard in DSPs knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Super-Harvard ist eine benannte DSP-Idee, nicht jeder DSP. Zwei Busse garantieren nicht zwei Operanden, wenn dieselbe Bank kollidiert. Mehrere parallele Speicherpfade gegen die Memory Wall. Typisch: Code-Bus + getrennte Datenbusse für <span class="math inline">\(x\)</span> und <span class="math inline">\(w\)</span>. Verständnischeck: Garantieren zwei Busse zwei Operanden? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="zero-overhead-loops" class="slide level2">
<h2>Zero-Overhead Loops</h2>
<ul>
<li>Hardware-Schleifenzähler: Start, Ende, Count</li>
<li>Kein <code>beq</code> pro Iteration — kein Predictor-Overhead</li>
<li>PC-Wrap in Hardware bis Count abgelaufen</li>
</ul>
<aside class="notes">
<p>Zero-Overhead Loops knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Ein Hardwareloop spart bestimmte Branch- und Zählerbefehle. Er entfernt keine Speicherwartezeit. Die spätere RVV-Schleife mit bnez ist Software. Hardware-Schleifenzähler: Start, Ende, Count. Kein <code>beq</code> pro Iteration — kein Predictor-Overhead. Verständnischeck: Entfernt der Hardwareloop Speicherwarten? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="grenze-packed-simd-skaliert-schlecht" class="slide level2">
<h2>Grenze: Packed SIMD skaliert schlecht</h2>
<ul>
<li>Feste Vektorbreite in der ISA (z. B. 128 / 256 / 512 Bit)</li>
<li>Alter Code nutzt neue breitere Units nicht automatisch</li>
<li>Oft Neukompilieren / Intrinsics für jede Generation</li>
</ul>
<aside class="notes">
<p>Grenze: Packed SIMD skaliert schlecht knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. 128 Bit fassen vier Int32-Werte. Alter Code bleibt korrekt, nutzt breitere Befehle aber nicht automatisch. Neukompilieren ist eine Möglichkeit, keine Pflicht für Korrektheit. Feste Vektorbreite in der ISA (z. B. 128 / 256 / 512 Bit). Alter Code nutzt neue breitere Units nicht automatisch. Verständnischeck: Wie viele Int32 in 128 Bit? Vier, ohne Taktaussage. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="instruction-fetch-overhead-bleibt" class="slide level2">
<h2>Instruction-Fetch-Overhead bleibt</h2>
<ul>
<li>Auch breites SIMD: weiterhin viele Instruktionen für große Matrizen</li>
<li>Decode und I-Cache kosten Energie</li>
<li>Wunsch: „rechne lange auf diesen Daten“ mit weniger Instruction Stream</li>
</ul>
<aside class="notes">
<p>Instruction-Fetch-Overhead bleibt knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. SIMD senkt Befehle je Element, nicht den Fetch auf null. Loads und Schleifen bleiben. Weniger Fetch ist kein Joule-Nachweis. Auch breites SIMD: weiterhin viele Instruktionen für große Matrizen. Decode und I-Cache kosten Energie. Verständnischeck: Verschwindet Fetch? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="übergang-zu-vektoren" class="slide level2">
<h2>Übergang zu Vektoren</h2>
<ul>
<li>Packed SIMD hat eine feste Breite. RVV wählt die aktive Elementzahl zur Laufzeit</li>
<li>RISC-V Vector Extension (RVV): Ansatz für skalierbare Vektor-ISAs</li>
<li>Code-Idee: dieselbe Software auf schmalen und breiten Implementierungen</li>
</ul>
<aside class="notes">
<p>Übergang zu Vektoren knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. RVV wählt die aktive Länge zur Laufzeit. Ein Register bleibt endlich. Ein langes Array wird in Stücken verarbeitet. Dieselbe Binärdatei braucht passende ISA und ABI. Weg von starrem Packed SIMD → flexible Vektorlängen. RISC-V Vector Extension (RVV): Ansatz für skalierbare Vektor-ISAs. Verständnischeck: Kann ein Register das ganze Array halten? Nicht beliebig lang. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="kurzfazit-dsp-und-simd" class="slide level2">
<h2>Kurzfazit: DSP und SIMD</h2>
<ul>
<li>DLP ist die Datenparallelität. SIMD nutzt sie mit einem gemeinsamen Operationstyp</li>
<li>Packed SIMD: breite Register, starre Breiten</li>
<li>DSPs: MAC, Multi-Bus, Zero-Overhead Loops</li>
<li>Vektoren und NPUs können bei passenden Operatoren helfen. Ein DSP ist dadurch nicht veraltet</li>
</ul>
<aside class="notes">
<p>Kurzfazit: DSP und SIMD knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. DLP ist nicht der Name von SIMD. Packed SIMD hat feste Breite. DSP-MAC, Busse und Hardwareloops sind getrennte Merkmale. Vektoren sind kein Beweis, dass DSPs veraltet sind. DLP ist die Datenparallelität. SIMD nutzt sie mit einem gemeinsamen Operationstyp. Packed SIMD: breite Register, starre Breiten. Verständnischeck: Ist DLP nur ein anderer Name für SIMD? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fragen-simd-und-dsp" class="slide level2">
<h2>Fragen? — SIMD und DSP</h2>
<ul>
<li>Wie senkt SIMD den Fetch/Decode-Overhead?</li>
<li>Warum ist eine Hardware-MAC für Signalverarbeitung wertvoll?</li>
<li>Warum muss Packed-SIMD-Code oft neu angepasst werden?</li>
</ul>
<aside class="notes">
<p>Fragen? — SIMD und DSP knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. SIMD senkt Fetch je Lanegruppe. Die Hardware-MAC passt zur Produktsumme, wenn die Daten da sind. Feste Breite wird nicht automatisch größer, nur weil neue Hardware breiter ist. Wie senkt SIMD den Fetch/Decode-Overhead?. Warum ist eine Hardware-MAC für Signalverarbeitung wertvoll?. Verständnischeck: Warum ist die MAC wertvoll? Sie bündelt die häufige Rechnung, wenn die Versorgung passt. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="echte-vektor-architektur" class="slide level2">
<h2>Echte Vektor-Architektur</h2>
<ul>
<li>Verarbeitet lineare Arrays (Vektoren), nicht nur Skalare</li>
<li>Anders als Packed SIMD: Vektorlänge flexibel, nicht in feste Registerhäppchen geschnitten</li>
<li>Befehlssatz abstrahiert: „Addiere Vektor A und B“ — unabhängig von der Implementierungsbreite</li>
</ul>
<aside class="notes">
<p>Echte Vektor-Architektur knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Ein Vektorbefehl hat eine konfigurierte Länge. Ist N größer als VLMAX, folgen mehrere Stücke. VLEN ist nicht die Lanezahl. Ein Load ist keine Garantie, dass alles in einem Takt fertig ist. Verarbeitet lineare Arrays (Vektoren), nicht nur Skalare. Anders als Packed SIMD: Vektorlänge flexibel, nicht in feste Registerhäppchen geschnitten. Verständnischeck: Was passiert bei zu langem Array? Mehrere VL-Stücke. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="vektor-register-file" class="slide level2">
<h2>Vektor-Register-File</h2>
<ul>
<li>Neben <code>x0</code>–<code>x31</code>: Vektorregister <code>v0</code>–<code>v31</code></li>
<li>Jedes <code>v</code>-Register hält viele Elemente gleichzeitig</li>
<li>Kapazität hängt von der Implementierung ab (<span class="math inline">\(\mathrm{VLEN}\)</span> = Vector Length)</li>
</ul>
<aside class="notes">
<p>Vektor-Register-File knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Es gibt 32 Vektorregister zu je VLEN Bit. Bei VLEN 128, SEW 32 und LMUL 1 ist VLMAX 4, nicht 128. VL ist die aktive Elementzahl. Eine Lanegruppe kann diese Elemente über mehrere Takte rechnen. Neben <code>x0</code>–<code>x31</code>: Vektorregister <code>v0</code>–<code>v31</code>. Jedes <code>v</code>-Register hält viele Elemente gleichzeitig. Verständnischeck: Ist VLEN 128 gleich 128 Elemente? Nein, bei 32 Bit sind es vier. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="risc-v-vector-extension-rvv" class="slide level2">
<h2>RISC-V Vector Extension (RVV)</h2>
<ul>
<li>Offizielle RISC-V-Erweiterung für Vektormathematik (u. a. ML, Krypto)</li>
<li>Neue Instruktionen, z. B. <code>vadd.vv</code></li>
<li>Software kennt die physische Breite oft nicht (Watch vs.&nbsp;Server)</li>
<li>Frage: ein Binary für unbekannte <span class="math inline">\(\mathrm{VLEN}\)</span>?</li>
</ul>
<aside class="notes">
<p>RISC-V Vector Extension (RVV) knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. vadd.vv addiert Integer-Vektoren. Krypto und Int8-TinyML brauchen passende Erweiterungen. Dieselbe Binärdatei läuft nicht auf jeder Uhr und jedem Server. Offizielle RISC-V-Erweiterung für Vektormathematik (u. a. ML, Krypto). Neue Instruktionen, z. B. <code>vadd.vv</code>. Verständnischeck: Läuft dasselbe Binary überall nur wegen RVV? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="vsetvli-hardware-agnostisch" class="slide level2">
<h2><code>vsetvli</code> / hardware-agnostisch</h2>
<ul>
<li>Software: „Array mit <span class="math inline">\(N\)</span> Elementen“</li>
<li>Bei LMUL <span class="math inline">\(= 1\)</span> ist <span class="math inline">\(\mathrm{VLMAX} = \mathrm{VLEN}/\mathrm{SEW}\)</span>. Allgemein <span class="math inline">\(\mathrm{VLMAX} = \mathrm{LMUL}\times\mathrm{VLEN}/\mathrm{SEW}\)</span></li>
<li><code>vsetvli</code> liefert nicht immer <span class="math inline">\(\min(AVL, VLMAX)\)</span></li>
<li>Schleife läuft in Hardware-Schritten durch das Array</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode numberSource asm number-lines code-with-copy"><code class="sourceCode fasm"><span id="cb4-1"><a aria-label="1"></a># RVV <span class="fl">1.0</span><span class="op">,</span> LMUL<span class="op">=</span><span class="dv">1</span><span class="op">,</span> e32<span class="op">,</span> ta<span class="op">,</span> ma<span class="op">.</span> Nicht in diesem Repo assembliert<span class="op">.</span></span>
<span id="cb4-2"><a aria-label="2"></a><span class="fu">loop:</span></span>
<span id="cb4-3"><a aria-label="3"></a>    vsetvli t0<span class="op">,</span> a0<span class="op">,</span> e32<span class="op">,</span> m1<span class="op">,</span> ta<span class="op">,</span> ma</span>
<span id="cb4-4"><a aria-label="4"></a>    vle32<span class="op">.</span>v v1<span class="op">,</span> <span class="op">(</span>a1<span class="op">)</span></span>
<span id="cb4-5"><a aria-label="5"></a>    vle32<span class="op">.</span>v v2<span class="op">,</span> <span class="op">(</span>a2<span class="op">)</span></span>
<span id="cb4-6"><a aria-label="6"></a>    vadd<span class="op">.</span>vv v3<span class="op">,</span> v1<span class="op">,</span> v2</span>
<span id="cb4-7"><a aria-label="7"></a>    vse32<span class="op">.</span>v v3<span class="op">,</span> <span class="op">(</span>a3<span class="op">)</span></span>
<span id="cb4-8"><a aria-label="8"></a>    slli t1<span class="op">,</span> t0<span class="op">,</span> <span class="dv">2</span></span>
<span id="cb4-9"><a aria-label="9"></a>    <span class="bu">add</span> a1<span class="op">,</span> a1<span class="op">,</span> t1</span>
<span id="cb4-10"><a aria-label="10"></a>    <span class="bu">add</span> a2<span class="op">,</span> a2<span class="op">,</span> t1</span>
<span id="cb4-11"><a aria-label="11"></a>    <span class="bu">add</span> a3<span class="op">,</span> a3<span class="op">,</span> t1</span>
<span id="cb4-12"><a aria-label="12"></a>    <span class="bu">sub</span> a0<span class="op">,</span> a0<span class="op">,</span> t0</span>
<span id="cb4-13"><a aria-label="13"></a>    bnez a0<span class="op">,</span> loop</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p><code>vsetvli</code> / hardware-agnostisch knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. a0 ist der Rest, a1 und a2 sind Quellen, a3 das Ziel, t0 das zurückgegebene VL. slli mal 4 rechnet Bytes, nicht Datenwerte. Ist AVL höchstens VLMAX, ist VL gleich AVL. Liegt AVL zwischen VLMAX und dem Doppelten, liegt VL zwischen der Hälfte aufgerundet und VLMAX. Ab dem Doppelten ist VL gleich VLMAX. Bei N gleich 0 passiert nichts. ta und ma dürfen nicht als neue Ergebnisse gelesen werden. Lehrcode, nicht assembliert. Software: „Array mit <span class="math inline">\(N\)</span> Elementen“. Bei LMUL <span class="math inline">\(= 1\)</span> ist <span class="math inline">\(\mathrm{VLMAX} = \mathrm{VLEN}/\mathrm{SEW}\)</span>. Allgemein <span class="math inline">\(\mathrm{VLMAX} = \mathrm{LMUL}\times\mathrm{VLEN}/\mathrm{SEW}\)</span>. Verständnischeck: Warum um VL vorrücken? Die Hardware darf im mittleren Bereich kürzer wählen. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ein-binary-viele-mathrmvlen" class="slide level2">
<h2>Ein Binary, viele <span class="math inline">\(\mathrm{VLEN}\)</span></h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/08_ki_beschleuniger_edge_ai/rvv.png"></p>
<figcaption>128 Bit: 250 Schritte zu VL 4. 1024 Bit: 31 Schritte zu VL 32 plus VL 8.</figcaption>
</figure>
</div>
<p>Beispiel: 1000 Elemente, <code>vadd.vv</code> (schematisch)</p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 15%">
<col style="width: 31%">
<col style="width: 30%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th>Plattform</th>
<th>Breite (schematisch)</th>
<th><span class="math inline">\(\mathrm{VL}\)</span> (e32)</th>
<th>Schleifenläufe</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Edge</td>
<td>schmal (z. B. 128 Bit)</td>
<td>4</td>
<td>250</td>
</tr>
<tr class="even">
<td>Server</td>
<td>1024 Bit, LMUL 1</td>
<td>32, dann 20+20 oder 32+8</td>
<td>32</td>
</tr>
</tbody>
</table>
<p>Gleiche RVV-Schleifenidee skaliert mit <span class="math inline">\(\mathrm{VLEN}\)</span> — ohne feste Packed-SIMD-Breite im Quelltext.</p>
<aside class="notes">
<p>Ein Binary, viele <span class="math inline">\(\mathrm{VLEN}\)</span> knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. 1000 Elemente, e32, m1: VLEN 128 ergibt VLMAX 4 und 250 Iterationen. VLEN 1024 ergibt VLMAX 32. Nach 30 vollen Stücken bleiben 40. Die erste VL darf 20 bis 32 sein, der Rest ist dann exakt. 20 plus 20, 24 plus 16 und 32 plus 8 sind zulässige Policies mit 32 Iterationen. Je Zeiger insgesamt 4000 Byte. 31 mal 32 plus 8 ist nur eine Policy. Verständnischeck: Ist bei AVL 40 und VLMAX 32 zwingend VL 32? Nein, 20 bis 32 sind erlaubt. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="energie-weniger-instruction-fetch" class="slide level2">
<h2>Energie: weniger Instruction Fetch</h2>
<ul>
<li>Architektonisch viele Elemente je Befehl. Physisch kann dieselbe Lane sie über mehrere Takte rechnen</li>
<li>Skalar: dutzende Loads/Adds/Branches aus dem I-Cache</li>
<li>Weniger Fetch kann Energie sparen und garantiert keinen geringeren Gesamtverbrauch</li>
</ul>
<aside class="notes">
<p>Energie: weniger Instruction Fetch knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Weniger Befehle können den Front-End-Anteil senken. Loads, Register und Laufzeit bleiben. Weniger Instruktionen sind nicht automatisch weniger Joule. Ein Vektorbefehl → viele Elemente parallel. Skalar: dutzende Loads/Adds/Branches aus dem I-Cache. Verständnischeck: Garantieren weniger Befehle weniger Energie? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="vector-loadstore" class="slide level2">
<h2>Vector Load/Store</h2>
<ul>
<li>Breite Speicherpfade zum D-Cache / SRAM</li>
<li><code>vle32.v</code>: zusammenhängender Block → Vektorregister</li>
<li>Ähnlich Burst-Idee: DRAM-/Bus-Lokalität besser ausnutzen</li>
</ul>
<aside class="notes">
<p>Vector Load/Store knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. vle32.v mit VL 4 lädt vier 32-Bit-Werte, also 16 Byte, nicht vier Byte. Der Befehl darf intern mehrere Takte brauchen. Eine Cachezeile ist keine garantierte DRAM-Transaktion. Breite Speicherpfade zum D-Cache / SRAM. <code>vle32.v</code>: zusammenhängender Block → Vektorregister. Verständnischeck: Lädt VL 4 vier Bytes? Nein, 16 Nutzbytes. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="chaining" class="slide level2">
<h2>Chaining</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/08_ki_beschleuniger_edge_ai/chain.png"></p>
<figcaption>Gleiche Achse 1–9. Ohne Chaining letztes Ergebnis Ende Takt 9, mit Chaining Ende Takt 6.</figcaption>
</figure>
</div>
<ul>
<li>MAC: Mul dann Add — Zwischenergebnis sonst zurück ins Registerfile</li>
<li>Chaining ist eine Option des Kerns. Eine FMA ist eine andere Instruktion mit einer Rundung</li>
<li>Weniger Registerverkehr, höherer Durchsatz</li>
</ul>
<aside class="notes">
<p>Chaining knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Mul startet in den Takten 1 bis 4 und endet 2 bis 5. Ohne Chaining startet Add in 6 bis 9 und endet dort. Mit elementweisem Weiterreichen startet Add in 3 bis 6. Das erste Ergebnis ist Ende Takt 3 statt 6, das letzte Ende Takt 6 statt 9. Die Rechenzahl bleibt gleich. Das ist kein RVV-Zeitversprechen und keine FMA. MAC: Mul dann Add — Zwischenergebnis sonst zurück ins Registerfile. Chaining ist eine Option des Kerns. Eine FMA ist eine andere Instruktion mit einer Rundung. Verständnischeck: Was spart das Modell? Wartezeit, nicht Multiplikationen. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="rvv-und-tinyml" class="slide level2">
<h2>RVV und TinyML</h2>
<ul>
<li>TinyML: Inferenz auf sehr knappen Energie-/SRAM-Budgets</li>
<li>RVV-fähige Kerne: flexibel (noch volle CPU) + Vektor-Durchsatz</li>
<li>Typisch: Keyword Spotting, kleine Sensor-Modelle am Edge</li>
</ul>
<aside class="notes">
<p>RVV und TinyML knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. TinyML ist Inferenz bei knappem Speicher und Energie. RVV beschleunigt nur, wenn der Kernel sie benutzt. Firmware kann ohne Betriebssystem laufen. Ein vorhandenes TFLM-RVV-Build liegt hier nicht vor. TinyML: Inferenz auf sehr knappen Energie-/SRAM-Budgets. RVV-fähige Kerne: flexibel (noch volle CPU) + Vektor-Durchsatz. Verständnischeck: Nutzt TFLM automatisch RVV? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="grenzen-von-vektoren" class="slide level2">
<h2>Grenzen von Vektoren</h2>
<ul>
<li>Registerfile bleibt: lesen/schreiben kostet Energie und limitiert Skalierung</li>
<li>Ein großes Modellfile beweist den Registerengpass nicht. Form und Reuse entscheiden</li>
<li>Nächste Stufe: Daten fließen ohne ständiges Zurückschreiben — Systolic Arrays</li>
</ul>
<aside class="notes">
<p>Grenzen von Vektoren knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Registerports kosten Energie. Ein großes Modellfile beweist nicht, dass das Registerfile der Engpass ist. Ein systolisches Gitter ist eine andere Entscheidung, keine Pflichtstufe. Registerfile bleibt: lesen/schreiben kostet Energie und limitiert Skalierung. Sehr große Modelle: Pfad ALU → Register wird Engpass. Verständnischeck: Beweist die Dateigröße den Engpass? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="kurzfazit-rvv" class="slide level2">
<h2>Kurzfazit RVV</h2>
<ul>
<li>Die Software verarbeitet lange Arrays in Stücken der Länge VL</li>
<li>VLEN ist die Registerbreite in Bit, VL die aktive Elementzahl</li>
<li>Dieselbe Binärdatei braucht passende ISA, XLEN und ABI</li>
<li>Weniger Befehlsstrom kann helfen. DLP ist die Datenparallelität, nicht der Befehl selbst</li>
<li>Loads und Chaining können Wartezeit senken. Chaining ist keine RVV-Garantie</li>
</ul>
<aside class="notes">
<p>Kurzfazit RVV knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Die Schleife benutzt das zurückgegebene VL, nicht eine feste VLEN. Loads heben die Bandbreite nicht auf. Chaining ist optional. Physische Parallelität folgt nicht aus der Bitbreite. Ein Befehl, lange Arrays. <span class="math inline">\(\mathrm{VLEN}\)</span>/<span class="math inline">\(\mathrm{VL}\)</span> abstrahiert Hardwarebreite. Verständnischeck: Welche Größe rückt den Zeiger? VL mal 4 Byte. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="aufgabe-avl-40" class="slide level2">
<h2>Aufgabe — AVL 40</h2>
<p>VLMAX ist 32. Nach 30 Schritten mit VL 32 bleiben 40 Elemente. Welche letzten VL-Werte sind zulässig, und wie viele Iterationen ergeben 1000 Elemente?</p>
<aside class="notes">
<p>Aufgabe — AVL 40 knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. AVL 40 und VLMAX 32 liegen zwischen 32 und 64. Die Untergrenze ist aufgerundet 20. VL 16 wäre zu klein. Danach ist der Rest exakt die nächste VL. 20 plus 20 sind je 80 Byte, 32 plus 8 sind 128 dann 32 Byte. Verständnischeck: Wäre 16 plus 24 zulässig? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="was-ist-eine-npu" class="slide level2">
<h2>Was ist eine NPU?</h2>
<ul>
<li>Neural Processing Unit: Beschleuniger für Inferenz (manchmal Training)</li>
<li>Namen: TPU (Google), Neural Engine (Apple), NVDLA, …</li>
<li>Nicht jede NPU ist ein systolisches Gitter oder nur für Matrizen. Kontrolle bleibt im System</li>
<li>CPU füttert Adressen/Puffer (ähnlich DMA-Aufträgen)</li>
</ul>
<aside class="notes">
<p>Was ist eine NPU knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. NPU ist eine Beschleunigerklasse, kein einheitlicher Befehlssatz. Nicht jede NPU ist ein systolisches Gitter oder nur Matrizen. DMA und Aufträge sind eine mögliche Organisation. Neural Processing Unit: Beschleuniger für Inferenz (manchmal Training). Namen: TPU (Google), Neural Engine (Apple), NVDLA, …. Verständnischeck: Ist NPU ein fester Befehlssatz? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="npu-vs.-gpu-vs.-cpu" class="slide level2">
<h2>NPU vs.&nbsp;GPU vs.&nbsp;CPU</h2>
<table class="caption-top">
<colgroup>
<col style="width: 8%">
<col style="width: 38%">
<col style="width: 23%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Optimierung</th>
<th>Stärke</th>
<th>Schwäche</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CPU</td>
<td>Latenz, Kontrollfluss</td>
<td>flexibel, auch kleine Modelle</td>
<td>braucht passende Datenversorgung</td>
</tr>
<tr class="even">
<td>GPU</td>
<td>Durchsatz, viele Threads</td>
<td>programmierbar, breite Lasten</td>
<td>Energie hängt von Modell und Batch ab</td>
</tr>
<tr class="odd">
<td>NPU</td>
<td>unterstützte neuronale Operatoren</td>
<td>viele lokale MACs bei passender Form</td>
<td>unpassende Operatoren bleiben auf der CPU</td>
</tr>
</tbody>
</table>
<p>Kombination ist möglich. Milliwatt gegen Watt ohne Messung bleibt offen.</p>
<aside class="notes">
<p>NPU vs.&nbsp;GPU vs.&nbsp;CPU knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Eine CPU kann für ein kleines Modell passen. Eine GPU ist nicht automatisch am Edge unbrauchbar. Milliwatt gegen Watt ohne Messung streichen. Latenz und Durchsatz sind verschieden. Verständnischeck: Kann die CPU reichen? Ja. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="flaschenhals-register-verdrahtung" class="slide level2">
<h2>Flaschenhals: Register / Verdrahtung</h2>
<ul>
<li>Wunsch: zehntausende MACs/Takt</li>
<li>Jede MAC braucht Operanden — unmöglich, unendlich viele Ports zum SRAM</li>
<li>Routing und Multiplexer begrenzen die Breite</li>
<li>Lösung: Daten lokal zwischen Zellen weiterreichen</li>
</ul>
<aside class="notes">
<p>Flaschenhals: Register / Verdrahtung knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. 65536 MACs mal zwei Int8-Operanden wären ohne Reuse 131072 Byte je Takt. Das ist ein hypothetischer Bedarf, keine TPU-Messung. Mehr Multiplizierer brauchen Datenwege. Wunsch: zehntausende MACs/Takt. Jede MAC braucht Operanden — unmöglich, unendlich viele Ports zum SRAM. Verständnischeck: Warum nicht nur mehr Multiplizierer? Die Operanden müssen ankommen. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="systolic-arrays" class="slide level2">
<h2>Systolic Arrays</h2>
<ul>
<li>2D-Gitter aus MAC-Zellen</li>
<li>Nur der Rand spricht mit dem Speicher</li>
<li>Ergebnisse/Operanden wandern zu Nachbarn — ohne Systembus pro Schritt</li>
</ul>
<aside class="notes">
<p>Systolic Arrays knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Im Lehrgitter wandert A nach rechts und B nach unten, C bleibt in der Zelle. Der Rand ist ein vereinfachtes Modell. Nachbarverbindungen ersetzen Vorladen und Readout nicht. 2D-Gitter aus MAC-Zellen. Nur der Rand spricht mit dem Speicher. Verständnischeck: Verschwindet der Speicher? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="systolisch-namensbild" class="slide level2">
<h2>„Systolisch“ — Namensbild</h2>
<ul>
<li>Systole: rhythmische Pumpwelle</li>
<li>Takt pumpt Werte wellenartig durch das Gitter</li>
<li>Pro Zyklus: Daten eine Zelle weiter (rechts/unten je nach Dataflow)</li>
</ul>
<aside class="notes">
<p>„Systolisch“ — Namensbild knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Ein Takt schiebt im Modell eine Zelle weiter. Leere Plätze rechnen nicht. Gleiche k-Indizes müssen in derselben Zelle zusammentreffen. Systole: rhythmische Pumpwelle. Takt pumpt Werte wellenartig durch das Gitter. Verständnischeck: Warum nicht alles ungeordnet einspeisen? Die Paare müssen sich treffen. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="eine-systolische-zelle" class="slide level2">
<h2>Eine systolische Zelle</h2>
<p>Pro Takt typisch:</p>
<ol type="1">
<li>Empfängt <span class="math inline">\(x\)</span> (links) und <span class="math inline">\(w\)</span> (oben)</li>
<li>MAC auf interne Teilsumme</li>
<li>Reicht <span class="math inline">\(x\)</span> nach rechts und <span class="math inline">\(w\)</span> nach unten weiter</li>
</ol>
<div class="cell" data-reveal="true" data-fig-width="3.2" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%
flowchart TD
  W[w von oben] --&gt; Z[MAC-Zelle]
  X[x von links] --&gt; Z
  Z --&gt; R[x nach rechts]
  Z --&gt; U[w nach unten]
  style Z fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Eine systolische Zelle knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. C startet bei null. Ein gültiges Paar addiert A mal B. A wird original weitergereicht, nicht als Produkt. Für C00 erst 1 mal 5 gleich 5, dann plus 2 mal 7 gleich 19. Verständnischeck: Warum A weiterreichen? Die Nachbarzelle braucht dasselbe A. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="weniger-ram-zugriffe" class="slide level2">
<h2>Weniger RAM-Zugriffe</h2>
<ul>
<li>Ein Wert wird einmal eingespeist und wandert durch viele Zellen</li>
<li>Viele MACs ohne erneuten Cache-/DRAM-Load</li>
<li>Im Lehrfall steigt die Intensity von 0,25 auf 0,5 Op/Byte. Der Knick liegt bei 1</li>
</ul>
<aside class="notes">
<p>Weniger RAM-Zugriffe knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. 16 Ops auf 64 Byte sind 0,25 Op je Byte, auf 32 Byte 0,5. Der Knick liegt bei 1. Beide Punkte bleiben speicherbegrenzt. Lokale Bewegung kostet ebenfalls Energie. Ein Wert wird einmal eingespeist und wandert durch viele Zellen. Viele MACs ohne erneuten Cache-/DRAM-Load. Verständnischeck: Beseitigt die doppelte Intensity die Grenze? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="datenfluss-füllt-das-array" class="slide level2">
<h2>Datenfluss füllt das Array</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/08_ki_beschleuniger_edge_ai/array.png"></p>
<figcaption>C00 fertig in Takt 2, C01 und C10 in Takt 3, C11 in Takt 4.</figcaption>
</figure>
</div>
<p><span class="math inline">\(2\times 2\)</span>-Idee (schematisch):</p>
<ul>
<li>Takt 1: erste Paare treffen sich, Summen starten</li>
<li>Takt 2: Wellen wandern, neue Werte am Rand</li>
<li>Im 2×2-Output-Stationary-Beispiel enden die vier Summen in den Takten 2, 3, 3 und 4</li>
<li>Das ist kein Ergebnis je Takt ab Takt 3. Readout der lokalen Summen kommt danach</li>
</ul>
<aside class="notes">
<p>Datenfluss füllt das Array knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. A kommt in Zeile i zur Zeit 1 plus k plus i, B in Spalte j zur Zeit 1 plus k plus j. C00 ist in Takt 1 gleich 5 und in Takt 2 fertig mit 19. C11 wird in Takt 3 gleich 18 und in Takt 4 gleich 50. Acht gültige MACs, nicht ein Ergebnis je Takt ab Takt 3. Takt 1: erste Paare treffen sich, Summen starten. Takt 2: Wellen wandern, neue Werte am Rand. Verständnischeck: Warum startet C11 später? Zeile und Spalte sind gestaffelt. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="weight-stationary" class="slide level2">
<h2>Weight-Stationary</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/08_ki_beschleuniger_edge_ai/stationary.png"></p>
<figcaption>Output-Stationary hält C. Weight-Stationary hält das Gewicht und muss es trotzdem laden.</figcaption>
</figure>
</div>
<ul>
<li>Gewichte während einer Inferenz oft konstant</li>
<li>Variante: Weights in Zellen „parken“, nur Activations durchschieben</li>
<li>Weniger Bewegungen der großen Konstanten-Matrizen</li>
</ul>
<aside class="notes">
<p>Weight-Stationary knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Weight-Stationary hält Gewichte nur für den benannten Zeitraum. Ein Tilewechsel kann neu laden. Aktivierungen und Teilsummen bewegen sich weiter. Gewichte während einer Inferenz oft konstant. Variante: Weights in Zellen „parken“, nur Activations durchschieben. Verständnischeck: Werden Gewichte nie wieder geladen? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="beispiel-google-tpu-v1" class="slide level2">
<h2>Beispiel: Google TPU v1</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/08_ki_beschleuniger_edge_ai/tops.png"></p>
<figcaption>91,75 TOPS Peak bei zwei Ops je MAC. Ein 2×2-Tile nutzt 4 von 16 gedachten Zellen.</figcaption>
</figure>
</div>
<ul>
<li><span class="math inline">\(256\times 256 = 65\,536\)</span> Int8-MACs. Bei 700 MHz sind das 45,8752 TMAC/s</li>
<li>Mit zwei Ops je MAC: 91,7504 TOPS, in der Originalarbeit oft 92 TOPS. Das ist Peak, kein End-to-End</li>
<li>TPU v1 ist ein Datacenter-Baustein, kein Milliwatt-Edge-Teil</li>
</ul>
<aside class="notes">
<p>Beispiel: Google TPU v1 knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. 256 mal 256 ist 65536. Mal 700 MHz sind 45,8752 Billionen MACs je Sekunde. Mal zwei Ops sind 91,75 TOPS, gerundet 92. Das ist Peak, keine Inferenzrate. Ein 2 mal 2 Tile in 4 mal 4 belegt räumlich 25 Prozent. Über vier Takte sind zeitlich 8 durch 64 gleich 12,5 Prozent. Auf dem 2 mal 2 selbst sind es 50 Prozent. <span class="math inline">\(256\times 256 = 65\,536\)</span> Int8-MACs. Bei 700 MHz sind das 45,8752 TMAC/s. Mit zwei Ops je MAC: 91,7504 TOPS, in der Originalarbeit oft 92 TOPS. Das ist Peak, kein End-to-End. Verständnischeck: Was sind 92 TOPS? Ein gerundeter Rechenpeak, kein End-to-End-Wert. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="npus-am-edge" class="slide level2">
<h2>NPUs am Edge</h2>
<ul>
<li>SoCs mit kleineren Arrays (z. B. <span class="math inline">\(32\times 32\)</span> / <span class="math inline">\(64\times 64\)</span>)</li>
<li>CPU, Vorverarbeitung und NPU gehören zusammen. Ein Betriebssystem ist optional</li>
<li>Die CPU schläft nur, wenn Versorgung, Wakeup und übrige Aufgaben das erlauben</li>
</ul>
<aside class="notes">
<p>NPUs am Edge knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. 32 mal 32 ist eine Schemazeichnung, keine SoC-Konfiguration. Die CPU schläft nur, wenn Versorgung, Steuerung und übrige Aufgaben das erlauben. SoCs mit kleineren Arrays (z. B. <span class="math inline">\(32\times 32\)</span> / <span class="math inline">\(64\times 64\)</span>). CPU: OS, Netz; NPU: Bild/Audio-Inferenz (oft per DMA gefüttert). Verständnischeck: Schläft die CPU bei jeder Inferenz? Nicht zwingend. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="grenzen-systolischer-arrays" class="slide level2">
<h2>Grenzen systolischer Arrays</h2>
<ul>
<li>Starr an Array-/Tile-Größen — Padding bei ungünstigen Layern</li>
<li>Dense-Matrizen stark; Sparse (viele Nullen) weniger effizient</li>
<li>Kein General Purpose — kein TCP/IP-Stack auf der NPU</li>
</ul>
<aside class="notes">
<p>Grenzen systolischer Arrays knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. 25 Prozent belegte Zellen sind nicht 25 Prozent zeitliche Auslastung. Dichte Nullen sparen nur mit passender Sparse-Ausführung MACs. Nicht jede NPU ist gleich starr. Starr an Array-/Tile-Größen — Padding bei ungünstigen Layern. Dense-Matrizen stark; Sparse (viele Nullen) weniger effizient. Verständnischeck: Sind Belegung und Auslastung gleich? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="kurzfazit-npu" class="slide level2">
<h2>Kurzfazit NPU</h2>
<ul>
<li>Systolic Arrays: lokale Weitergabe statt Von-Neumann-Pendeln</li>
<li>Wellenartiger Datenfluss, hohe Wiederverwendung</li>
<li>Weight-Stationary spart Bewegungen</li>
<li>TOPS je Watt brauchen gemessene Leistung derselben Grenze, nicht nur den Peak</li>
</ul>
<aside class="notes">
<p>Kurzfazit NPU knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Lokale Weitergabe senkt bestimmten Verkehr. TOPS je Watt brauchen gemessene Watt derselben Grenze. 92 TOPS ohne Leistung sind keine TOPS je Watt. Systolic Arrays: lokale Weitergabe statt Von-Neumann-Pendeln. Wellenartiger Datenfluss, hohe Wiederverwendung. Verständnischeck: Kann man TOPS je Watt ohne Watt rechnen? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="aufgabe-takt-4" class="slide level2">
<h2>Aufgabe — Takt 4</h2>
<p>Wann ist C11 im 2×2-Output-Stationary-Beispiel fertig? Ist 92 TOPS eine End-to-End-Leistung?</p>
<aside class="notes">
<p>Aufgabe — Takt 4 knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. C11 erhält 3 mal 6 gleich 18 in Takt 3 und 4 mal 8 gleich 32 in Takt 4, Summe 50. Der Readout ist ein eigener Schritt. Die TOPS-Rechnung ist 65536 mal 700 Millionen mal 2. Verständnischeck: Ist C11 dann schon außen gelesen? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="edge-ai-software-das-problem" class="slide level2">
<h2>Edge-AI-Software: das Problem</h2>
<ul>
<li>Training oft in Python (TensorFlow/PyTorch) auf GPUs — große Float32-Modelle</li>
<li>MCU: kein Python, knappes SRAM, oft keine FPU</li>
<li>Wie wird das Cloud-Modell zu Bare-Metal-C?</li>
</ul>
<aside class="notes">
<p>Edge-AI-Software: das Problem knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Das Modellarray ist Daten. Kernel in der Firmware führen Operatoren aus. Cloud ist nicht unbegrenzt. Nicht jede MCU hat eine FPU. Training oft in Python (TensorFlow/PyTorch) auf GPUs — große Float32-Modelle. MCU: kein Python, knappes SRAM, oft keine FPU. Verständnischeck: Wird aus dem Array automatisch ein C-Programm? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="tensorflow-lite-for-microcontrollers-tflm" class="slide level2">
<h2>TensorFlow Lite for Microcontrollers (TFLM)</h2>
<ul>
<li>Kleine C++-Runtime. Ohne verpflichtendes OS und mit Arena möglich. Der übrige Stack ist nicht automatisch heapfrei</li>
<li>Nimmt kompaktes Modell, interpretiert Layer (Conv2D, Dense, …)</li>
<li>Rechnet mit Firmware-Kerneln. Eine NPU braucht ein passendes Backend, nicht nur das Silizium</li>
</ul>
<aside class="notes">
<p>TensorFlow Lite for Microcontrollers (TFLM) knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. TFLM ist eine kleine C++-Runtime. Sie kann ohne Betriebssystem mit einer Arena arbeiten. Das ganze Firmwareprojekt ist dadurch nicht heapfrei. Ein NPU-Backend ist extra. Hier liegt kein Commit vor. Kleine C++-Runtime für MCUs (ohne OS, ohne <code>malloc</code>). Nimmt kompaktes Modell, interpretiert Layer (Conv2D, Dense, …). Verständnischeck: Wer rechnet: Bytes oder Kernel? Die Kernel. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="workflow-embedded-ai" class="slide level2">
<h2>Workflow Embedded AI</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/08_ki_beschleuniger_edge_ai/flow.png"></p>
<figcaption>Das C-Array sind Modelldaten. Invoke läuft über Kernel, nicht als Modell-Maschinencode.</figcaption>
</figure>
</div>
<ol type="1">
<li>Trainieren (Cloud / Python)</li>
<li>Konvertieren → <code>.tflite</code></li>
<li>Export als C-Byte-Array (<code>xxd</code> o. Ä.)</li>
<li>Linken in Flash (<code>.rodata</code>)</li>
<li>Firmware: <code>Invoke()</code> / Interpreter</li>
</ol>
<aside class="notes">
<p>Workflow Embedded AI knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Offline entstehen geprüfte Bytes, online laufen Kernel. .rodata ist ein Linkerbereich, nicht automatisch Flash. Der Export allein genügt nicht. Verständnischeck: Warum genügt das Array nicht? Operatoren, Laufzeit und Speicher fehlen. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="quantisierung" class="slide level2">
<h2>Quantisierung</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/figures/08_ki_beschleuniger_edge_ai/quant.png"></p>
<figcaption>1,24 wird 12 und zurück 1,2. 20 wird auf 127 begrenzt. Flash und SRAM bleiben getrennt.</figcaption>
</figure>
</div>
<ul>
<li>Float32: 4 Byte/Gewicht, teuer ohne FPU</li>
<li>Reine Float32-Gewichte werden als Int8 um 75 Prozent kleiner. Bias, Aktivierungen und Arena nicht automatisch</li>
<li>Integer ist nicht auf jeder CPU schneller. Den Accuracy-Verlust messen, nicht annehmen</li>
</ul>
<aside class="notes">
<p>Quantisierung knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. real gleich s mal (q minus z). Bei s 0,1 und z 0 wird 1,24 zu 12 und zurück 1,2, Fehler 0,04. 20 wird auf 127 geklemmt, Rückwert 12,7, Fehler 7,3. Minus 20 wird minus 128, Rückwert minus 12,8. Bei z minus 3 ist die kodierte Null minus 3. 75 Prozent gelten nur für reine Gewichtbytes von 4 auf 1. Float32: 4 Byte/Gewicht, teuer ohne FPU. Reine Float32-Gewichte werden als Int8 um 75 Prozent kleiner. Bias, Aktivierungen und Arena nicht automatisch. Verständnischeck: Warum ist die Null bei z minus 3 gleich minus 3? Weil s mal null bleibt null. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="pruning" class="slide level2">
<h2>Pruning</h2>
<ul>
<li>Viele Gewichte nahe null nach dem Training</li>
<li>Pruning braucht eine sparsityfähige Darstellung und einen passenden Kernel</li>
<li>Flash-Ersparnis und weniger ausgeführte MACs sind zwei verschiedene Folgen</li>
</ul>
<aside class="notes">
<p>Pruning knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Vier dichte Bytes bleiben vier Bytes, auch wenn zwei null sind. Sparse-Speicher braucht Indizes. Ein Nullgewicht spart nur dann eine MAC, wenn der Kernel sie überspringt. Viele Gewichte nahe null nach dem Training. Pruning braucht eine sparsityfähige Darstellung und einen passenden Kernel. Verständnischeck: Spart eine Null automatisch eine MAC? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="geplante-aktivitätserkennung" class="slide level2">
<h2>Geplante Aktivitätserkennung</h2>
<p>Geplanter Anwendungsfall, kein vorhandenes Labor:</p>
<ul>
<li>Unter 20 KB ist ein hypothetisches Modellziel, kein vorhandenes Modell</li>
<li>Ein 3-Achsen-Fenster wäre später an die I2C-Pipeline anzuschließen</li>
<li>Klassen Stehen, Gehen, Laufen sind noch kein Schrittzähler</li>
<li>Renode, <code>.repl</code> und Runtime liegen hier nicht vor</li>
</ul>
<aside class="notes">
<p>Geplante Aktivitätserkennung knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Stehen, Gehen und Laufen sind Fensterklassen, keine gezählten Schritte. Unter 20 KB ist ein hypothetisches Ziel, kein vorhandenes Modell. Es gibt keine .repl. Kleines quantisiertes Modell (<span class="math inline">\(&lt; 20\,\mathrm{KB}\)</span>). Eingabe: 3-Achsen-Beschleunigung (Anknüpfung I2C, Block 5). Verständnischeck: Ist jedes Gehen-Fenster ein Schritt? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="modell-als-c-array" class="slide level2">
<h2>Modell als C-Array</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb5-1"><a aria-label="1"></a><span class="co">/* Platzhalter, kein gültiges Modell und keine Lizenzdatei. */</span></span>
<span id="cb5-2"><a aria-label="2"></a><span class="dt">const</span> <span class="dt">unsigned</span> <span class="dt">char</span> step_model_tflite<span class="op">[]</span></span>
<span id="cb5-3"><a aria-label="3"></a>    __attribute__<span class="op">((</span>aligned<span class="op">(</span><span class="dv">4</span><span class="op">)))</span> <span class="op">=</span> <span class="op">{</span></span>
<span id="cb5-4"><a aria-label="4"></a>    <span class="bn">0x1c</span><span class="op">,</span> <span class="bn">0x00</span><span class="op">,</span> <span class="bn">0x00</span><span class="op">,</span> <span class="bn">0x00</span><span class="op">,</span> <span class="bn">0x54</span><span class="op">,</span> <span class="bn">0x46</span><span class="op">,</span> <span class="bn">0x4c</span><span class="op">,</span> <span class="bn">0x33</span><span class="op">,</span></span>
<span id="cb5-5"><a aria-label="5"></a>    <span class="co">/* … weitere Bytes … */</span></span>
<span id="cb5-6"><a aria-label="6"></a><span class="op">};</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Modell als C-Array knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Die acht Bytes mit TFL3 sind kein gültiges Modell und kein Maschinencode. const legt nicht allein ins Flash. Eine Ausrichtung ist compilerspezifisch. Verständnischeck: Beweist TFL3 ein Netz? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="tensor-arena" class="slide level2">
<h2>Tensor Arena</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb6-1"><a aria-label="1"></a><span class="co">/* Pseudocode. Kein TFLM-Build und kein gültiges Modell.</span></span>
<span id="cb6-2"><a aria-label="2"></a><span class="co">   Ein Kontext bleibt über Setup und Run gültig. */</span></span>
<span id="cb6-3"><a aria-label="3"></a><span class="at">static</span> <span class="dt">int</span> ready<span class="op">;</span></span>
<span id="cb6-4"><a aria-label="4"></a></span>
<span id="cb6-5"><a aria-label="5"></a><span class="dt">int</span> setup<span class="op">(</span><span class="dt">void</span><span class="op">)</span> <span class="op">{</span></span>
<span id="cb6-6"><a aria-label="6"></a>    <span class="cf">if</span> <span class="op">(</span>model_blob_invalid<span class="op">())</span> <span class="cf">return</span> <span class="op">-</span><span class="dv">1</span><span class="op">;</span></span>
<span id="cb6-7"><a aria-label="7"></a>    <span class="cf">if</span> <span class="op">(</span>plan_tensors<span class="op">()</span> <span class="op">!=</span> <span class="dv">0</span><span class="op">)</span> <span class="cf">return</span> <span class="op">-</span><span class="dv">3</span><span class="op">;</span></span>
<span id="cb6-8"><a aria-label="8"></a>    ready <span class="op">=</span> <span class="dv">1</span><span class="op">;</span></span>
<span id="cb6-9"><a aria-label="9"></a>    <span class="cf">return</span> <span class="dv">0</span><span class="op">;</span></span>
<span id="cb6-10"><a aria-label="10"></a><span class="op">}</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li>1024 Byte Arena sind eine Lehrannahme</li>
<li>Der lokale Interpreter der alten Fassung endete mit der Funktion</li>
</ul>
<aside class="notes">
<p>Tensor Arena knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Der alte lokale Interpreter endete mit return. Setup und Run brauchen denselben langlebigen Kontext. 1024 Byte sind eine Lehrannahme, kein Budget für ein 20-KB-Modell. Ohne gültigen Blob wird nicht dereferenziert. Ein zu kleiner Puffer lässt die Planung scheitern. 1024 Byte Arena sind eine Lehrannahme. Der lokale Interpreter der alten Fassung endete mit der Funktion. Verständnischeck: Warum genügt return 0 nicht? Das Objekt und das Budget bleiben sonst offen. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="inferenz-zyklus" class="slide level2">
<h2>Inferenz-Zyklus</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb7-1"><a aria-label="1"></a><span class="co">/* Pseudocode. src hat m Float32-Werte, das Ziel m Int8-Elemente. */</span></span>
<span id="cb7-2"><a aria-label="2"></a><span class="dt">int</span> run_window<span class="op">(</span><span class="at">const</span> <span class="dt">float</span> <span class="op">*</span>src<span class="op">,</span> <span class="dt">size_t</span> m<span class="op">)</span> <span class="op">{</span></span>
<span id="cb7-3"><a aria-label="3"></a>    <span class="cf">if</span> <span class="op">(!</span>ready <span class="op">||</span> src <span class="op">==</span> <span class="dv">0</span><span class="op">)</span> <span class="cf">return</span> <span class="op">-</span><span class="dv">1</span><span class="op">;</span></span>
<span id="cb7-4"><a aria-label="4"></a>    <span class="cf">if</span> <span class="op">(</span>input_elements<span class="op">()</span> <span class="op">!=</span> m<span class="op">)</span> <span class="cf">return</span> <span class="op">-</span><span class="dv">6</span><span class="op">;</span></span>
<span id="cb7-5"><a aria-label="5"></a>    <span class="cf">for</span> <span class="op">(</span><span class="dt">size_t</span> i <span class="op">=</span> <span class="dv">0</span><span class="op">;</span> i <span class="op">&lt;</span> m<span class="op">;</span> i<span class="op">++)</span></span>
<span id="cb7-6"><a aria-label="6"></a>        input_i8<span class="op">[</span>i<span class="op">]</span> <span class="op">=</span> quantize_f32<span class="op">(</span>src<span class="op">[</span>i<span class="op">]);</span></span>
<span id="cb7-7"><a aria-label="7"></a>    <span class="cf">if</span> <span class="op">(</span>invoke<span class="op">()</span> <span class="op">!=</span> <span class="dv">0</span><span class="op">)</span> <span class="cf">return</span> <span class="op">-</span><span class="dv">8</span><span class="op">;</span></span>
<span id="cb7-8"><a aria-label="8"></a>    <span class="cf">return</span> status_only<span class="op">();</span> <span class="co">/* Klasse und Score getrennt */</span></span>
<span id="cb7-9"><a aria-label="9"></a><span class="op">}</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><code>sizeof</code> eines Zeigers zählt nicht die Fensterelemente</li>
<li>Drei Ausgabebytes beweisen keine drei Klassen und keine Schrittzahl</li>
</ul>
<aside class="notes">
<p>Inferenz-Zyklus knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. m Float32-Werte brauchen 4m Quellbytes und m Int8-Ziele. sizeof eines Zeigers zählt den Puffer nicht. Invoke ohne Erfolg liefert keinen Score. Drei Bytes beweisen keine Klasse Gehen. Status, Index und Score bleiben getrennt. Zwölf Floatwerte wären 48 Quellbytes und 12 Int8-Ziele. <code>sizeof</code> eines Zeigers zählt nicht die Fensterelemente. Drei Ausgabebytes beweisen keine drei Klassen und keine Schrittzahl. Verständnischeck: Brauchen 12 Floatwerte 12 Bytes? Nein, 48. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="renode-virtuelle-stimuli" class="slide level2">
<h2>Renode: virtuelle Stimuli</h2>
<ul>
<li>Geplanter späterer Ausblick. Keine .repl und kein Modell liegen vor</li>
<li>Eine Konsole wäre eine funktionale Beobachtung, keine Zyklusmessung</li>
</ul>
<aside class="notes">
<p>Renode: virtuelle Stimuli knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Ohne Plattform, Firmware und Modell gibt es keine Konsole und kein .resc. Eine spätere Klasse wäre funktional, keine Energiezahl. Geplanter späterer Ausblick. Keine .repl und kein Modell liegen vor. Eine Konsole wäre eine funktionale Beobachtung, keine Zyklusmessung. Verständnischeck: Beweist die Konsole Zyklen? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="erwartung-cpu-ohne-npu" class="slide level2">
<h2>Erwartung: CPU ohne NPU</h2>
<ul>
<li>RV32IM ohne FPU kann Float in Software rechnen. Der Aufwand ist hier nicht gemessen</li>
<li>Eine funktionale Simulation belegt weder die Memory Wall noch eine NPU-Beschleunigung</li>
<li>Int8 auf der CPU kann sinnvoll sein. Eine CPU ohne NPU ist nicht automatisch falsch</li>
</ul>
<aside class="notes">
<p>Erwartung: CPU ohne NPU knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. RV32IM ohne FPU kann Float in Software rechnen. Der Aufwand ist nicht gemessen. Int8 auf der CPU kann passen. MIPS sind keine Megahertz. RV32IM ohne FPU kann Float in Software rechnen. Der Aufwand ist hier nicht gemessen. Eine funktionale Simulation belegt weder die Memory Wall noch eine NPU-Beschleunigung. Verständnischeck: Ist die CPU ohne NPU falsch? Nein. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="zusammenfassung-block-8" class="slide level2">
<h2>Zusammenfassung Block 8</h2>
<ul>
<li>DLP ist Datenparallelität. SIMD und RVV sind Umsetzungen, keine Definition</li>
<li>Systolische Arrays reduzieren bestimmten globalen Verkehr und brauchen Fill und Readout</li>
<li>TFLM-Bytes sind Modelldaten. Die Kernel führen die Operatoren aus</li>
<li>Quantisierung spart bestimmte Gewichtbytes, keine garantierte Genauigkeit</li>
</ul>
<aside class="notes">
<p>Zusammenfassung Block 8 knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Die Ansätze eint passende Datenversorgung und lokale Wiederverwendung. DLP, RVV und systolische Arrays bleiben verschiedene Mechanismen. DLP ist Datenparallelität. SIMD und RVV sind Umsetzungen, keine Definition. Systolische Arrays reduzieren bestimmten globalen Verkehr und brauchen Fill und Readout. Verständnischeck: Welche Aussage verbindet sie? Gleichartige Rechnung braucht passende Versorgung. Die nächste Folie nimmt die noch offene Frage auf. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ausblick-und-abschluss" class="slide level2">
<h2>Ausblick und Abschluss</h2>
<ul>
<li>Geplante Aktivitätserkennung, hier nicht ausgeführt</li>
<li>Es fehlen Modell, Tensorvertrag, Kernel und Plattform</li>
</ul>
<p>Vielen Dank.</p>
<aside class="notes">
<p>Ausblick und Abschluss knüpft an die bisherige Frage nach Rechnung und Datenbewegung an. Geprüft sind Rechnungen und Semantik. Nicht geprüft sind Kompilierung, Inferenz und Renode. Eine spätere Integration braucht Modell, Vertrag, Kernel und Plattform. Geplante Aktivitätserkennung, hier nicht ausgeführt. Es fehlen Modell, Tensorvertrag, Kernel und Plattform. Verständnischeck: Was wurde nicht ausgeführt? Firmware, Training und Simulation. Ein späterer Versuch braucht Modell, Kernel und Plattform. Zahlen sind Lehrannahmen. Code ist Lehrcode und wurde nicht kompiliert, trainiert oder ausgeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="../assets/dhbw_logo.svg" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 8.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script>
    /**
     * Fit Quarto/Reveal Mermaid SVGs to remaining slide space.
     * Dimensions from getBoundingClientRect are viewport pixels; CSS sizes inside
     * Reveal slides are unscaled — divide by Reveal.getScale().
     */
    (function () {
      const BOTTOM_PAD = 36;
      const SIDE_PAD_RATIO = 0.92;
      const MAX_SCALE = 3.4;

      function presentSlide() {
        var present = document.querySelector("section.present");
        if (!present) return null;
        var nested = present.querySelector(":scope > section.present");
        return nested || present;
      }

      function revealScale() {
        if (window.Reveal && typeof Reveal.getScale === "function") {
          var s = Reveal.getScale();
          return s > 0.05 ? s : 1;
        }
        return 1;
      }

      function ensureWrap(svg) {
        var parent = svg.parentElement;
        if (!parent) return null;
        if (parent.classList.contains("mermaid-fit")) return parent;
        var wrap = document.createElement("div");
        wrap.className = "mermaid-fit";
        parent.insertBefore(wrap, svg);
        wrap.appendChild(svg);
        return wrap;
      }

      function contentBottomAbove(slide, wrap) {
        var top = slide.getBoundingClientRect().top;
        var bottom = top + 8;
        var children = slide.children;
        for (var i = 0; i < children.length; i++) {
          var el = children[i];
          if (el === wrap || el.classList.contains("mermaid-fit")) break;
          if (el.querySelector && el.querySelector("svg.mermaid-js")) break;
          if (el.tagName === "ASIDE") continue;
          var r = el.getBoundingClientRect();
          if (r.height > 1) bottom = Math.max(bottom, r.bottom);
        }
        return bottom;
      }

      function naturalSize(svg) {
        if (svg.dataset.natW && svg.dataset.natH) {
          return { w: +svg.dataset.natW, h: +svg.dataset.natH };
        }
        var vb = svg.viewBox && svg.viewBox.baseVal;
        if (vb && vb.width > 0 && vb.height > 0) {
          svg.dataset.natW = String(vb.width);
          svg.dataset.natH = String(vb.height);
          return { w: vb.width, h: vb.height };
        }
        var wAttr = parseFloat(svg.getAttribute("width"));
        var hAttr = parseFloat(svg.getAttribute("height"));
        if (wAttr > 0 && hAttr > 0) {
          svg.dataset.natW = String(wAttr);
          svg.dataset.natH = String(hAttr);
          return { w: wAttr, h: hAttr };
        }
        var r = svg.getBoundingClientRect();
        var rs = revealScale();
        var w = r.width / rs || 320;
        var h = r.height / rs || 120;
        svg.dataset.natW = String(w);
        svg.dataset.natH = String(h);
        return { w: w, h: h };
      }

      function fitMermaids() {
        var slide = presentSlide();
        if (!slide) return;

        var rs = revealScale();
        var slideRect = slide.getBoundingClientRect();
        var svgs = slide.querySelectorAll("svg.mermaid-js");

        for (var i = 0; i < svgs.length; i++) {
          var svg = svgs[i];
          var wrap = ensureWrap(svg);
          if (!wrap) continue;

          svg.style.removeProperty("transform");
          svg.style.removeProperty("max-width");
          svg.style.removeProperty("zoom");
          wrap.style.zoom = "";

          var nat = naturalSize(svg);
          var above = contentBottomAbove(slide, wrap);
          var availW = (slideRect.width * SIDE_PAD_RATIO) / rs;
          var availH = Math.max(72, (slideRect.bottom - above - BOTTOM_PAD) / rs);

          var scale = Math.min(availW / nat.w, availH / nat.h, MAX_SCALE);
          if (!(scale > 0)) scale = 1;

          var targetW = Math.max(1, Math.round(nat.w * scale));
          var targetH = Math.max(1, Math.round(nat.h * scale));

          svg.setAttribute("width", targetW);
          svg.setAttribute("height", targetH);
          svg.style.width = targetW + "px";
          svg.style.height = targetH + "px";
          svg.style.display = "block";
          svg.style.margin = "0.35rem auto 0";
        }
      }

      function scheduleFit() {
        requestAnimationFrame(function () {
          fitMermaids();
          setTimeout(fitMermaids, 150);
          setTimeout(fitMermaids, 500);
          setTimeout(fitMermaids, 1100);
        });
      }

      window.addEventListener("load", scheduleFit);

      function bindReveal() {
        if (!window.Reveal || !Reveal.on) return false;
        Reveal.on("ready", scheduleFit);
        Reveal.on("slidechanged", scheduleFit);
        if (Reveal.isReady && Reveal.isReady()) scheduleFit();
        return true;
      }

      if (!bindReveal()) {
        window.addEventListener("load", function () {
          var tries = 0;
          var id = setInterval(function () {
            if (bindReveal() || ++tries > 50) clearInterval(id);
          }, 100);
        });
      }

      window.dhbwMermaidFit = fitMermaids;
    })();
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Kopiert");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Kopiert");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/dantschi\.github\.io\/mct3\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>