project:
  type: default

format:
  pdf:
    toc: false
    number-sections: false
    colorlinks: true
    highlight-style: github
    geometry:
      - top=25mm
      - left=25mm
      - right=25mm
      - bottom=25mm
